/*
 * $Id: dmux.h 1.18.6.2 Broadcom SDK $
 * 
 * $Copyright: Copyright 2011 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 */

#ifndef __BCM_DMUX_H__
#define __BCM_DMUX_H__

#include <bcm/types.h>

#define BCM_MAX_DMUX_PAIRS      64         

/* Configuration flags to select packet parameters. */
#define BCM_DMUX_L4DS           0x00000001 /* TCP/UDP destination socket. */
#define BCM_DMUX_L4SS           0x00000002 /* TCP/UDP source socket. */
#define BCM_DMUX_IPDA           0x00000004 /* Destination IP address. */
#define BCM_DMUX_IPSA           0x00000008 /* Source IP address. */
#define BCM_DMUX_IPVID          0x00000010 /* IP: VLAN ID. */
#define BCM_DMUX_IPTYPE         0x00000020 /* IP: Ethertype. */
#define BCM_DMUX_IPMACDA        0x00000040 /* IP: MAC destination address. */
#define BCM_DMUX_IPMACSA        0x00000080 /* IP: MAC source address. */
#define BCM_DMUX_VID            0x00000100 /* Non-IP: VLAN ID. */
#define BCM_DMUX_TYPE           0x00000200 /* Non-IP: Ethertype. */
#define BCM_DMUX_MACDA          0x00000400 /* Non-IP: MAC destination address. */
#define BCM_DMUX_MACSA          0x00000800 /* Non-IP: MAC source address. */

#ifndef BCM_HIDE_DISPATCHABLE

/* Initializes the DMUX system for a unit. */
extern int bcm_dmux_init(
    int unit);

/* Clean up the DMUX tables. */
extern int bcm_dmux_detach(
    int unit);

/* Set/retrieve demuxing configuration of a port. */
extern int bcm_dmux_config_set(
    int unit, 
    bcm_port_t port, 
    uint32 flags);

/* Set/retrieve demuxing configuration of a port. */
extern int bcm_dmux_config_get(
    int unit, 
    bcm_port_t port, 
    uint32 *flags);

/* Add/remove (module, port) pair to/from demux destinations for a port. */
extern int bcm_dmux_dest_add(
    int unit, 
    bcm_port_t port, 
    _shr_module_t dest_mod, 
    bcm_port_t dest_port);

/* Add/remove (module, port) pair to/from demux destinations for a port. */
extern int bcm_dmux_dest_delete(
    int unit, 
    bcm_port_t port, 
    int dest_mod, 
    bcm_port_t dest_port);

/* Clear (module, port) demux destinations for a port. */
extern int bcm_dmux_dest_delete_all(
    int unit, 
    bcm_port_t port);

/* 
 * Retrieve port bitmap of demux destinations for a given destination
 * module configured on the selected port.
 */
extern int bcm_dmux_dest_get(
    int unit, 
    bcm_port_t port, 
    int dest_mod, 
    bcm_pbmp_t *dest_pbmp);

#endif /* BCM_HIDE_DISPATCHABLE */

#endif /* __BCM_DMUX_H__ */
