/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: bcm53242_a0.c 1.50 Broadcom SDK $
 * $Copyright: Copyright 2011 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 * File:	bcm53242_a0.c
 * Purpose:	bcm53242_a0 chip specific information (register, memories, etc)
 */


#include <sal/core/libc.h>
#include <soc/defs.h>
#include <soc/mem.h>
#include <soc/mcm/robo/memregs.h>
#include <soc/mcm/robo/driver.h>
#include <soc/mcm/robo/allenum.h>
#include <soc/mcm/robo/intenum.h>

#if defined(BCM_53242_A0)
#include <soc/robo/bcm53242_service.h>

/* Chip specific top matter from memory file */

/* These are the null memory descriptions for BCM53242_A0 */

/* End of chip specific top matter */

static soc_reg_info_t *soc_registers_bcm53242_a0[] = {
    &soc_robo_reg_list[SOC_REG_INT_ACTLSTS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ACT_POL_DATA_BCM53242_A0r_ROBO],
    NULL,    /* ACT_POL_DATA0 */
    NULL,    /* ACT_POL_DATA1 */
    &soc_robo_reg_list[SOC_REG_INT_AEGSTS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_AGEOUT_CTLr_ROBO],
    NULL,    /* AGEOUT_EN_VID */
    &soc_robo_reg_list[SOC_REG_INT_AMODE2_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_AMPHY_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ANADV_BCM5347_A0r_ROBO],
    NULL,    /* ANADV_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_ANEXP_BCM5347_A0r_ROBO],
    NULL,    /* ANEXP_EXT_P5 */
    NULL,    /* ANLPA */
    &soc_robo_reg_list[SOC_REG_INT_ANLPAR_BCM5347_A0r_ROBO],
    NULL,    /* ANLPA_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_ANNXP_BCM5347_A0r_ROBO],
    NULL,    /* ANNXP_EXT_P5 */
    NULL,    /* ARLA_ENTRY */
    NULL,    /* ARLA_ENTRY0 */
    NULL,    /* ARLA_ENTRY1 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_ENTRY_0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_ENTRY_1r_ROBO],
    NULL,    /* ARLA_FWD_ENTRY0 */
    NULL,    /* ARLA_FWD_ENTRY1 */
    NULL,    /* ARLA_FWD_ENTRY2 */
    NULL,    /* ARLA_FWD_ENTRY3 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_MACr_ROBO],
    NULL,    /* ARLA_MACVID_ENTRY0 */
    NULL,    /* ARLA_MACVID_ENTRY1 */
    NULL,    /* ARLA_MACVID_ENTRY2 */
    NULL,    /* ARLA_MACVID_ENTRY3 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_RWCTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_ADR_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_CTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_BCM53242_A0r_ROBO],
    NULL,    /* ARLA_SRCH_RSLT_0 */
    NULL,    /* ARLA_SRCH_RSLT_1 */
    NULL,    /* ARLA_SRCH_RSLT_0_MACVID */
    NULL,    /* ARLA_SRCH_RSLT_1_MACVID */
    NULL,    /* ARLA_SRCH_RSLT_MACVID */
    NULL,    /* ARLA_SRCH_RSLT_MACVID_0 */
    NULL,    /* ARLA_SRCH_RSLT_MACVID_1 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_VID_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VID_BCM5348_A0r_ROBO],
    NULL,    /* ARLA_VID_ENTRY */
    NULL,    /* ARLA_VID_ENTRY0 */
    NULL,    /* ARLA_VID_ENTRY1 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VID_ENTRY_0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VID_ENTRY_1r_ROBO],
    NULL,    /* ARLA_VTBL_ADDR */
    NULL,    /* ARLA_VTBL_ENTRY */
    NULL,    /* ARLA_VTBL_RWCTRL */
    NULL,    /* ARL_SPAREREG0 */
    NULL,    /* ARL_SPAREREG1 */
    NULL,    /* ARL_SPAREREG2 */
    NULL,    /* ARL_SPAREREG3 */
    &soc_robo_reg_list[SOC_REG_INT_ASTSSUM_BCM5347_A0r_ROBO],
    NULL,    /* AUTH_8021X_CTL1 */
    NULL,    /* AUTH_8021X_CTL2 */
    NULL,    /* AUX_CONTROL_STATUS */
    NULL,    /* AUX_CONTROL_STATUS_EXT_P5 */
    NULL,    /* AUX_MODE */
    NULL,    /* AUX_MODE2 */
    NULL,    /* AUX_MODE2_EXT_P5 */
    NULL,    /* AUX_MODE_EXT_P5 */
    NULL,    /* AUX_MULTI_PHY */
    NULL,    /* AUX_MULTI_PHY_EXT_P5 */
    NULL,    /* AUX_STATUS_SUMMARY */
    NULL,    /* AUX_STATUS_SUMMARY_EXT_P5 */
    NULL,    /* AVB_AV_EN_CTRL */
    NULL,    /* AVB_C4_BW_CNTL */
    NULL,    /* AVB_C5_BW_CNTL */
    NULL,    /* AVB_EGRESS_TM_STAMP */
    NULL,    /* AVB_EGRESS_TS_PORTMAP */
    NULL,    /* AVB_EGRESS_TS_TM_STAMP */
    NULL,    /* AVB_LNK_STATUS */
    NULL,    /* AVB_MAX_AV_PKT_SZ */
    NULL,    /* AVB_SLOT_ADJ */
    NULL,    /* AVB_SLOT_TICK_CNTR */
    NULL,    /* AVB_TM_ADJ */
    NULL,    /* AVB_TM_BASE */
    NULL,    /* B100X_AUX_CONTROL */
    NULL,    /* B100X_AUX_CONTROL_EXT_P5 */
    NULL,    /* B100X_AUX_STATUS */
    NULL,    /* B100X_AUX_STATUS_EXT_P5 */
    NULL,    /* B100X_DISCONNECT_COUNTER */
    NULL,    /* B100X_DISCONNECT_COUNTER_EXT_P5 */
    NULL,    /* B100X_FALSE_CARRIER_SENSE_COUNTER */
    NULL,    /* B100X_FALSE_CARRIER_SENSE_COUNTER_EXT_P5 */
    NULL,    /* B100X_RX_ERROR_COUNTER */
    NULL,    /* B100X_RX_ERROR_COUNTER_EXT_P5 */
    NULL,    /* B10T_AUX_STATUS */
    NULL,    /* B10T_AUX_STATUS_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_BCAST_FWD_MAPr_ROBO],
    NULL,    /* BC_SUP_PKTDROP_CNT_IMP */
    NULL,    /* BC_SUP_PKTDROP_CNT_P */
    NULL,    /* BC_SUP_RATECTRL_IMP */
    NULL,    /* BC_SUP_RATECTRL_P */
    &soc_robo_reg_list[SOC_REG_INT_BG_SEL_BCM53242_A0r_ROBO],
    NULL,    /* BIST_STS */
    &soc_robo_reg_list[SOC_REG_INT_BIST_STS0_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_BIST_STS1_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_BONDING_PADr_ROBO],
    NULL,    /* BONDING_PAD_STATUS */
    NULL,    /* BOND_DIRECT_PIN */
    &soc_robo_reg_list[SOC_REG_INT_BPDU_MCADDRr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_BRCMTST_BCM5347_A0r_ROBO],
    NULL,    /* BRCM_HDR_CTRL */
    NULL,    /* BRCM_TAG_CTRL */
    NULL,    /* BROADCOM_TEST */
    NULL,    /* BROADCOM_TEST_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_BUFCON_MEMADR_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_BUFCON_MEMDAT0_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_BUFCON_MEMDAT1_BCM5348_A0r_ROBO],
    NULL,    /* C4_WEIGHT */
    &soc_robo_reg_list[SOC_REG_INT_CFP_ACC_BCM53242_A0r_ROBO],
    NULL,    /* CFP_CTL_REG */
    &soc_robo_reg_list[SOC_REG_INT_CFP_DATA_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CFP_EN_CTRLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CFP_GLOBAL_CTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CFP_MASK_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CFP_RCr_ROBO],
    NULL,    /* CFP_TEST */
    NULL,    /* CFP_UDF_0_A */
    NULL,    /* CFP_UDF_0_B08 */
    NULL,    /* CFP_UDF_0_C */
    NULL,    /* CFP_UDF_1_A */
    NULL,    /* CFP_UDF_1_C */
    NULL,    /* CFP_UDF_2_A */
    NULL,    /* CFP_UDF_2_B */
    NULL,    /* CFP_UDF_2_C */
    NULL,    /* CFP_UDF_3_D */
    &soc_robo_reg_list[SOC_REG_INT_CFP_UDF_Ar_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CFP_UDF_Br_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CFP_UDF_Cr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CFP_UDF_Dr_ROBO],
    NULL,    /* CFP_UNLCK */
    NULL,    /* CHIP0_PORT_AGE */
    NULL,    /* CHIP_REVID */
    &soc_robo_reg_list[SOC_REG_INT_CHIP_RST_CTL_BCM53242_A0r_ROBO],
    NULL,    /* CLASS_PCP */
    NULL,    /* CLKSET */
    NULL,    /* COMM_IRC_CON */
    NULL,    /* COS_VALUE_CTRL */
    NULL,    /* CPU2COS_MAP */
    NULL,    /* CPU_ADDRESS */
    NULL,    /* CPU_DATA1_SHARE */
    NULL,    /* CPU_DATA_SHARE */
    NULL,    /* CPU_MEM_RD_EN */
    NULL,    /* CPU_OTP_ADDR */
    NULL,    /* CPU_OTP_CTL */
    NULL,    /* CPU_OTP_RD_DATA */
    NULL,    /* CPU_OTP_STATUS */
    NULL,    /* CPU_OTP_WR_DATA */
    NULL,    /* CPU_RAM_ROM_SEL */
    NULL,    /* CPU_READ_DATA */
    NULL,    /* CPU_RESOURCE_ARBITER */
    &soc_robo_reg_list[SOC_REG_INT_CRC16_GP_BCM53242_A0r_ROBO],
    NULL,    /* CTRL_REG */
    NULL,    /* DEBUG_CONGESTION */
    &soc_robo_reg_list[SOC_REG_INT_DEBUG_REG_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_DEBUG_STSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_DEFAULT_1Q_TAG_BCM53242_A0r_ROBO],
    NULL,    /* DEFAULT_1Q_TAG_IMP */
    NULL,    /* DEF_PORT_QOS_CFG */
    NULL,    /* DF_TIMER */
    &soc_robo_reg_list[SOC_REG_INT_DIAGNOSISr_ROBO],
    NULL,    /* DIRECT_CTRL_PIN */
    NULL,    /* DIRECT_INPUT_CTRL_VALUE */
    NULL,    /* DIS_LEARN */
    NULL,    /* DMA_CTRL */
    NULL,    /* DMA_LPB_BUF_ADDR */
    NULL,    /* DMA_LPB_BUF_SIZE */
    NULL,    /* DOS_ATTACK_FILTER_DROP_CTL */
    NULL,    /* DOS_ATTACK_FILTER_EVENT */
    NULL,    /* DOS_CTRL */
    NULL,    /* DOS_DIS_LRN_REG */
    NULL,    /* DOU_TAG_TPID */
    NULL,    /* DP_CTRL */
    NULL,    /* DSCP2TC_DP_MAP0 */
    NULL,    /* DSCP2TC_DP_MAP1 */
    NULL,    /* DSCP2TC_DP_MAP2 */
    NULL,    /* DSCP2TC_DP_MAP3 */
    NULL,    /* DSCP2TC_DP_MAP4 */
    NULL,    /* DSCP2TC_DP_MAP5 */
    NULL,    /* DSCP2TC_DP_MAP6 */
    NULL,    /* DSCP2TC_DP_MAP7 */
    &soc_robo_reg_list[SOC_REG_INT_DTAG_GLO_CTL_BCM53242_A0r_ROBO],
    NULL,    /* DTAG_TPID */
    &soc_robo_reg_list[SOC_REG_INT_DUPSTS_BCM53242_A0r_ROBO],
    NULL,    /* EAP_DIP */
    &soc_robo_reg_list[SOC_REG_INT_EAP_GLO_CON_BCM53242_A0r_ROBO],
    NULL,    /* EAP_MULTI_ADDR_CTRL */
    NULL,    /* EAP_PORT_CTL */
    NULL,    /* EAV_LNK_STATUS */
    NULL,    /* EEE_DEBUG */
    NULL,    /* EEE_EN_CTRL */
    NULL,    /* EEE_GLB_CONG_TH */
    NULL,    /* EEE_LINK_DLY_TIMER */
    NULL,    /* EEE_LPI_ASSERT */
    NULL,    /* EEE_LPI_DURATION */
    NULL,    /* EEE_LPI_EVENT */
    NULL,    /* EEE_LPI_INDICATE */
    NULL,    /* EEE_MIN_LP_TIMER_G */
    NULL,    /* EEE_MIN_LP_TIMER_G_IMP */
    NULL,    /* EEE_MIN_LP_TIMER_H */
    NULL,    /* EEE_MIN_LP_TIMER_H_IMP */
    NULL,    /* EEE_PHY_CTRL */
    NULL,    /* EEE_PIPELINE_TIMER */
    NULL,    /* EEE_RX_IDLE_SYMBOL */
    NULL,    /* EEE_SLEEP_TIMER_G */
    NULL,    /* EEE_SLEEP_TIMER_G_IMP */
    NULL,    /* EEE_SLEEP_TIMER_H */
    NULL,    /* EEE_SLEEP_TIMER_H_IMP */
    NULL,    /* EEE_STATE */
    NULL,    /* EEE_TXQ_CONG_TH */
    NULL,    /* EEE_WAKE_TIMER_G */
    NULL,    /* EEE_WAKE_TIMER_G_IMP */
    NULL,    /* EEE_WAKE_TIMER_H */
    NULL,    /* EEE_WAKE_TIMER_H_IMP */
    &soc_robo_reg_list[SOC_REG_INT_EGMIRCTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EGMIRDIV_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EGMIRMAC_BCM5348_A0r_ROBO],
    NULL,    /* EGRESS_NAVB_PKT_TC2PCP_MAP */
    NULL,    /* EGRESS_NAVB_PKT_TC2PCP_MAP_IMP */
    NULL,    /* EGRESS_NRESE_PKT_TC2PCP_MAP */
    NULL,    /* EGRESS_NRESE_PKT_TC2PCP_MAP_8 */
    NULL,    /* EGRESS_NRESE_PKT_TC2PCP_MAP_IMP */
    &soc_robo_reg_list[SOC_REG_INT_EGRESS_RMONr_ROBO],
    NULL,    /* EGRESS_SFLOW */
    NULL,    /* EGRESS_VID_RMK_TBL_ACS */
    NULL,    /* EGRESS_VID_RMK_TBL_DATA */
    &soc_robo_reg_list[SOC_REG_INT_EN_IMP_CONG_REMAPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EN_IMP_HIGH_RATEr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EN_TOTAL_MC_DROP_IMPr_ROBO],
    NULL,    /* EQZ_CTRL */
    NULL,    /* EXP_PORT */
    NULL,    /* EXTPHY_SCAN_CTL */
    NULL,    /* EXT_ACTLSTS */
    NULL,    /* EXT_AEGSTS */
    NULL,    /* EXT_AMODE2 */
    NULL,    /* EXT_AMPHY */
    NULL,    /* EXT_ANADV */
    NULL,    /* EXT_ANEXP */
    NULL,    /* EXT_ANLPA */
    NULL,    /* EXT_ANNXP */
    NULL,    /* EXT_ASTSSUM */
    NULL,    /* EXT_BRCMTST */
    NULL,    /* EXT_HNDRD_ACTL */
    NULL,    /* EXT_HNDRD_ASTS */
    NULL,    /* EXT_HNDRD_FCSCNT */
    NULL,    /* EXT_HNDRD_RECNT */
    NULL,    /* EXT_LPNXP */
    NULL,    /* EXT_MIICTL */
    NULL,    /* EXT_MIISTS */
    NULL,    /* EXT_PHYIDH */
    NULL,    /* EXT_PHYIDL */
    NULL,    /* E_ACTLSTS */
    NULL,    /* E_AEGSTS */
    NULL,    /* E_AMODE2 */
    NULL,    /* E_AMPHY */
    NULL,    /* E_ANADV */
    NULL,    /* E_ANEXP */
    NULL,    /* E_ANLPA */
    NULL,    /* E_ANNXP */
    NULL,    /* E_ASTSSUM */
    NULL,    /* E_BRCMTST */
    NULL,    /* E_HNDRD_ACTL */
    NULL,    /* E_HNDRD_ASTS */
    NULL,    /* E_HNDRD_FCSCNT */
    NULL,    /* E_HNDRD_RECNT */
    NULL,    /* E_LPNXP */
    NULL,    /* E_MIICTL */
    NULL,    /* E_MIISTS */
    NULL,    /* E_PHYIDH */
    NULL,    /* E_PHYIDL */
    NULL,    /* FAST_AGE_CTL */
    NULL,    /* FAST_AGE_CTRL */
    NULL,    /* FAST_AGE_PORT */
    NULL,    /* FAST_AGE_VID */
    NULL,    /* FAST_AGING_CTL */
    NULL,    /* FAST_AGING_PORT */
    NULL,    /* FAST_AGING_VID */
    &soc_robo_reg_list[SOC_REG_INT_FCON_BCST_TH_CTRL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_DIAG_CTRL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_DLF_TH_CTRL_BCM53242_A0r_ROBO],
    NULL,    /* FCON_FLOWCON_STATUS0 */
    NULL,    /* FCON_FLOWCON_STATUS1 */
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS2_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS3_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS4r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS5r_ROBO],
    NULL,    /* FCON_FLOWCON_STATUS6 */
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS7r_ROBO],
    NULL,    /* FCON_FLOWCON_STATUS8 */
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS9r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS10_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS11_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS12_BCM5348_A0r_ROBO],
    NULL,    /* FCON_FLOWCON_STATUS13 */
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWMIX_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_GLOB_TH_CTRL_1_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_GLOB_TH_CTRL_2_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_MISC_CTRLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_MISC_TXFLOW_CTRL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_PERQ_TXDROP_CTRL_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q0_100_TH_CTRL_1_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q0_100_TH_CTRL_2_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q0_TXDSC_CTRL_3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q1_100_TH_CTRL_1_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q1_100_TH_CTRL_2_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q1_TXDSC_CTRL_3_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q2_100_TH_CTRL_1_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q2_100_TH_CTRL_2_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q2_TXDSC_CTRL_3_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q3_100_TH_CTRL_1_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q3_100_TH_CTRL_2_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_Q3_TXDSC_CTRL_3_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_RSRV_BUFNUM_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_RXBASE_BUFNUM_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_RX_FCON_CTRL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_SPARE0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_SPARE1_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_SPARE2r_ROBO],
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL0 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL1 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL2 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL3 */
    &soc_robo_reg_list[SOC_REG_INT_FCON_TXQ_FULL_TH_BCM5348_A0r_ROBO],
    NULL,    /* FC_CHIP_INFO */
    NULL,    /* FC_CHIP_INFO_1 */
    NULL,    /* FC_CHIP_INFO_2 */
    NULL,    /* FC_CONG_BUF_ERR_HIS */
    NULL,    /* FC_CONG_PORTMAP01 */
    NULL,    /* FC_CONG_PORTMAP8 */
    NULL,    /* FC_CONG_PORTMAP16 */
    NULL,    /* FC_CONG_PORTMAP23 */
    NULL,    /* FC_CONG_PORTMAP45 */
    NULL,    /* FC_CONG_PORTMAP67 */
    NULL,    /* FC_CONG_PORTMAP89 */
    NULL,    /* FC_CONG_PORTMAP1011 */
    NULL,    /* FC_CONG_PORTMAP1213 */
    NULL,    /* FC_CONG_PORTMAP1415 */
    NULL,    /* FC_DIAG_CTRL */
    NULL,    /* FC_GIGA_INFO */
    NULL,    /* FC_GIGA_INFO_1 */
    NULL,    /* FC_GIGA_INFO_2 */
    NULL,    /* FC_IMP_THRESH_ADJUST_Q */
    NULL,    /* FC_MCAST_DROP_CTRL */
    NULL,    /* FC_MCAST_DROP_CTRL_1 */
    NULL,    /* FC_MCAST_DROP_CTRL_2 */
    NULL,    /* FC_MON_TXQ */
    NULL,    /* FC_PAUSE_DROP_CTRL */
    NULL,    /* FC_PAUSE_HIS */
    NULL,    /* FC_PAUSE_HIS_1 */
    NULL,    /* FC_PAUSE_HIS_2 */
    NULL,    /* FC_PEAK_RXBYTE */
    NULL,    /* FC_PEAK_TOTAL_USED */
    NULL,    /* FC_PEAK_TXQ */
    NULL,    /* FC_PEAK_TXQ_45 */
    NULL,    /* FC_Q45_CONG_PORTMAP_8 */
    NULL,    /* FC_Q45_CONG_PORTMAP_0123 */
    NULL,    /* FC_Q45_CONG_PORTMAP_4567 */
    NULL,    /* FC_RXBUF_ERR_HIS */
    NULL,    /* FC_RXBUF_ERR_HIS_1 */
    NULL,    /* FC_RXBUF_ERR_HIS_2 */
    NULL,    /* FC_RXPAUSE_HIS */
    NULL,    /* FC_RXPAUSE_HIS_1 */
    NULL,    /* FC_RXPAUSE_HIS_2 */
    NULL,    /* FC_RX_HYST */
    NULL,    /* FC_RX_MAX_PTR */
    NULL,    /* FC_RX_RSRV */
    NULL,    /* FC_RX_RUNOFF */
    NULL,    /* FC_SPARE_REG */
    NULL,    /* FC_TOTAL_TH_DROP_Q */
    NULL,    /* FC_TOTAL_TH_DROP_Q45 */
    NULL,    /* FC_TOTAL_TH_DROP_Q_IMP */
    NULL,    /* FC_TOTAL_TH_DROP_Q_WAN */
    NULL,    /* FC_TOTAL_TH_HYST_Q */
    NULL,    /* FC_TOTAL_TH_HYST_Q45 */
    NULL,    /* FC_TOTAL_TH_HYST_Q_IMP */
    NULL,    /* FC_TOTAL_TH_HYST_Q_WAN */
    NULL,    /* FC_TOTAL_TH_PAUSE_Q */
    NULL,    /* FC_TOTAL_TH_PAUSE_Q45 */
    NULL,    /* FC_TOTAL_TH_PAUSE_Q_IMP */
    NULL,    /* FC_TOTAL_TH_PAUSE_Q_WAN */
    NULL,    /* FC_TOTAL_TH_RSRV_Q */
    NULL,    /* FC_TOTAL_USED */
    NULL,    /* FC_TXPAUSE_HIS */
    NULL,    /* FC_TXPAUSE_HIS_1 */
    NULL,    /* FC_TXPAUSE_HIS_2 */
    NULL,    /* FC_TXQ_TH_DROP_Q */
    NULL,    /* FC_TXQ_TH_DROP_Q45 */
    NULL,    /* FC_TXQ_TH_DROP_Q_IMP */
    NULL,    /* FC_TXQ_TH_DROP_Q_WAN */
    NULL,    /* FC_TXQ_TH_PAUSE_Q */
    NULL,    /* FC_TXQ_TH_PAUSE_Q45 */
    NULL,    /* FC_TXQ_TH_PAUSE_Q_IMP */
    NULL,    /* FC_TXQ_TH_PAUSE_Q_WAN */
    NULL,    /* FC_TXQ_TH_RSRV_Q */
    NULL,    /* FC_TXQ_TH_RSRV_Q45 */
    NULL,    /* FC_TXQ_TH_RSRV_Q_IMP */
    NULL,    /* FC_TXQ_TH_RSRV_Q_WAN */
    &soc_robo_reg_list[SOC_REG_INT_FLOW_MON_BUS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FM_MEMADR_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FM_MEMDAT0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FM_MEMDAT1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FM_MEMDAT2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FM_MEMDAT3r_ROBO],
    NULL,    /* FM_SIZE_CTL */
    NULL,    /* FORCE_FRAME_DROP */
    &soc_robo_reg_list[SOC_REG_INT_GARLCFGr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_GENMEM_ADDR_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_GENMEM_CTL_BCM53242_A0r_ROBO],
    NULL,    /* GENMEM_DATA */
    &soc_robo_reg_list[SOC_REG_INT_GENMEM_DATA0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_GENMEM_DATA1_BCM53242_A0r_ROBO],
    NULL,    /* GLB_ACTLSTS */
    NULL,    /* GLB_AEGSTS */
    NULL,    /* GLB_AMODE2 */
    NULL,    /* GLB_AMPHY */
    NULL,    /* GLB_ANADV */
    NULL,    /* GLB_ANEXP */
    NULL,    /* GLB_ANLPA */
    NULL,    /* GLB_ANNXP */
    NULL,    /* GLB_ASTSSUM */
    NULL,    /* GLB_BRCMTST */
    NULL,    /* GLB_HNDRD_ACTL */
    NULL,    /* GLB_HNDRD_ASTS */
    NULL,    /* GLB_HNDRD_FCSCNT */
    NULL,    /* GLB_HNDRD_RECNT */
    NULL,    /* GLB_LPNXP */
    NULL,    /* GLB_MIICTL */
    NULL,    /* GLB_MIISTS */
    NULL,    /* GLB_OVERFLOW_DROP_PKT_CNT */
    NULL,    /* GLB_PHYIDH */
    NULL,    /* GLB_PHYIDL */
    NULL,    /* GLB_VLAN_ING_FILTER_CTL */
    NULL,    /* GLOBAL_CONGESTION_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_GLOBAL_TRUNK_CTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_GMNGCFG_BCM53242_A0r_ROBO],
    NULL,    /* GREEN_MODE_DATA */
    NULL,    /* GREEN_MODE_DEBUG */
    NULL,    /* GREEN_MODE_SELECT */
    NULL,    /* GROUP_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_GRPADDR1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_GRPADDR2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_ANADVr_ROBO],
    NULL,    /* G_ANADV_EXT */
    NULL,    /* G_ANADV_EXT_P5 */
    NULL,    /* G_ANADV_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_ANEXPr_ROBO],
    NULL,    /* G_ANEXP_EXT */
    NULL,    /* G_ANEXP_EXT_P5 */
    NULL,    /* G_ANEXP_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_ANLPAr_ROBO],
    NULL,    /* G_ANLPA_EXT */
    NULL,    /* G_ANLPA_EXT_P5 */
    NULL,    /* G_ANLPA_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_ANNXPr_ROBO],
    NULL,    /* G_ANNXP_EXT */
    NULL,    /* G_ANNXP_EXT_P5 */
    NULL,    /* G_ANNXP_EXT_P7 */
    NULL,    /* G_AUX_CTL */
    NULL,    /* G_AUX_CTL_EXT */
    NULL,    /* G_AUX_CTL_EXT_P5 */
    NULL,    /* G_AUX_CTL_EXT_P7 */
    NULL,    /* G_AUX_STS */
    NULL,    /* G_AUX_STS_EXT */
    NULL,    /* G_AUX_STS_EXT_P5 */
    NULL,    /* G_AUX_STS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_B1000T_CTLr_ROBO],
    NULL,    /* G_B1000T_CTL_EXT */
    NULL,    /* G_B1000T_CTL_EXT_P5 */
    NULL,    /* G_B1000T_CTL_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_B1000T_STSr_ROBO],
    NULL,    /* G_B1000T_STS_EXT */
    NULL,    /* G_B1000T_STS_EXT_P5 */
    NULL,    /* G_B1000T_STS_EXT_P7 */
    NULL,    /* G_DSP_COEFFICIENT */
    NULL,    /* G_DSP_COEFFICIENT_ADDR */
    NULL,    /* G_DSP_COEFFICIENT_ADDR_EXT */
    NULL,    /* G_DSP_COEFFICIENT_ADDR_EXT_P5 */
    NULL,    /* G_DSP_COEFFICIENT_ADDR_EXT_P7 */
    NULL,    /* G_DSP_COEFFICIENT_EXT */
    NULL,    /* G_DSP_COEFFICIENT_EXT_P5 */
    NULL,    /* G_DSP_COEFFICIENT_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_EXT_STSr_ROBO],
    NULL,    /* G_EXT_STS_EXT */
    NULL,    /* G_EXT_STS_EXT_P5 */
    NULL,    /* G_EXT_STS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_FALSE_CARR_CNTr_ROBO],
    NULL,    /* G_FALSE_CARR_CNT_EXT */
    NULL,    /* G_FALSE_CARR_CNT_EXT_P5 */
    NULL,    /* G_FALSE_CARR_CNT_EXT_P7 */
    NULL,    /* G_INTERRUPT_MSK */
    NULL,    /* G_INTERRUPT_MSK_EXT */
    NULL,    /* G_INTERRUPT_MSK_EXT_P5 */
    NULL,    /* G_INTERRUPT_MSK_EXT_P7 */
    NULL,    /* G_INTERRUPT_STS */
    NULL,    /* G_INTERRUPT_STS_EXT */
    NULL,    /* G_INTERRUPT_STS_EXT_P5 */
    NULL,    /* G_INTERRUPT_STS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_LPNXPr_ROBO],
    NULL,    /* G_LPNXP_EXT */
    NULL,    /* G_LPNXP_EXT_P5 */
    NULL,    /* G_LPNXP_EXT_P7 */
    NULL,    /* G_MASTER_SLAVE_SEED */
    NULL,    /* G_MASTER_SLAVE_SEED_EXT */
    NULL,    /* G_MASTER_SLAVE_SEED_EXT_P5 */
    NULL,    /* G_MASTER_SLAVE_SEED_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_MIICTLr_ROBO],
    NULL,    /* G_MIICTL_EXT */
    NULL,    /* G_MIICTL_EXT_P5 */
    NULL,    /* G_MIICTL_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_MIISTSr_ROBO],
    NULL,    /* G_MIISTS_EXT */
    NULL,    /* G_MIISTS_EXT_P5 */
    NULL,    /* G_MIISTS_EXT_P7 */
    NULL,    /* G_MISC_SHADOW */
    NULL,    /* G_MISC_SHADOW_EXT */
    NULL,    /* G_MISC_SHADOW_EXT_P5 */
    NULL,    /* G_MISC_SHADOW_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_PCTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_PHYIDHr_ROBO],
    NULL,    /* G_PHYIDH_EXT */
    NULL,    /* G_PHYIDH_EXT_P5 */
    NULL,    /* G_PHYIDH_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_PHYIDLr_ROBO],
    NULL,    /* G_PHYIDL_EXT */
    NULL,    /* G_PHYIDL_EXT_P5 */
    NULL,    /* G_PHYIDL_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_PHY_EXT_CTLr_ROBO],
    NULL,    /* G_PHY_EXT_CTL_EXT */
    NULL,    /* G_PHY_EXT_CTL_EXT_P5 */
    NULL,    /* G_PHY_EXT_CTL_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_PHY_EXT_STSr_ROBO],
    NULL,    /* G_PHY_EXT_STS_EXT */
    NULL,    /* G_PHY_EXT_STS_EXT_P5 */
    NULL,    /* G_PHY_EXT_STS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_REC_ERR_CNTr_ROBO],
    NULL,    /* G_REC_ERR_CNT_EXT */
    NULL,    /* G_REC_ERR_CNT_EXT_P5 */
    NULL,    /* G_REC_ERR_CNT_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_REC_NOTOK_CNTr_ROBO],
    NULL,    /* G_REC_NOTOK_CNT_EXT */
    NULL,    /* G_REC_NOTOK_CNT_EXT_P5 */
    NULL,    /* G_REC_NOTOK_CNT_EXT_P7 */
    NULL,    /* G_TEST1 */
    NULL,    /* G_TEST2 */
    NULL,    /* G_TEST1_EXT */
    NULL,    /* G_TEST1_EXT_P5 */
    NULL,    /* G_TEST1_EXT_P7 */
    NULL,    /* G_TEST2_EXT */
    NULL,    /* G_TEST2_EXT_P5 */
    NULL,    /* G_TEST2_EXT_P7 */
    NULL,    /* HL_PRTC_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_HNDRD_ACTL_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_HNDRD_ASTS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_HNDRD_FCSCNT_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_HNDRD_RECNT_BCM5347_A0r_ROBO],
    NULL,    /* IEEE802P2_LLC */
    NULL,    /* IEEE_802_2_LLC */
    &soc_robo_reg_list[SOC_REG_INT_IGMIRCTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_IGMIRDIV_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_IGMIRMAC_BCM5348_A0r_ROBO],
    NULL,    /* IMP0_PRT_ID */
    NULL,    /* IMP1_EGRESS_RATE_CTRL_CFG_REG */
    NULL,    /* IMP1_PRT_ID */
    NULL,    /* IMP_CTL */
    NULL,    /* IMP_EGRESS_RATE_CTRL_CFG_REG */
    NULL,    /* IMP_PCP2TC */
    NULL,    /* IMP_PCTL */
    NULL,    /* IMP_RGMII_CTL_GP */
    NULL,    /* IMP_RGMII_TIME_DLY_GP */
    NULL,    /* IMP_SLEEP_STS */
    NULL,    /* IMP_SLEEP_TIMER */
    NULL,    /* IMP_SOFTWARE_EGRESS_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_INGRESS_RMON_BCM53242_A0r_ROBO],
    NULL,    /* INGRESS_SFLOW */
    NULL,    /* INGRESS_SFLOW_PORT */
    NULL,    /* INRANGEERRCOUNT */
    NULL,    /* INRANGEERRPKTS */
    NULL,    /* INTERNAL_CPU_DEBUG */
    NULL,    /* INTERNAL_CPU_MII_PORT_CONTROL */
    NULL,    /* INTERNAL_CPU_MMR_ADDRESS */
    NULL,    /* INTERNAL_CPU_MMR_DATA */
    NULL,    /* INTERRUPT */
    NULL,    /* INTERRUPT_EXT_P5 */
    NULL,    /* INT_EN */
    NULL,    /* INT_STS */
    NULL,    /* INT_TRIGGER */
    NULL,    /* IN_CPU_CTRL */
    NULL,    /* IPG_SHRNK_CTRL */
    NULL,    /* ISP_PORT_SEL_PBM */
    &soc_robo_reg_list[SOC_REG_INT_ISP_SEL_PORTMAPr_ROBO],
    NULL,    /* ISP_TPID */
    &soc_robo_reg_list[SOC_REG_INT_ISP_VID_BCM53242_A0r_ROBO],
    NULL,    /* IVM_EVM_HIT_ENTRY */
    NULL,    /* JUMBOPKT */
    NULL,    /* JUMBO_PORT_MASK */
    &soc_robo_reg_list[SOC_REG_INT_L4PORT_RANGE_CHECKERr_ROBO],
    NULL,    /* LCPLL_CTRL_H */
    NULL,    /* LCPLL_CTRL_L */
    NULL,    /* LCPLL_STATE_OUTPUT */
    NULL,    /* LDMETER_UPDATE_RATECTL */
    NULL,    /* LD_FRM_SA */
    NULL,    /* LED0_ST */
    NULL,    /* LED1_ST */
    NULL,    /* LED2_ST */
    NULL,    /* LED3_ST */
    NULL,    /* LEDA_CTL */
    NULL,    /* LEDA_ST */
    NULL,    /* LEDB_ST */
    NULL,    /* LEDC_ST */
    NULL,    /* LEDD_ST */
    &soc_robo_reg_list[SOC_REG_INT_LED_CONTROLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_EN_MAP_BCM53242_A0r_ROBO],
    NULL,    /* LED_FLSH_CTL */
    &soc_robo_reg_list[SOC_REG_INT_LED_FUNC0_CTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_FUNC1_CTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_FUNC_MAP_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_MODE_MAP_0_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_MODE_MAP_1_BCM53242_A0r_ROBO],
    NULL,    /* LED_OPTIONS */
    NULL,    /* LED_OUTPUT_ENABLE */
    NULL,    /* LED_PORTMAP */
    NULL,    /* LED_REFLSH_CTL */
    &soc_robo_reg_list[SOC_REG_INT_LNKSTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LNKSTSCHG_BCM53242_A0r_ROBO],
    NULL,    /* LOW_POWER_CTRL */
    NULL,    /* LPDET_CFG */
    NULL,    /* LPDET_SA */
    &soc_robo_reg_list[SOC_REG_INT_LPNXP_BCM5347_A0r_ROBO],
    NULL,    /* LPNXP_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_LP_STA_GP_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LRN_CNT_CTLr_ROBO],
    NULL,    /* LSA_MII_PORT */
    NULL,    /* LSA_PORT */
    &soc_robo_reg_list[SOC_REG_INT_MAC2VLAN_CTLr_ROBO],
    NULL,    /* MAC_FM_DROP_CTL */
    NULL,    /* MAC_SEC_CON0 */
    NULL,    /* MAC_SEC_CON1 */
    NULL,    /* MAC_SEC_CON2 */
    NULL,    /* MAC_SEC_CON3 */
    NULL,    /* MAC_SEC_CON4 */
    NULL,    /* MAC_TRUNK_CTL */
    NULL,    /* MARLA_FWD_ENTRY0 */
    NULL,    /* MARLA_FWD_ENTRY1 */
    NULL,    /* MARLA_SRCH_RSLT */
    NULL,    /* MARLA_SRCH_RSLT_0 */
    NULL,    /* MARLA_SRCH_RSLT_1 */
    NULL,    /* MAX_ICMPV4_SIZE */
    NULL,    /* MAX_ICMPV4_SIZE_REG */
    NULL,    /* MAX_ICMPV6_SIZE */
    NULL,    /* MAX_ICMPV6_SIZE_REG */
    NULL,    /* MCAST_SUP0 */
    NULL,    /* MCAST_SUP1 */
    NULL,    /* MDIO_ADDR_P */
    NULL,    /* MDIO_ADDR_P8 */
    NULL,    /* MDIO_ADDR_WAN */
    &soc_robo_reg_list[SOC_REG_INT_MDIO_BASE_ADDRr_ROBO],
    NULL,    /* MDIO_DIRECT_ACCESS */
    NULL,    /* MDIO_IMP_ADDR */
    NULL,    /* MDIO_PORT7_ADDR */
    NULL,    /* MDIO_WAN_ADDR */
    NULL,    /* MEMORY_TEST_CTRL */
    NULL,    /* MEMORY_TEST_CTRL_1 */
    NULL,    /* MEM_ADDR */
    NULL,    /* MEM_ADDR_0 */
    NULL,    /* MEM_ADDR_1 */
    NULL,    /* MEM_ADDR_2 */
    NULL,    /* MEM_ADDR_3 */
    NULL,    /* MEM_ARL_B0_HI */
    NULL,    /* MEM_ARL_B0_LO */
    NULL,    /* MEM_ARL_B1_HI */
    NULL,    /* MEM_ARL_B1_LO */
    NULL,    /* MEM_ARL_HIGH */
    NULL,    /* MEM_ARL_LOW */
    NULL,    /* MEM_BFC_ADDR */
    NULL,    /* MEM_BFC_DATA */
    NULL,    /* MEM_BTM_DATA */
    NULL,    /* MEM_BTM_DATA0 */
    NULL,    /* MEM_BTM_DATA1 */
    NULL,    /* MEM_CTRL */
    NULL,    /* MEM_DATA_0 */
    NULL,    /* MEM_DATA_1 */
    NULL,    /* MEM_DATA_2 */
    NULL,    /* MEM_DATA_3 */
    NULL,    /* MEM_DATA_4 */
    NULL,    /* MEM_DATA_5 */
    NULL,    /* MEM_DATA_6 */
    NULL,    /* MEM_DATA_7 */
    NULL,    /* MEM_DATA_HIGH */
    NULL,    /* MEM_DATA_LOW */
    NULL,    /* MEM_DEBUG_DATA_0_0 */
    NULL,    /* MEM_DEBUG_DATA_0_1 */
    NULL,    /* MEM_DEBUG_DATA_1_0 */
    NULL,    /* MEM_DEBUG_DATA_1_1 */
    NULL,    /* MEM_FRM_ADDR */
    NULL,    /* MEM_FRM_DATA0 */
    NULL,    /* MEM_FRM_DATA1 */
    NULL,    /* MEM_FRM_DATA2 */
    NULL,    /* MEM_FRM_DATA3 */
    NULL,    /* MEM_FRM_DATA4 */
    NULL,    /* MEM_FRM_DATA5 */
    NULL,    /* MEM_FRM_DATA6 */
    NULL,    /* MEM_FRM_DATA7 */
    NULL,    /* MEM_INDEX */
    NULL,    /* MEM_KEY_0 */
    NULL,    /* MEM_KEY_1 */
    NULL,    /* MEM_KEY_2 */
    NULL,    /* MEM_KEY_3 */
    NULL,    /* MEM_KEY_4 */
    NULL,    /* MEM_KEY_5 */
    NULL,    /* MEM_KEY_6 */
    NULL,    /* MEM_KEY_7 */
    NULL,    /* MEM_MARL_B0_HI */
    NULL,    /* MEM_MARL_B0_LO */
    NULL,    /* MEM_MARL_B1_HI */
    NULL,    /* MEM_MARL_B1_LO */
    NULL,    /* MEM_MARL_HIGH */
    NULL,    /* MEM_MARL_LOW */
    NULL,    /* MEM_SRCH_ADDR_0 */
    NULL,    /* MEM_SRCH_CTRL */
    NULL,    /* MEM_SRCH_DATA_0 */
    NULL,    /* MEM_SRCH_DATA_1 */
    NULL,    /* MEM_SRCH_INDEX */
    NULL,    /* MEM_SRCH_KEY_2 */
    NULL,    /* MEM_TEST_CTL */
    NULL,    /* MEM_TEST_CTRL_0 */
    NULL,    /* MEM_TEST_CTRL_1 */
    NULL,    /* MEM_TEST_CTRL_2 */
    NULL,    /* MEM_TEST_CTRL_3 */
    NULL,    /* MEM_VLAN_DATA */
    NULL,    /* MIBDIAG_PAGE */
    &soc_robo_reg_list[SOC_REG_INT_MIBDIAG_PAGEr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MIBKILLOVR_BCM5348_A0r_ROBO],
    NULL,    /* MIB_GD_FM_MAX_SIZE */
    NULL,    /* MIB_PORT_SEL */
    NULL,    /* MIB_SELECT */
    &soc_robo_reg_list[SOC_REG_INT_MIB_SNAPSHOT_CTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MIICTL_BCM5347_A0r_ROBO],
    NULL,    /* MIICTL_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_MIISTS_BCM5347_A0r_ROBO],
    NULL,    /* MIISTS_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_MII_PCTL_BCM5348_A0r_ROBO],
    NULL,    /* MINIMUM_TCP_HDR_SZ */
    NULL,    /* MIN_TCP_HEADER_SIZE */
    &soc_robo_reg_list[SOC_REG_INT_MIRCAPCTL_BCM53242_A0r_ROBO],
    NULL,    /* MIRRORCTL */
    NULL,    /* MISC_CTL */
    &soc_robo_reg_list[SOC_REG_INT_MLF_DROP_MAP_BCM53242_A0r_ROBO],
    NULL,    /* MLF_IMPC_FWD_MAP */
    &soc_robo_reg_list[SOC_REG_INT_MLF_IPMC_FWD_MAP_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MNGPID_BCM5348_A0r_ROBO],
    NULL,    /* MODEL_ID */
    NULL,    /* MODULE_ID0 */
    NULL,    /* MODULE_ID1 */
    NULL,    /* MONITOR_TOTAL_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ0_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ1_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ2_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ3_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ4_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ5_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ6_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ7_BUF_USED_COUNT */
    NULL,    /* MONITOR_TX_PORT_CTRL */
    NULL,    /* MPORTVEC0 */
    NULL,    /* MPORTVEC1 */
    NULL,    /* MPORTVEC2 */
    NULL,    /* MPORTVEC3 */
    NULL,    /* MPORTVEC4 */
    NULL,    /* MPORTVEC5 */
    &soc_robo_reg_list[SOC_REG_INT_MR_STAr_ROBO],
    NULL,    /* MST_AGE */
    &soc_robo_reg_list[SOC_REG_INT_MST_CON_BCM53242_A0r_ROBO],
    NULL,    /* MST_TAB */
    NULL,    /* MST_TBL */
    NULL,    /* MULTIPORT_ADDR0 */
    NULL,    /* MULTIPORT_ADDR1 */
    NULL,    /* MULTIPORT_ADDR2 */
    NULL,    /* MULTIPORT_ADDR3 */
    NULL,    /* MULTIPORT_ADDR4 */
    NULL,    /* MULTIPORT_ADDR5 */
    NULL,    /* MULTI_PORT_CTL */
    &soc_robo_reg_list[SOC_REG_INT_NEW_CONTROL_BCM53242_A0r_ROBO],
    NULL,    /* NEW_CTRL */
    NULL,    /* NEW_PRI_MAP */
    &soc_robo_reg_list[SOC_REG_INT_OTHER_CHECKERr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_OTHER_TABLE_DATA0_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_OTHER_TABLE_DATA1_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_OTHER_TABLE_DATA2_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_OTHER_TABLE_INDEX_BCM53242_A0r_ROBO],
    NULL,    /* OTPROM_STATUS */
    NULL,    /* OTP_ADDR_REG */
    NULL,    /* OTP_CTL_REG */
    NULL,    /* OTP_RD_DATA */
    NULL,    /* OTP_STS_REG */
    NULL,    /* OTP_WR_DATA */
    NULL,    /* OUTOFRANGEERRPKTS */
    NULL,    /* OUTRANGEERRCOUNT */
    NULL,    /* P5_RGMII_TIME_DLY_GP */
    NULL,    /* P8_PCP2TC */
    NULL,    /* PAGEREG */
    &soc_robo_reg_list[SOC_REG_INT_PAUSESTS_BCM53242_A0r_ROBO],
    NULL,    /* PAUSE_CAP */
    NULL,    /* PAUSE_FM_SA */
    NULL,    /* PAUSE_FRM_CTRL */
    NULL,    /* PAUSE_QUANTA */
    NULL,    /* PBPTRFIFO */
    NULL,    /* PBPTRFIFO_0 */
    NULL,    /* PBPTRFIFO_1 */
    NULL,    /* PCP_VALUE_CTRL */
    NULL,    /* PEAK_TEMP_MON_RESU */
    NULL,    /* PEAK_TOTAL_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ0_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ1_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ2_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ3_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ4_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ5_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ6_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ7_BUF_USED_COUNT */
    &soc_robo_reg_list[SOC_REG_INT_PHYIDH_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PHYIDL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PHYINFO_PHYIDH_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PHYINFO_PHYIDL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PHYSCAN_CTL_BCM5348_A0r_ROBO],
    NULL,    /* PHY_CTRL */
    NULL,    /* PHY_INT_STS */
    NULL,    /* PHY_LED_FUNC */
    NULL,    /* PHY_PWR_DOWN */
    NULL,    /* PHY_STAT */
    NULL,    /* PHY_STS */
    NULL,    /* PKTS1024TO1522OCTETS */
    &soc_robo_reg_list[SOC_REG_INT_RXMULTICASTPKTS_BCM5347_A0r_ROBO],
    NULL,    /* PKTS1024TOMAXPKTOCTETS */
    &soc_robo_reg_list[SOC_REG_INT_PKTS128TO255OCTETS_BCM53242_A0r_ROBO],
    NULL,    /* PKTS1523TO2047 */
    NULL,    /* PKTS2048TO4095 */
    &soc_robo_reg_list[SOC_REG_INT_PKTS256TO511OCTETS_BCM53242_A0r_ROBO],
    NULL,    /* PKTS4096TO8191 */
    &soc_robo_reg_list[SOC_REG_INT_RXUNICASTPKTS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PKTS64OCTETS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PKTS65TO127OCTETS_BCM53242_A0r_ROBO],
    NULL,    /* PKTS8192TO9728 */
    NULL,    /* PKT_MARK_CTL */
    NULL,    /* PLL_CTRL */
    NULL,    /* PLL_CTRL_0 */
    NULL,    /* PLL_CTRL_1 */
    NULL,    /* PLL_CTRL_2 */
    NULL,    /* PLL_FREQ_SEL */
    NULL,    /* PLL_STS */
    NULL,    /* PLL_TEST */
    NULL,    /* PLL_TEST_CTRL_I */
    NULL,    /* PLL_TEST_CTRL_II */
    NULL,    /* PN_PCP2TC */
    NULL,    /* PORT4_RGMII_CTL_GP */
    NULL,    /* PORT5_RGMII_CTL_GP */
    NULL,    /* PORT7_RGMII_CTL_GP */
    NULL,    /* PORT7_RGMII_TIME_DLY_GP */
    &soc_robo_reg_list[SOC_REG_INT_PORTVEC1_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PORTVEC2_BCM53242_A0r_ROBO],
    NULL,    /* PORT_CROSS_CONNECT */
    NULL,    /* PORT_EAP1_CON */
    NULL,    /* PORT_EAP_CON */
    &soc_robo_reg_list[SOC_REG_INT_PORT_EAP_DAr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PORT_EGCTLr_ROBO],
    NULL,    /* PORT_ERC_CON */
    NULL,    /* PORT_ERC_CON_IMP */
    NULL,    /* PORT_IRC1_CON */
    NULL,    /* PORT_IRC_CON */
    &soc_robo_reg_list[SOC_REG_INT_PORT_MAX_LEARN_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PORT_SA_CNT_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PORT_SEC_CONr_ROBO],
    NULL,    /* PORT_VLAN1_CTL */
    NULL,    /* PORT_VLAN_CTL */
    NULL,    /* PORT_VLAN_CTL_IMP */
    NULL,    /* PORT_XOFF_STS */
    NULL,    /* POST_LED_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_PRBS_CTLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PRBS_STA_BCM53242_A0r_ROBO],
    NULL,    /* PRESERVE_PKT_FORMAT */
    NULL,    /* PROFILE_CTL */
    &soc_robo_reg_list[SOC_REG_INT_PROTECTED_SEL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PROTOCOL2VLAN_CTLr_ROBO],
    NULL,    /* PRS_FIFO_DEBUG_CTRL */
    NULL,    /* PRS_FIFO_DEBUG_DATA */
    NULL,    /* PTEST */
    &soc_robo_reg_list[SOC_REG_INT_PWR_DOWN_MODE_BCM5348_A0r_ROBO],
    NULL,    /* QOS_1P1Q_PRI_MAP */
    &soc_robo_reg_list[SOC_REG_INT_QOS_1P_EN_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_CTL_BCM53242_A0r_ROBO],
    NULL,    /* QOS_DIFF_DSCP0 */
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP1_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP2_BCM5348_A0r_ROBO],
    NULL,    /* QOS_DIFF_DSCP3 */
    NULL,    /* QOS_D_TOS_TH */
    NULL,    /* QOS_EN_DIFFSERV */
    NULL,    /* QOS_EN_TRAFFIC_PRI_REMAP */
    NULL,    /* QOS_ETHERPRI_CTRL */
    NULL,    /* QOS_GLOBAL_CTRL */
    NULL,    /* QOS_MIB_QUE_SEL */
    NULL,    /* QOS_M_TOS_TH */
    &soc_robo_reg_list[SOC_REG_INT_QOS_PAUSE_EN_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_REASON_CODEr_ROBO],
    NULL,    /* QOS_RX_CTRL_P */
    NULL,    /* QOS_R_TOS_TH */
    &soc_robo_reg_list[SOC_REG_INT_QOS_TCI_TH_BCM5348_A0r_ROBO],
    NULL,    /* QOS_TOS_DIF_CTL */
    &soc_robo_reg_list[SOC_REG_INT_QOS_TOS_DIF_EN_BCM53242_A0r_ROBO],
    NULL,    /* QOS_TRAFFIC_PRI_REMAP */
    NULL,    /* QOS_TX_CTRL */
    NULL,    /* QOS_T_TOS_TH */
    NULL,    /* QOS_WEIGHT */
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FCON_FLOWCON_STATUS6r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QUEUE_CONGESTION_STATUS3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QUEUE_CONGESTION_STATUS4_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QUEUE_CONGESTION_STATUS5_BCM53242_A0r_ROBO],
    NULL,    /* QUEUE_REGION_STATUS */
    NULL,    /* RANGE_CHECKER */
    &soc_robo_reg_list[SOC_REG_INT_RANGE_CHECKER_CTLr_ROBO],
    NULL,    /* RANGE_CHECKER_FIELD_SEL */
    &soc_robo_reg_list[SOC_REG_INT_RATE_INBAND_BCM53242_A0r_ROBO],
    NULL,    /* RATE_METER0 */
    NULL,    /* RATE_METER1 */
    &soc_robo_reg_list[SOC_REG_INT_RATE_OUTBAND_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RCM_CTLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RCM_DATA0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RCM_DATA1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RCM_DATA2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RCM_DATA3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RCM_DATA4r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RCM_PORTr_ROBO],
    NULL,    /* REGULATOR_CTRL */
    NULL,    /* REGULATOR_UNLOCK */
    NULL,    /* REGULATOR_VOLT_SEL */
    NULL,    /* RESE_AV_EN_CTRL */
    NULL,    /* RESE_C4_BW_CNTL */
    NULL,    /* RESE_C5_BW_CNTL */
    NULL,    /* RESE_EGRESS_TM_STAMP */
    NULL,    /* RESE_MAX_AV_PKT_SZ */
    NULL,    /* RESE_SLOT_ADJ */
    NULL,    /* RESE_SLOT_TICK_CNTR */
    NULL,    /* RESE_TM_ADJ */
    NULL,    /* RESE_TM_BASE */
    NULL,    /* RGMII_CTL_GP */
    NULL,    /* RGMII_CTL_GP48 */
    &soc_robo_reg_list[SOC_REG_INT_RGMII_CTL_GP49r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RGMII_CTL_GP50r_ROBO],
    NULL,    /* RGMII_CTRL */
    NULL,    /* RGMII_CTRL_GP25 */
    NULL,    /* RGMII_CTRL_GP26 */
    NULL,    /* RGMII_CTRL_IMP */
    NULL,    /* RGMII_TIME_DELAY_CTRL */
    NULL,    /* RGMII_TIME_DLY_CTRL_GP25 */
    NULL,    /* RGMII_TIME_DLY_CTRL_GP26 */
    NULL,    /* RGMII_TIME_DLY_CTRL_IMP */
    NULL,    /* RGMII_TIME_DLY_GP */
    NULL,    /* RGMII_TIME_DLY_GP48 */
    &soc_robo_reg_list[SOC_REG_INT_RGMII_TIME_DLY_GP49r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RGMII_TIME_DLY_GP50r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RMONSTEER_BCM53242_A0r_ROBO],
    NULL,    /* RM_PINS_DEBUG */
    &soc_robo_reg_list[SOC_REG_INT_RST_TABLE_MEMr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RST_TABLE_MEM1r_ROBO],
    NULL,    /* RSV_MCAST_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_RXALIGNMENTERRORS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXBROADCASTPKT_BCM53242_A0r_ROBO],
    NULL,    /* RXBROADCASTPKTS */
    NULL,    /* RXDISCARD */
    &soc_robo_reg_list[SOC_REG_INT_RXDROPPKTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXEXCESSSIZEDISC_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXEXCESSSIZEDISC_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXFRAGMENTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXFWDDISCPKTSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXGOODOCTETS_BCM53242_A0r_ROBO],
    NULL,    /* RXGOODPKTS */
    NULL,    /* RXJABBERPKTS */
    &soc_robo_reg_list[SOC_REG_INT_RXSACHANGES_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXMULTICASTPKTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXOCTETS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXOVERSIZEPKTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXPAUSEPKTS_BCM53242_A0r_ROBO],
    NULL,    /* RXPAUSESTS */
    NULL,    /* RXPKTS1024TOMAXPKT */
    NULL,    /* RXPKTS128TO255OCTETS */
    NULL,    /* RXPKTS256TO511OCTETS */
    NULL,    /* RXPKTS512TO1023OCTETS */
    NULL,    /* RXPKTS64OCTETS */
    NULL,    /* RXPKTS65TO127OCTETS */
    NULL,    /* RXQOSOCTETS */
    NULL,    /* RXQOSPKTS */
    &soc_robo_reg_list[SOC_REG_INT_RXSACHANGES_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXSYMBLERR_BCM53242_A0r_ROBO],
    NULL,    /* RXSYMBOLERR */
    &soc_robo_reg_list[SOC_REG_INT_RXUNDERSIZEPKTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXUNICASTPKTS_BCM53242_A0r_ROBO],
    NULL,    /* RX_GLOBAL_CTL */
    NULL,    /* RX_JUMBO_PACKET_COUNTER */
    &soc_robo_reg_list[SOC_REG_INT_RX_PAUSE_PASS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SCAN_RSLT_GP_BCM53242_A0r_ROBO],
    NULL,    /* SCAN_RSLT_IMP */
    NULL,    /* SCAN_RSLT_P */
    &soc_robo_reg_list[SOC_REG_INT_SCAN_TIMEOUTr_ROBO],
    NULL,    /* SDACTLSTS */
    NULL,    /* SDAEGSTS */
    NULL,    /* SDAMODE2 */
    NULL,    /* SDAMPHY */
    NULL,    /* SDANADV */
    NULL,    /* SDANEXP */
    NULL,    /* SDANLPA */
    NULL,    /* SDANNXP */
    NULL,    /* SDASTSSUM */
    NULL,    /* SDBRCMTST */
    NULL,    /* SDHNDRD_ACTL */
    NULL,    /* SDHNDRD_ASTS */
    NULL,    /* SDHNDRD_FCSCNT */
    NULL,    /* SDHNDRD_RECNT */
    NULL,    /* SDLPNXP */
    NULL,    /* SDMIICTL */
    NULL,    /* SDMIISTS */
    NULL,    /* SDPHYIDH */
    NULL,    /* SDPHYIDL */
    NULL,    /* SD_DEFAULT */
    NULL,    /* SD_SEL_EARLY */
    NULL,    /* SD_SIGNAL_DETC */
    NULL,    /* SECURITY_BYPASS_CTL */
    NULL,    /* SECURITY_GLOBAL_CTL */
    NULL,    /* SEC_DPMSK */
    NULL,    /* SEC_SPMSK */
    &soc_robo_reg_list[SOC_REG_INT_SEC_TDIP0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SEC_TDIP1r_ROBO],
    NULL,    /* SERDES_CTRL */
    NULL,    /* SFT_LRN_CTL */
    &soc_robo_reg_list[SOC_REG_INT_SGMII_CLR_CTL_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SGMII_CTL_GP_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SGMII_STA_GP_BCM53242_A0r_ROBO],
    NULL,    /* SIP_REG */
    NULL,    /* SLICE_MAP_P */
    NULL,    /* SLICE_MAP_P8 */
    NULL,    /* SPARE_REG0 */
    NULL,    /* SPARE_REG1 */
    NULL,    /* SPARE_REG2 */
    &soc_robo_reg_list[SOC_REG_INT_SPDSTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPECIAL_MNGT_BCM53242_A0r_ROBO],
    NULL,    /* SPICTL */
    NULL,    /* SPIDIO0 */
    NULL,    /* SPIDIO1 */
    NULL,    /* SPIDIO2 */
    NULL,    /* SPIDIO3 */
    NULL,    /* SPIDIO4 */
    NULL,    /* SPIDIO5 */
    NULL,    /* SPIDIO6 */
    NULL,    /* SPIDIO7 */
    NULL,    /* SPISTS */
    &soc_robo_reg_list[SOC_REG_INT_SPTAGT_BCM5348_A0r_ROBO],
    NULL,    /* SPT_MULTI_ADDR_BPS_CTRL */
    NULL,    /* SRCADRCHG */
    NULL,    /* STP_BYPASS_CTL */
    NULL,    /* STRAP_PIN_STATUS */
    &soc_robo_reg_list[SOC_REG_INT_STRAP_STS_BCM53242_A0r_ROBO],
    NULL,    /* STRAP_VALUE */
    &soc_robo_reg_list[SOC_REG_INT_STS_CTLr_ROBO],
    NULL,    /* STS_OVERRIDE_GMIIP */
    &soc_robo_reg_list[SOC_REG_INT_STS_OVERRIDE_GP_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_STS_OVERRIDE_IMP_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_STS_OVERRIDE_P_BCM53242_A0r_ROBO],
    NULL,    /* STS_OVERRIDE_P24 */
    NULL,    /* STS_OVERRIDE_WAN_P */
    NULL,    /* SWITCH_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_SWMODE_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SW_FLOW_CON_BCM53242_A0r_ROBO],
    NULL,    /* SW_XOFF_PORT_CTL */
    NULL,    /* S_ANADV */
    NULL,    /* S_ANEXP */
    NULL,    /* S_ANLPA1 */
    NULL,    /* S_ANLPA2 */
    NULL,    /* S_ANNXP */
    NULL,    /* S_EEE_LPI_DURATION */
    NULL,    /* S_EEE_LPI_EVENT */
    NULL,    /* S_EXT_STS */
    NULL,    /* S_INRANGEERRCOUNT */
    NULL,    /* S_INRANGEERRPKTS */
    NULL,    /* S_JUMBOPKT */
    NULL,    /* S_MIICTL */
    NULL,    /* S_MIISTS */
    NULL,    /* S_OUTOFRANGEERRPKTS */
    NULL,    /* S_OUTRANGEERRCOUNT */
    NULL,    /* S_PHYIDH */
    NULL,    /* S_PHYIDL */
    NULL,    /* S_PKTS1024TO1522OCTETS */
    &soc_robo_reg_list[SOC_REG_INT_S_RXMULTICASTPKTS_BCM5348_A0r_ROBO],
    NULL,    /* S_PKTS1024TOMAXPKTOCTETS */
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS128TO255OCTETS_BCM53242_A0r_ROBO],
    NULL,    /* S_PKTS1523TO2047 */
    NULL,    /* S_PKTS2048TO4095 */
    &soc_robo_reg_list[SOC_REG_INT_S_RXDROPPKTS_BCM5348_A0r_ROBO],
    NULL,    /* S_PKTS4096TO8191 */
    &soc_robo_reg_list[SOC_REG_INT_S_RXUNICASTPKTS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXFCSERRORS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS65TO127OCTETS_BCM53242_A0r_ROBO],
    NULL,    /* S_PKTS8192TO9728 */
    &soc_robo_reg_list[SOC_REG_INT_S_RXFRAGMENTS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXBROADCASTPKT_BCM53242_A0r_ROBO],
    NULL,    /* S_RXBROADCASTPKTS */
    NULL,    /* S_RXDISCARD */
    &soc_robo_reg_list[SOC_REG_INT_S_RXDROPPKTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXEXCESSSIZEDISC_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXEXCESSSIZEDISC_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXFRAGMENTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXFWDDISCPKTSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXGOODOCTETS_BCM53242_A0r_ROBO],
    NULL,    /* S_RXJABBERPKTS */
    &soc_robo_reg_list[SOC_REG_INT_S_RXSACHANGES_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXMULTICASTPKTS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXOCTETS_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXBROADCASTPKT_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXALIGNMENTERRORS_BCM5348_A0r_ROBO],
    NULL,    /* S_RXPKTS1024TOMAXPKT */
    NULL,    /* S_RXPKTS128TO255OCTETS */
    NULL,    /* S_RXPKTS256TO511OCTETS */
    NULL,    /* S_RXPKTS512TO1023OCTETS */
    NULL,    /* S_RXPKTS64OCTETS */
    NULL,    /* S_RXPKTS65TO127OCTETS */
    NULL,    /* S_RXQOSOCTETS */
    NULL,    /* S_RXQOSPKTS */
    &soc_robo_reg_list[SOC_REG_INT_S_RXSACHANGES_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXSYMBLERR_BCM53242_A0r_ROBO],
    NULL,    /* S_RXSYMBOLERR */
    &soc_robo_reg_list[SOC_REG_INT_S_RXJABBERS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXUNICASTPKTS_BCM53242_A0r_ROBO],
    NULL,    /* S_RX_JUMBO_PACKET_COUNTER */
    &soc_robo_reg_list[SOC_REG_INT_S_TXBROADCASTPKTS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXCOLLISIONS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXDEFERREDTRANSMIT_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXDROPPKTS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXEXCESSIVECOLLISION_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXFRAMEINDISC_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXLATECOLLISION_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXMULTICASTPKTS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXMULTIPLECOLLISION_BCM5348_A0r_ROBO],
    NULL,    /* S_TXMULTIPLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_S_TXOCTETS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQOSPKTS_BCM5348_A0r_ROBO],
    NULL,    /* S_TXPKTS1024TOMAXPKT */
    NULL,    /* S_TXPKTS128TO255OCTETS */
    NULL,    /* S_TXPKTS256TO511OCTETS */
    NULL,    /* S_TXPKTS512TO1023OCTETS */
    NULL,    /* S_TXPKTS64OCTETS */
    NULL,    /* S_TXPKTS65TO127OCTETS */
    NULL,    /* S_TXPORTCONGESTIONDROP */
    &soc_robo_reg_list[SOC_REG_INT_S_TXQOSOCTETS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXPAUSEPKTS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQOS1OCTETSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQOS1PKTSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQOS2OCTETSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXPAUSEPKTS_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQOS3OCTETSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS128TO255OCTETS_BCM5348_A0r_ROBO],
    NULL,    /* S_TXQOSOCTETS */
    NULL,    /* S_TXQOSPKTS */
    NULL,    /* S_TXQPKTQ0 */
    NULL,    /* S_TXQPKTQ1 */
    NULL,    /* S_TXQPKTQ2 */
    NULL,    /* S_TXQPKTQ3 */
    NULL,    /* S_TXQPKTQ4 */
    NULL,    /* S_TXQPKTQ5 */
    NULL,    /* S_TXQQ0OCTETS */
    NULL,    /* S_TXQQ0PACKET */
    NULL,    /* S_TXQQ1OCTETS */
    NULL,    /* S_TXQQ1PACKET */
    NULL,    /* S_TXQQ2OCTETS */
    NULL,    /* S_TXQQ2PACKET */
    NULL,    /* S_TXQQ3OCTETS */
    NULL,    /* S_TXQQ3PACKET */
    NULL,    /* S_TXQQ4OCTETS */
    NULL,    /* S_TXQQ4PACKET */
    NULL,    /* S_TXQQ5OCTETS */
    NULL,    /* S_TXQQ5PACKET */
    NULL,    /* S_TXQQ6OCTETS */
    NULL,    /* S_TXQQ6PACKET */
    NULL,    /* S_TXQQ7OCTETS */
    NULL,    /* S_TXQQ7PACKET */
    NULL,    /* S_TXQQSEL0CONGESTIONDROP */
    NULL,    /* S_TXQQSEL1CONGESTIONDROP */
    &soc_robo_reg_list[SOC_REG_INT_S_TXSINGLECOLLISION_BCM5348_A0r_ROBO],
    NULL,    /* S_TXSINGLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_S_TXUNICASTPKTS_BCM5348_A0r_ROBO],
    NULL,    /* S_TX_JUMBO_PACKET_COUNTER */
    &soc_robo_reg_list[SOC_REG_INT_TBI_CTL_BCM53242_A0r_ROBO],
    NULL,    /* TC2COS_MAP */
    NULL,    /* TCAM_BIST_CONTROL */
    NULL,    /* TCAM_BIST_CTL */
    NULL,    /* TCAM_BIST_STATUS */
    NULL,    /* TCAM_BIST_STS0 */
    NULL,    /* TCAM_BIST_STS1 */
    NULL,    /* TCAM_CHKSUM_STS */
    NULL,    /* TCAM_CTL */
    NULL,    /* TCAM_CTRL */
    NULL,    /* TCAM_TEST_COMPARE_STATUS */
    NULL,    /* TCP_UDP_ACTION_REG */
    NULL,    /* TCP_UDP_HIT_REG */
    NULL,    /* TCP_UDP_KEY_REG */
    NULL,    /* TCP_UDP_WILDCARD_ACTION_REG */
    NULL,    /* TC_DP2DSCP_MAP0 */
    NULL,    /* TC_DP2DSCP_MAP1 */
    NULL,    /* TC_DP2DSCP_MAP2 */
    NULL,    /* TC_DP2DSCP_MAP3 */
    NULL,    /* TC_DP2DSCP_MAP4 */
    NULL,    /* TC_DP2DSCP_MAP5 */
    NULL,    /* TC_DP2DSCP_MAP6 */
    NULL,    /* TC_DP2DSCP_MAP7 */
    NULL,    /* TC_GROUP_CTRL */
    NULL,    /* TEMP_MON_CAL */
    NULL,    /* TEMP_MON_CTL */
    NULL,    /* TEMP_MON_RESU */
    NULL,    /* TEMP_MON_SPEC_CTL */
    &soc_robo_reg_list[SOC_REG_INT_TH_PCTL_BCM5347_A0r_ROBO],
    NULL,    /* TM_STAMP_RPT_CTRL */
    NULL,    /* TM_STAMP_STATUS */
    NULL,    /* TOTAL_CONGESTION_ON_THRESHOLD */
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_DLF_DROP_THRESH_Q1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_DLF_DROP_THRESH_Q2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_DLF_DROP_THRESH_Q3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_DROP_THRESH_Q1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_DROP_THRESH_Q2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_DROP_THRESH_Q3r_ROBO],
    NULL,    /* TOTAL_HYST_COUNT */
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_HYST_THRESH_Q1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_HYST_THRESH_Q2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_HYST_THRESH_Q3r_ROBO],
    NULL,    /* TOTAL_LIMIT_THRESHOLD */
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_MC_DROP_IMP_THRESHr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TOTAL_PAUSE_IMP_THRESHr_ROBO],
    NULL,    /* TOTAL_PROTECTION_ON_THRESHOLD */
    NULL,    /* TOTAL_REGION_STATUS */
    NULL,    /* TRREG_CTRL */
    NULL,    /* TRUNK_GRP0_CTL */
    NULL,    /* TRUNK_GRP1_CTL */
    NULL,    /* TRUNK_GRP2_CTL */
    NULL,    /* TRUNK_GRP3_CTL */
    NULL,    /* TRUNK_GRP_00_CTL */
    NULL,    /* TRUNK_GRP_01_CTL */
    NULL,    /* TRUNK_GRP_02_CTL */
    NULL,    /* TRUNK_GRP_03_CTL */
    NULL,    /* TRUNK_GRP_04_CTL */
    NULL,    /* TRUNK_GRP_05_CTL */
    NULL,    /* TRUNK_GRP_06_CTL */
    NULL,    /* TRUNK_GRP_07_CTL */
    NULL,    /* TRUNK_GRP_08_CTL */
    NULL,    /* TRUNK_GRP_09_CTL */
    NULL,    /* TRUNK_GRP_10_CTL */
    NULL,    /* TRUNK_GRP_11_CTL */
    NULL,    /* TRUNK_GRP_12_CTL */
    NULL,    /* TRUNK_GRP_13_CTL */
    &soc_robo_reg_list[SOC_REG_INT_TRUNK_GRP_CTL_BCM53242_A0r_ROBO],
    NULL,    /* TRUST_C1P_CTL */
    NULL,    /* TRUST_CVID */
    &soc_robo_reg_list[SOC_REG_INT_TRUST_CVLANr_ROBO],
    NULL,    /* TRUST_DSCP_CTL */
    NULL,    /* TRUST_S1P_CTL */
    &soc_robo_reg_list[SOC_REG_INT_TXBROADCASTPKTS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXCOLLISIONS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXDEFERREDTRANSMIT_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXDROPPKTS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXEXCESSIVECOLLISION_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXFRAMEINDISC_BCM5347_A0r_ROBO],
    NULL,    /* TXGOODPKTS */
    &soc_robo_reg_list[SOC_REG_INT_TXLATECOLLISION_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXMULTICASTPKTS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXMULTIPLECOLLISION_BCM5347_A0r_ROBO],
    NULL,    /* TXMULTIPLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_TXOCTETS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQOSPKTS_BCM5347_A0r_ROBO],
    NULL,    /* TXPAUSESTS */
    NULL,    /* TXPKTS1024TOMAXPKT */
    NULL,    /* TXPKTS128TO255OCTETS */
    NULL,    /* TXPKTS256TO511OCTETS */
    NULL,    /* TXPKTS512TO1023OCTETS */
    NULL,    /* TXPKTS64OCTETS */
    NULL,    /* TXPKTS65TO127OCTETS */
    NULL,    /* TXPORTCONGESTIONDROP */
    &soc_robo_reg_list[SOC_REG_INT_TXQOSOCTETS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXPAUSEPKTS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQOS1OCTETSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQOS1PKTSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQOS2OCTETSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXPAUSEPKTS_BCM5347_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQOS3OCTETSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PKTS128TO255OCTETS_BCM5347_A0r_ROBO],
    NULL,    /* TXQOSOCTETS */
    NULL,    /* TXQOSPKTS */
    NULL,    /* TXQPKTQ0 */
    NULL,    /* TXQPKTQ1 */
    NULL,    /* TXQPKTQ2 */
    NULL,    /* TXQPKTQ3 */
    NULL,    /* TXQPKTQ4 */
    NULL,    /* TXQPKTQ5 */
    NULL,    /* TXQQ0OCTETS */
    NULL,    /* TXQQ0PACKET */
    NULL,    /* TXQQ1OCTETS */
    NULL,    /* TXQQ1PACKET */
    NULL,    /* TXQQ2OCTETS */
    NULL,    /* TXQQ2PACKET */
    NULL,    /* TXQQ3OCTETS */
    NULL,    /* TXQQ3PACKET */
    NULL,    /* TXQQ4OCTETS */
    NULL,    /* TXQQ4PACKET */
    NULL,    /* TXQQ5OCTETS */
    NULL,    /* TXQQ5PACKET */
    NULL,    /* TXQQ6OCTETS */
    NULL,    /* TXQQ6PACKET */
    NULL,    /* TXQQ7OCTETS */
    NULL,    /* TXQQ7PACKET */
    NULL,    /* TXQQSEL0CONGESTIONDROP */
    NULL,    /* TXQQSEL1CONGESTIONDROP */
    NULL,    /* TXQ_BACKPRESSURE_GE0_CTL */
    NULL,    /* TXQ_BACKPRESSURE_GE1_CTL */
    NULL,    /* TXQ_BACKPRESSURE_GE2_CTL */
    NULL,    /* TXQ_BACKPRESSURE_GE3_CTL */
    NULL,    /* TXQ_BACKPRESSURE_IMP_CTL */
    NULL,    /* TXQ_DROP_CNT_COS_SELECT_0 */
    NULL,    /* TXQ_DROP_CNT_COS_SELECT_1 */
    NULL,    /* TXQ_FLUSH_MODE */
    NULL,    /* TXQ_HYST_A_COUNT */
    NULL,    /* TXQ_HYST_B_COUNT */
    NULL,    /* TXQ_Q0_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q0_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q0_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q1_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q1_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q1_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q2_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q2_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q2_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q3_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q3_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q3_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q4_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q4_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q4_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q5_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q5_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q5_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q6_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q6_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q6_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q7_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q7_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q7_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_WEIGHT_QUOTA_SZ */
    &soc_robo_reg_list[SOC_REG_INT_TXSINGLECOLLISION_BCM5347_A0r_ROBO],
    NULL,    /* TXSINGLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_TXUNICASTPKTS_BCM5347_A0r_ROBO],
    NULL,    /* TX_EQZ_COEF */
    NULL,    /* TX_JUMBO_PACKET_COUNTER */
    &soc_robo_reg_list[SOC_REG_INT_TX_PAUSE_PASS_BCM53242_A0r_ROBO],
    NULL,    /* UDF_0_A_0_8 */
    NULL,    /* UDF_0_B_0_8 */
    NULL,    /* UDF_0_C_0_8 */
    NULL,    /* UDF_0_D_0_11 */
    NULL,    /* UDF_1_A_0_8 */
    NULL,    /* UDF_1_B_0_8 */
    NULL,    /* UDF_1_C_0_8 */
    NULL,    /* UDF_2_A_0_8 */
    NULL,    /* UDF_2_B_0_8 */
    NULL,    /* UDF_2_C_0_8 */
    NULL,    /* UDF_OFFSET0_P */
    NULL,    /* UDF_OFFSET0_P8 */
    NULL,    /* UDF_OFFSET2_P */
    NULL,    /* UDF_OFFSET3_P */
    NULL,    /* UDF_OFFSET4_EXP */
    NULL,    /* UDF_OFFSET4_GP */
    NULL,    /* UDF_OFFSET4_IMP */
    NULL,    /* UDF_OFFSET4_P */
    NULL,    /* UDF_OFFSET4_P8 */
    NULL,    /* UDF_OFFSET5_P */
    NULL,    /* UDF_OFFSET5_P8 */
    &soc_robo_reg_list[SOC_REG_INT_ULF_DROP_MAP_BCM53242_A0r_ROBO],
    NULL,    /* ULF_FORWARD_MAP */
    &soc_robo_reg_list[SOC_REG_INT_VID_RANGE_CHECKERr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN2VLAN_CTLr_ROBO],
    NULL,    /* VLAN_BYPASS_CTL */
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL1_BCM5348_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL2_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL3_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL4_BCM53242_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL5_BCM53242_A0r_ROBO],
    NULL,    /* VLAN_CTRL6 */
    NULL,    /* VLAN_GLOBAL_CTL */
    NULL,    /* VLAN_MAC_ADDR_INDX */
    NULL,    /* VLAN_MAC_CTRL */
    NULL,    /* VLAN_MAC_HASHSEL */
    NULL,    /* VLAN_MAC_TBL_ACS */
    NULL,    /* VLAN_MAC_TBL_DATA */
    NULL,    /* VLAN_MULTI_PORT_ADDR_CTL */
    &soc_robo_reg_list[SOC_REG_INT_VLAN_REMAP_BCM53242_A0r_ROBO],
    NULL,    /* VREG_UNLOCK */
    NULL,    /* WAN_PORT_SEL */
    NULL,    /* WAN_SLEEP_TIMER */
    NULL,    /* WATCH_DOG_CTRL */
    NULL,    /* WATCH_DOG_RPT1 */
    NULL,    /* WATCH_DOG_RPT2 */
    NULL,    /* WATCH_DOG_RPT3 */
    NULL,    /* X1K_ANADV */
    NULL,    /* X1K_ANEXP */
    NULL,    /* X1K_ANLPA */
    NULL,    /* X1K_ANNXP */
    NULL,    /* X1K_BER_CRC_RXCNT */
    NULL,    /* X1K_BRCMTST */
    NULL,    /* X1K_CTL1 */
    NULL,    /* X1K_CTL2 */
    NULL,    /* X1K_CTL3 */
    NULL,    /* X1K_CTL4 */
    NULL,    /* X1K_EXT_MIISTS */
    NULL,    /* X1K_FORCE_TXD1 */
    NULL,    /* X1K_FORCE_TXD2 */
    NULL,    /* X1K_LPNXP */
    NULL,    /* X1K_MIICTL */
    NULL,    /* X1K_MIISTS */
    NULL,    /* X1K_PATT_GEN_CTL */
    NULL,    /* X1K_PATT_GEN_STS */
    NULL,    /* X1K_PHYIDH */
    NULL,    /* X1K_PHYIDL */
    NULL,    /* X1K_PRBS_CTL */
    NULL,    /* X1K_PRBS_STS */
    NULL,    /* X1K_STS1 */
    NULL,    /* X1K_STS2 */
    NULL,    /* X1K_STS3 */
    NULL,    /* X1K_TST_MOD */
    NULL,    /* XOFF_PORT_HISTORY */
    NULL     /* XOFF_TRIG_PORT_CTRL */
};

static soc_mem_info_t *soc_memories_bcm53242_a0[] = {
    &soc_robo_mem_list[SOC_MEM_INT_CFP_ACT_POL_BCM53242_A0m_ROBO],
    NULL,    /* CFP_DATA */
    NULL,    /* CFP_DATA_MASK */
    NULL,    /* CFP_MASK */
    &soc_robo_mem_list[SOC_MEM_INT_CFP_METER_BCM53242_A0m_ROBO],
    NULL,    /* CFP_RATE_METER */
    NULL,    /* CFP_STAT */
    &soc_robo_mem_list[SOC_MEM_INT_CFP_STAT_IB_BCM53242_A0m_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_CFP_STAT_OB_BCM53242_A0m_ROBO],
    NULL,    /* CFP_TCAM_CHAIN_MASK */
    NULL,    /* CFP_TCAM_CHAIN_SC */
    NULL,    /* CFP_TCAM_IPV4_MASK */
    NULL,    /* CFP_TCAM_IPV4_S0 */
    NULL,    /* CFP_TCAM_IPV4_S1 */
    NULL,    /* CFP_TCAM_IPV4_S2 */
    NULL,    /* CFP_TCAM_IPV4_S0_MASK */
    NULL,    /* CFP_TCAM_IPV4_S1_MASK */
    NULL,    /* CFP_TCAM_IPV4_S2_MASK */
    NULL,    /* CFP_TCAM_IPV4_SC */
    NULL,    /* CFP_TCAM_IPV6_MASK */
    NULL,    /* CFP_TCAM_IPV6_S0 */
    NULL,    /* CFP_TCAM_IPV6_S1 */
    NULL,    /* CFP_TCAM_IPV6_S2 */
    NULL,    /* CFP_TCAM_IPV6_S0_MASK */
    NULL,    /* CFP_TCAM_IPV6_S1_MASK */
    NULL,    /* CFP_TCAM_IPV6_S2_MASK */
    NULL,    /* CFP_TCAM_IPV6_SC */
    &soc_robo_mem_list[SOC_MEM_INT_CFP_TCAM_MASK_BCM53242_A0m_ROBO],
    NULL,    /* CFP_TCAM_NONIP_MASK */
    NULL,    /* CFP_TCAM_NONIP_SC */
    &soc_robo_mem_list[SOC_MEM_INT_CFP_TCAM_S0_BCM53242_A0m_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_CFP_TCAM_S1_BCM53242_A0m_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_CFP_TCAM_S2_BCM53242_A0m_ROBO],
    NULL,    /* CFP_TCAM_S3 */
    NULL,    /* CFP_TCAM_S4 */
    NULL,    /* CFP_TCAM_S5 */
    NULL,    /* CFP_TCAM_SC */
    NULL,    /* DPTC2PCP */
    NULL,    /* DSCPECN2TCDP */
    NULL,    /* EGRESS_VID_REMARK */
    NULL,    /* ERC_PORT */
    NULL,    /* EVM_ACT */
    NULL,    /* EVM_KEY_DATA */
    NULL,    /* EVM_KEY_DATA_MASK */
    NULL,    /* EVM_KEY_MASK */
    &soc_robo_mem_list[SOC_MEM_INT_FLOW2VLANm_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_GEN_MEMORYm_ROBO],
    NULL,    /* INT_8051_RAM */
    NULL,    /* INT_8051_ROM */
    NULL,    /* IRC_PORT */
    NULL,    /* IVM_ACT */
    NULL,    /* IVM_KEY_DATA_0 */
    NULL,    /* IVM_KEY_DATA_1 */
    NULL,    /* IVM_KEY_DATA_2 */
    NULL,    /* IVM_KEY_DATA_3 */
    NULL,    /* IVM_KEY_DATA_MASK */
    NULL,    /* IVM_KEY_MASK_0 */
    NULL,    /* IVM_KEY_MASK_1 */
    NULL,    /* IVM_KEY_MASK_2 */
    NULL,    /* IVM_KEY_MASK_3 */
    &soc_robo_mem_list[SOC_MEM_INT_L2_ARL_BCM53242_A0m_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_L2_ARL_SW_BCM5348_A0m_ROBO],
    NULL,    /* L2_MARL */
    &soc_robo_mem_list[SOC_MEM_INT_L2_MARL_SW_BCM5348_A0m_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_MAC2VLAN_BCM53242_A0m_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_MARL_PBMP_BCM5347_A0m_ROBO],
    NULL,    /* MCAST_VPORT_MAP */
    &soc_robo_mem_list[SOC_MEM_INT_MSPT_TAB_BCM53242_A0m_ROBO],
    NULL,    /* PCP2DPTC */
    NULL,    /* PORT_MASK */
    &soc_robo_mem_list[SOC_MEM_INT_PROTOCOL2VLANm_ROBO],
    NULL,    /* SA_LRN_CNT */
    NULL,    /* STSEC_COUNTER0 */
    NULL,    /* STSEC_COUNTER1 */
    NULL,    /* STSEC_COUNTER2 */
    NULL,    /* STSEC_MAC0 */
    NULL,    /* STSEC_MAC1 */
    NULL,    /* STSEC_MAC2 */
    NULL,    /* TCDP2DSCPECN */
    &soc_robo_mem_list[SOC_MEM_INT_VLAN2VLANm_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_VLAN_1Q_BCM53242_A0m_ROBO],
    NULL     /* VPORT_VID_MAP */
};

/*
 * Packet Statistics Counter Map for bcm53242_a0
 *
 * NOTE: soc_attach verifies this map is correct and prints warnings if
 * not. The map should contain only registers with a single field named
 * COUNT, and all such registers should be in the map.
 *
 * The soc_counter_map array is a list of counter registers in the order
 * found in the internal address map and counter DMA buffer.
 * counter_map[0 to NUM_COUNTER-1] corresponds to internal addresses
 * COUNTER_REG_FIRST through COUNTER_REG_LAST.
 *
 * This map structure, contents, and size are exposed only to provide a
 * convenient way to loop through all available counters.
 */

static soc_ctr_ref_t _fe_counters_bcm53242_a0[] = {
    {INDEX(      TXOCTETSr), 0}, /* 0x000 */
    {INDEX(     INVALID_Rr), 0}, /* 0x004 */
    {INDEX(    TXDROPPKTSr), 0}, /* 0x008 */
    {INDEX(   TXPAUSEPKTSr), 0}, /* 0x00c */
    {INDEX(TXBROADCASTPKTSr), 0}, /* 0x010 */
    {INDEX(TXMULTICASTPKTSr), 0}, /* 0x014 */
    {INDEX( TXUNICASTPKTSr), 0}, /* 0x018 */
    {INDEX(  TXCOLLISIONSr), 0}, /* 0x01c */
    {INDEX(TXSINGLECOLLISIONr), 0}, /* 0x020 */
    {INDEX(TXMULTIPLECOLLISIONr), 0}, /* 0x024 */
    {INDEX(TXDEFERREDTRANSMITr), 0}, /* 0x028 */
    {INDEX(TXLATECOLLISIONr), 0}, /* 0x02c */
    {INDEX(TXEXCESSIVECOLLISIONr), 0}, /* 0x030 */
    {INDEX( TXFRAMEINDISCr), 0}, /* 0x034 */
    {INDEX(    TXQOS0PKTSr), 0}, /* 0x038 */
    {INDEX(  TXQOS0OCTETSr), 0}, /* 0x03c */
    {INDEX(     INVALID_Rr), 0}, /* 0x040 */
    {INDEX(    TXQOS1PKTSr), 0}, /* 0x044 */
    {INDEX(  TXQOS1OCTETSr), 0}, /* 0x048 */
    {INDEX(     INVALID_Rr), 0}, /* 0x04c */
    {INDEX(    TXQOS2PKTSr), 0}, /* 0x050 */
    {INDEX(  TXQOS2OCTETSr), 0}, /* 0x054 */
    {INDEX(     INVALID_Rr), 0}, /* 0x058 */
    {INDEX(    TXQOS3PKTSr), 0}, /* 0x05c */
    {INDEX(  TXQOS3OCTETSr), 0}, /* 0x060 */
    {INDEX(     INVALID_Rr), 0}, /* 0x064 */
    {INDEX(      RXOCTETSr), 0}, /* 0x068 */
    {INDEX(     INVALID_Rr), 0}, /* 0x06c */
    {INDEX(RXUNDERSIZEPKTSr), 0}, /* 0x070 */
    {INDEX(   RXPAUSEPKTSr), 0}, /* 0x074 */
    {INDEX(  PKTS64OCTETSr), 0}, /* 0x078 */
    {INDEX(PKTS65TO127OCTETSr), 0}, /* 0x07c */
    {INDEX(PKTS128TO255OCTETSr), 0}, /* 0x080 */
    {INDEX(PKTS256TO511OCTETSr), 0}, /* 0x084 */
    {INDEX(PKTS512TO1023OCTETSr), 0}, /* 0x088 */
    {INDEX(PKTS1024TOMAXOCTETSr), 0}, /* 0x08c */
    {INDEX(RXOVERSIZEPKTSr), 0}, /* 0x090 */
    {INDEX(     RXJABBERSr), 0}, /* 0x094 */
    {INDEX(RXALIGNMENTERRORSr), 0}, /* 0x098 */
    {INDEX(   RXFCSERRORSr), 0}, /* 0x09c */
    {INDEX(  RXGOODOCTETSr), 0}, /* 0x0a0 */
    {INDEX(     INVALID_Rr), 0}, /* 0x0a4 */
    {INDEX(    RXDROPPKTSr), 0}, /* 0x0a8 */
    {INDEX( RXUNICASTPKTSr), 0}, /* 0x0ac */
    {INDEX(RXMULTICASTPKTSr), 0}, /* 0x0b0 */
    {INDEX(RXBROADCASTPKTr), 0}, /* 0x0b4 */
    {INDEX(   RXSACHANGESr), 0}, /* 0x0b8 */
    {INDEX(   RXFRAGMENTSr), 0}, /* 0x0bc */
    {INDEX(RXEXCESSSIZEDISCr), 0}, /* 0x0c0 */
    {INDEX(    RXSYMBLERRr), 0}, /* 0x0c4 */
    {INDEX( RXFWDDISCPKTSr), 0}, /* 0x0c8 */
};

static soc_ctr_ref_t _ge_counters_bcm53242_a0[] = {
    {INDEX(      TXOCTETSr), 0}, /* 0x000 */
    {INDEX(     INVALID_Rr), 0}, /* 0x004 */
    {INDEX(    TXDROPPKTSr), 0}, /* 0x008 */
    {INDEX(   TXPAUSEPKTSr), 0}, /* 0x00c */
    {INDEX(TXBROADCASTPKTSr), 0}, /* 0x010 */
    {INDEX(TXMULTICASTPKTSr), 0}, /* 0x014 */
    {INDEX( TXUNICASTPKTSr), 0}, /* 0x018 */
    {INDEX(  TXCOLLISIONSr), 0}, /* 0x01c */
    {INDEX(TXSINGLECOLLISIONr), 0}, /* 0x020 */
    {INDEX(TXMULTIPLECOLLISIONr), 0}, /* 0x024 */
    {INDEX(TXDEFERREDTRANSMITr), 0}, /* 0x028 */
    {INDEX(TXLATECOLLISIONr), 0}, /* 0x02c */
    {INDEX(TXEXCESSIVECOLLISIONr), 0}, /* 0x030 */
    {INDEX( TXFRAMEINDISCr), 0}, /* 0x034 */
    {INDEX(    TXQOS0PKTSr), 0}, /* 0x038 */
    {INDEX(  TXQOS0OCTETSr), 0}, /* 0x03c */
    {INDEX(     INVALID_Rr), 0}, /* 0x040 */
    {INDEX(    TXQOS1PKTSr), 0}, /* 0x044 */
    {INDEX(  TXQOS1OCTETSr), 0}, /* 0x048 */
    {INDEX(     INVALID_Rr), 0}, /* 0x04c */
    {INDEX(    TXQOS2PKTSr), 0}, /* 0x050 */
    {INDEX(  TXQOS2OCTETSr), 0}, /* 0x054 */
    {INDEX(     INVALID_Rr), 0}, /* 0x058 */
    {INDEX(    TXQOS3PKTSr), 0}, /* 0x05c */
    {INDEX(  TXQOS3OCTETSr), 0}, /* 0x060 */
    {INDEX(     INVALID_Rr), 0}, /* 0x064 */
    {INDEX(      RXOCTETSr), 0}, /* 0x068 */
    {INDEX(     INVALID_Rr), 0}, /* 0x06c */
    {INDEX(RXUNDERSIZEPKTSr), 0}, /* 0x070 */
    {INDEX(   RXPAUSEPKTSr), 0}, /* 0x074 */
    {INDEX(  PKTS64OCTETSr), 0}, /* 0x078 */
    {INDEX(PKTS65TO127OCTETSr), 0}, /* 0x07c */
    {INDEX(PKTS128TO255OCTETSr), 0}, /* 0x080 */
    {INDEX(PKTS256TO511OCTETSr), 0}, /* 0x084 */
    {INDEX(PKTS512TO1023OCTETSr), 0}, /* 0x088 */
    {INDEX(PKTS1024TOMAXOCTETSr), 0}, /* 0x08c */
    {INDEX(RXOVERSIZEPKTSr), 0}, /* 0x090 */
    {INDEX(     RXJABBERSr), 0}, /* 0x094 */
    {INDEX(RXALIGNMENTERRORSr), 0}, /* 0x098 */
    {INDEX(   RXFCSERRORSr), 0}, /* 0x09c */
    {INDEX(  RXGOODOCTETSr), 0}, /* 0x0a0 */
    {INDEX(     INVALID_Rr), 0}, /* 0x0a4 */
    {INDEX(    RXDROPPKTSr), 0}, /* 0x0a8 */
    {INDEX( RXUNICASTPKTSr), 0}, /* 0x0ac */
    {INDEX(RXMULTICASTPKTSr), 0}, /* 0x0b0 */
    {INDEX(RXBROADCASTPKTr), 0}, /* 0x0b4 */
    {INDEX(   RXSACHANGESr), 0}, /* 0x0b8 */
    {INDEX(   RXFRAGMENTSr), 0}, /* 0x0bc */
    {INDEX(RXEXCESSSIZEDISCr), 0}, /* 0x0c0 */
    {INDEX(    RXSYMBLERRr), 0}, /* 0x0c4 */
    {INDEX( RXFWDDISCPKTSr), 0}, /* 0x0c8 */
};

/*
 * The array to put into chip parameters.
 * This array is indexed by SOC_CTR_TYPE_xxx (soc_ctr_types_t)
 */
static soc_cmap_t soc_counter_maps_bcm53242_a0[SOC_CTR_NUM_TYPES] = {
    {_fe_counters_bcm53242_a0, 51},    /* FE */
    {_ge_counters_bcm53242_a0, 51},    /* GE */
    {NULL, 0},                        /* GFE */
    {NULL, 0},                        /* HG */
    {NULL, 0},                         /* XE */
    {NULL, 0},                        /* CPU */
    {NULL, 0},                         /* RX */
    {NULL, 0}                         /* TX */
};

static soc_block_info_t soc_blocks_bcm53242_a0[] = {
	{ SOC_BLK_CPIC,	0,	0,	3	},	/* 0 C0 */
	{ SOC_BLK_EPIC,	0,	0,	0	},	/* 1 E0 */
	{ SOC_BLK_EPIC,	1,	0,	1	},	/* 2 E1 */
	{ SOC_BLK_EPIC,	2,	0,	2	},	/* 3 E2 */
	{ SOC_BLK_EXP,	0,	0,	8	},	/* 4 E0 */
	{ SOC_BLK_GPIC,	0,	0,	4	},	/* 5 G0 */
	{ SOC_BLK_GPIC,	1,	0,	5	},	/* 6 G1 */
	{ SOC_BLK_GPIC,	2,	0,	6	},	/* 7 G2 */
	{ SOC_BLK_GPIC,	3,	0,	7	},	/* 8 G3 */
	{ SOC_BLK_SPI,	0,	0,	9	},	/* 9 S0 */
	{ SOC_BLK_SYS,	0,	0,	10	},	/* 10 S0 */
	{ -1,		-1,	-1,	-1	}	/* end */
};

static soc_port_info_t soc_ports_bcm53242_a0[] = {
	{ 1,	0	},	/* 0 E0.0 */
	{ 1,	1	},	/* 1 E0.1 */
	{ 1,	2	},	/* 2 E0.2 */
	{ 1,	3	},	/* 3 E0.3 */
	{ 1,	4	},	/* 4 E0.4 */
	{ 1,	5	},	/* 5 E0.5 */
	{ 1,	6	},	/* 6 E0.6 */
	{ 1,	7	},	/* 7 E0.7 */
	{ 2,	0	},	/* 8 E1.0 */
	{ 2,	1	},	/* 9 E1.1 */
	{ 2,	2	},	/* 10 E1.2 */
	{ 2,	3	},	/* 11 E1.3 */
	{ 2,	4	},	/* 12 E1.4 */
	{ 2,	5	},	/* 13 E1.5 */
	{ 2,	6	},	/* 14 E1.6 */
	{ 2,	7	},	/* 15 E1.7 */
	{ 3,	0	},	/* 16 E2.0 */
	{ 3,	1	},	/* 17 E2.1 */
	{ 3,	2	},	/* 18 E2.2 */
	{ 3,	3	},	/* 19 E2.3 */
	{ 3,	4	},	/* 20 E2.4 */
	{ 3,	5	},	/* 21 E2.5 */
	{ 3,	6	},	/* 22 E2.6 */
	{ 3,	7	},	/* 23 E2.7 */
	{ 0,	0	},	/* 24 C0.0 */
	{ 5,	0	},	/* 25 G0.0 */
	{ 6,	0	},	/* 26 G1.0 */
	{ -1,	-1	}	/* end */
};

/* Forward declaration of init function */
static void chip_init_bcm53242_a0(void);

soc_driver_t soc_driver_bcm53242_a0 = {
	/* type           */	SOC_CHIP_BCM53242_A0,
	/* chip_string    */	"harrier",
	/* origin         */	" Not located in Server Need Verified",
	/* pci_vendor     */	BROADCOM_VENDOR_ID,
	/* pci_device     */	BCM53242_DEVICE_ID,
	/* pci_revision   */	BCM53242_A0_REV_ID,
	/* num_cos        */	4,
	/* reg_info       */	soc_registers_bcm53242_a0,
	/* mem_info       */	soc_memories_bcm53242_a0,
	/* soc_mem_t      */	NULL,
	/* block_info     */	soc_blocks_bcm53242_a0,
	/* port_info      */	soc_ports_bcm53242_a0,
	/* counter_maps   */	soc_counter_maps_bcm53242_a0,
	/* features       */	soc_features_bcm53242_a0,
	/* init           */	chip_init_bcm53242_a0,
	/* services       */	&drv_bcm53242_services
};  /* soc_driver */

/* Chip specific bottom matter from memory file */

/****************************************************************
 *
 * Function:    chip_init_bcm53242_a0
 * Purpose:
 *     Initialize software internals for bcm53242_a0 device:
 *         Initialize null memories
 * Parameters:  void
 * Returns:     void
 *
 ****************************************************************/
static void
chip_init_bcm53242_a0(void)
{

}

/* End of chip specific bottom matter */

#endif /* BCM_53242_A0 */
