/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: bcm5396_a0.c 1.49 Broadcom SDK $
 * $Copyright: Copyright 2011 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 * File:	bcm5396_a0.c
 * Purpose:	bcm5396_a0 chip specific information (register, memories, etc)
 */


#include <sal/core/libc.h>
#include <soc/defs.h>
#include <soc/mem.h>
#include <soc/mcm/robo/memregs.h>
#include <soc/mcm/robo/driver.h>
#include <soc/mcm/robo/allenum.h>
#include <soc/mcm/robo/intenum.h>

#if defined(BCM_5396_A0)
#include <soc/robo/bcm5396_service.h>

/* Chip specific top matter from memory file */

/* These are the null memory descriptions for BCM5396_A0 */

/* End of chip specific top matter */

static soc_reg_info_t *soc_registers_bcm5396_a0[] = {
    &soc_robo_reg_list[SOC_REG_INT_ACTLSTS_BCM5396_A0r_ROBO],
    NULL,    /* ACT_POL_DATA */
    NULL,    /* ACT_POL_DATA0 */
    NULL,    /* ACT_POL_DATA1 */
    &soc_robo_reg_list[SOC_REG_INT_AEGSTS_BCM5396_A0r_ROBO],
    NULL,    /* AGEOUT_CTL */
    NULL,    /* AGEOUT_EN_VID */
    &soc_robo_reg_list[SOC_REG_INT_AMODE2_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_AMPHY_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ANADV_BCM5396_A0r_ROBO],
    NULL,    /* ANADV_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_ANEXP_BCM5396_A0r_ROBO],
    NULL,    /* ANEXP_EXT_P5 */
    NULL,    /* ANLPA */
    &soc_robo_reg_list[SOC_REG_INT_ANLPAR_BCM5396_A0r_ROBO],
    NULL,    /* ANLPA_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_ANNXP_BCM5396_A0r_ROBO],
    NULL,    /* ANNXP_EXT_P5 */
    NULL,    /* ARLA_ENTRY */
    NULL,    /* ARLA_ENTRY0 */
    NULL,    /* ARLA_ENTRY1 */
    NULL,    /* ARLA_ENTRY_0 */
    NULL,    /* ARLA_ENTRY_1 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_FWD_ENTRY0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_FWD_ENTRY1r_ROBO],
    NULL,    /* ARLA_FWD_ENTRY2 */
    NULL,    /* ARLA_FWD_ENTRY3 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_MACr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_MACVID_ENTRY0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_MACVID_ENTRY1r_ROBO],
    NULL,    /* ARLA_MACVID_ENTRY2 */
    NULL,    /* ARLA_MACVID_ENTRY3 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_RWCTL_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_ADR_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_CTL_BCM5396_A0r_ROBO],
    NULL,    /* ARLA_SRCH_RSLT */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_1r_ROBO],
    NULL,    /* ARLA_SRCH_RSLT_0_MACVID */
    NULL,    /* ARLA_SRCH_RSLT_1_MACVID */
    NULL,    /* ARLA_SRCH_RSLT_MACVID */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_MACVID_0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_MACVID_1r_ROBO],
    NULL,    /* ARLA_SRCH_RSLT_VID */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VID_BCM5396_A0r_ROBO],
    NULL,    /* ARLA_VID_ENTRY */
    NULL,    /* ARLA_VID_ENTRY0 */
    NULL,    /* ARLA_VID_ENTRY1 */
    NULL,    /* ARLA_VID_ENTRY_0 */
    NULL,    /* ARLA_VID_ENTRY_1 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VTBL_ADDRr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VTBL_ENTRYr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VTBL_RWCTRLr_ROBO],
    NULL,    /* ARL_SPAREREG0 */
    NULL,    /* ARL_SPAREREG1 */
    NULL,    /* ARL_SPAREREG2 */
    NULL,    /* ARL_SPAREREG3 */
    &soc_robo_reg_list[SOC_REG_INT_ASTSSUM_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_AUTH_8021X_CTL1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_AUTH_8021X_CTL2r_ROBO],
    NULL,    /* AUX_CONTROL_STATUS */
    NULL,    /* AUX_CONTROL_STATUS_EXT_P5 */
    NULL,    /* AUX_MODE */
    NULL,    /* AUX_MODE2 */
    NULL,    /* AUX_MODE2_EXT_P5 */
    NULL,    /* AUX_MODE_EXT_P5 */
    NULL,    /* AUX_MULTI_PHY */
    NULL,    /* AUX_MULTI_PHY_EXT_P5 */
    NULL,    /* AUX_STATUS_SUMMARY */
    NULL,    /* AUX_STATUS_SUMMARY_EXT_P5 */
    NULL,    /* AVB_AV_EN_CTRL */
    NULL,    /* AVB_C4_BW_CNTL */
    NULL,    /* AVB_C5_BW_CNTL */
    NULL,    /* AVB_EGRESS_TM_STAMP */
    NULL,    /* AVB_EGRESS_TS_PORTMAP */
    NULL,    /* AVB_EGRESS_TS_TM_STAMP */
    NULL,    /* AVB_LNK_STATUS */
    NULL,    /* AVB_MAX_AV_PKT_SZ */
    NULL,    /* AVB_SLOT_ADJ */
    NULL,    /* AVB_SLOT_TICK_CNTR */
    NULL,    /* AVB_TM_ADJ */
    NULL,    /* AVB_TM_BASE */
    NULL,    /* B100X_AUX_CONTROL */
    NULL,    /* B100X_AUX_CONTROL_EXT_P5 */
    NULL,    /* B100X_AUX_STATUS */
    NULL,    /* B100X_AUX_STATUS_EXT_P5 */
    NULL,    /* B100X_DISCONNECT_COUNTER */
    NULL,    /* B100X_DISCONNECT_COUNTER_EXT_P5 */
    NULL,    /* B100X_FALSE_CARRIER_SENSE_COUNTER */
    NULL,    /* B100X_FALSE_CARRIER_SENSE_COUNTER_EXT_P5 */
    NULL,    /* B100X_RX_ERROR_COUNTER */
    NULL,    /* B100X_RX_ERROR_COUNTER_EXT_P5 */
    NULL,    /* B10T_AUX_STATUS */
    NULL,    /* B10T_AUX_STATUS_EXT_P5 */
    NULL,    /* BCAST_FWD_MAP */
    NULL,    /* BC_SUP_PKTDROP_CNT_IMP */
    &soc_robo_reg_list[SOC_REG_INT_BC_SUP_PKTDROP_CNT_Pr_ROBO],
    NULL,    /* BC_SUP_RATECTRL_IMP */
    NULL,    /* BC_SUP_RATECTRL_P */
    NULL,    /* BG_SEL */
    &soc_robo_reg_list[SOC_REG_INT_BIST_STS_BCM5396_A0r_ROBO],
    NULL,    /* BIST_STS0 */
    NULL,    /* BIST_STS1 */
    NULL,    /* BONDING_PAD */
    NULL,    /* BONDING_PAD_STATUS */
    NULL,    /* BOND_DIRECT_PIN */
    &soc_robo_reg_list[SOC_REG_INT_BPDU_MCADDRr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_BRCMTST_BCM5396_A0r_ROBO],
    NULL,    /* BRCM_HDR_CTRL */
    NULL,    /* BRCM_TAG_CTRL */
    NULL,    /* BROADCOM_TEST */
    NULL,    /* BROADCOM_TEST_EXT_P5 */
    NULL,    /* BUFCON_MEMADR */
    NULL,    /* BUFCON_MEMDAT0 */
    NULL,    /* BUFCON_MEMDAT1 */
    NULL,    /* C4_WEIGHT */
    NULL,    /* CFP_ACC */
    NULL,    /* CFP_CTL_REG */
    NULL,    /* CFP_DATA */
    NULL,    /* CFP_EN_CTRL */
    NULL,    /* CFP_GLOBAL_CTL */
    NULL,    /* CFP_MASK */
    NULL,    /* CFP_RC */
    NULL,    /* CFP_TEST */
    NULL,    /* CFP_UDF_0_A */
    NULL,    /* CFP_UDF_0_B08 */
    NULL,    /* CFP_UDF_0_C */
    NULL,    /* CFP_UDF_1_A */
    NULL,    /* CFP_UDF_1_C */
    NULL,    /* CFP_UDF_2_A */
    NULL,    /* CFP_UDF_2_B */
    NULL,    /* CFP_UDF_2_C */
    NULL,    /* CFP_UDF_3_D */
    NULL,    /* CFP_UDF_A */
    NULL,    /* CFP_UDF_B */
    NULL,    /* CFP_UDF_C */
    NULL,    /* CFP_UDF_D */
    NULL,    /* CFP_UNLCK */
    NULL,    /* CHIP0_PORT_AGE */
    &soc_robo_reg_list[SOC_REG_INT_CHIP_REVID_BCM5396_A0r_ROBO],
    NULL,    /* CHIP_RST_CTL */
    NULL,    /* CLASS_PCP */
    NULL,    /* CLKSET */
    &soc_robo_reg_list[SOC_REG_INT_COMM_IRC_CON_BCM5396_A0r_ROBO],
    NULL,    /* COS_VALUE_CTRL */
    NULL,    /* CPU2COS_MAP */
    NULL,    /* CPU_ADDRESS */
    NULL,    /* CPU_DATA1_SHARE */
    NULL,    /* CPU_DATA_SHARE */
    NULL,    /* CPU_MEM_RD_EN */
    NULL,    /* CPU_OTP_ADDR */
    NULL,    /* CPU_OTP_CTL */
    NULL,    /* CPU_OTP_RD_DATA */
    NULL,    /* CPU_OTP_STATUS */
    NULL,    /* CPU_OTP_WR_DATA */
    NULL,    /* CPU_RAM_ROM_SEL */
    NULL,    /* CPU_READ_DATA */
    NULL,    /* CPU_RESOURCE_ARBITER */
    NULL,    /* CRC16_GP */
    NULL,    /* CTRL_REG */
    NULL,    /* DEBUG_CONGESTION */
    &soc_robo_reg_list[SOC_REG_INT_DEBUG_REG_BCM5396_A0r_ROBO],
    NULL,    /* DEBUG_STS */
    &soc_robo_reg_list[SOC_REG_INT_DEFAULT_1Q_TAG_BCM5396_A0r_ROBO],
    NULL,    /* DEFAULT_1Q_TAG_IMP */
    NULL,    /* DEF_PORT_QOS_CFG */
    NULL,    /* DF_TIMER */
    &soc_robo_reg_list[SOC_REG_INT_DIAGNOSISr_ROBO],
    NULL,    /* DIRECT_CTRL_PIN */
    NULL,    /* DIRECT_INPUT_CTRL_VALUE */
    NULL,    /* DIS_LEARN */
    NULL,    /* DMA_CTRL */
    NULL,    /* DMA_LPB_BUF_ADDR */
    NULL,    /* DMA_LPB_BUF_SIZE */
    NULL,    /* DOS_ATTACK_FILTER_DROP_CTL */
    NULL,    /* DOS_ATTACK_FILTER_EVENT */
    NULL,    /* DOS_CTRL */
    NULL,    /* DOS_DIS_LRN_REG */
    NULL,    /* DOU_TAG_TPID */
    NULL,    /* DP_CTRL */
    NULL,    /* DSCP2TC_DP_MAP0 */
    NULL,    /* DSCP2TC_DP_MAP1 */
    NULL,    /* DSCP2TC_DP_MAP2 */
    NULL,    /* DSCP2TC_DP_MAP3 */
    NULL,    /* DSCP2TC_DP_MAP4 */
    NULL,    /* DSCP2TC_DP_MAP5 */
    NULL,    /* DSCP2TC_DP_MAP6 */
    NULL,    /* DSCP2TC_DP_MAP7 */
    NULL,    /* DTAG_GLO_CTL */
    NULL,    /* DTAG_TPID */
    &soc_robo_reg_list[SOC_REG_INT_DUPSTS_BCM5396_A0r_ROBO],
    NULL,    /* EAP_DIP */
    NULL,    /* EAP_GLO_CON */
    NULL,    /* EAP_MULTI_ADDR_CTRL */
    NULL,    /* EAP_PORT_CTL */
    NULL,    /* EAV_LNK_STATUS */
    NULL,    /* EEE_DEBUG */
    NULL,    /* EEE_EN_CTRL */
    NULL,    /* EEE_GLB_CONG_TH */
    NULL,    /* EEE_LINK_DLY_TIMER */
    NULL,    /* EEE_LPI_ASSERT */
    NULL,    /* EEE_LPI_DURATION */
    NULL,    /* EEE_LPI_EVENT */
    NULL,    /* EEE_LPI_INDICATE */
    NULL,    /* EEE_MIN_LP_TIMER_G */
    NULL,    /* EEE_MIN_LP_TIMER_G_IMP */
    NULL,    /* EEE_MIN_LP_TIMER_H */
    NULL,    /* EEE_MIN_LP_TIMER_H_IMP */
    NULL,    /* EEE_PHY_CTRL */
    NULL,    /* EEE_PIPELINE_TIMER */
    NULL,    /* EEE_RX_IDLE_SYMBOL */
    NULL,    /* EEE_SLEEP_TIMER_G */
    NULL,    /* EEE_SLEEP_TIMER_G_IMP */
    NULL,    /* EEE_SLEEP_TIMER_H */
    NULL,    /* EEE_SLEEP_TIMER_H_IMP */
    NULL,    /* EEE_STATE */
    NULL,    /* EEE_TXQ_CONG_TH */
    NULL,    /* EEE_WAKE_TIMER_G */
    NULL,    /* EEE_WAKE_TIMER_G_IMP */
    NULL,    /* EEE_WAKE_TIMER_H */
    NULL,    /* EEE_WAKE_TIMER_H_IMP */
    &soc_robo_reg_list[SOC_REG_INT_EGMIRCTL_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EGMIRDIV_BCM5396_A0r_ROBO],
    NULL,    /* EGMIRMAC */
    NULL,    /* EGRESS_NAVB_PKT_TC2PCP_MAP */
    NULL,    /* EGRESS_NAVB_PKT_TC2PCP_MAP_IMP */
    NULL,    /* EGRESS_NRESE_PKT_TC2PCP_MAP */
    NULL,    /* EGRESS_NRESE_PKT_TC2PCP_MAP_8 */
    NULL,    /* EGRESS_NRESE_PKT_TC2PCP_MAP_IMP */
    NULL,    /* EGRESS_RMON */
    NULL,    /* EGRESS_SFLOW */
    NULL,    /* EGRESS_VID_RMK_TBL_ACS */
    NULL,    /* EGRESS_VID_RMK_TBL_DATA */
    NULL,    /* EN_IMP_CONG_REMAP */
    NULL,    /* EN_IMP_HIGH_RATE */
    NULL,    /* EN_TOTAL_MC_DROP_IMP */
    NULL,    /* EQZ_CTRL */
    NULL,    /* EXP_PORT */
    &soc_robo_reg_list[SOC_REG_INT_EXTPHY_SCAN_CTLr_ROBO],
    NULL,    /* EXT_ACTLSTS */
    NULL,    /* EXT_AEGSTS */
    NULL,    /* EXT_AMODE2 */
    NULL,    /* EXT_AMPHY */
    NULL,    /* EXT_ANADV */
    NULL,    /* EXT_ANEXP */
    NULL,    /* EXT_ANLPA */
    NULL,    /* EXT_ANNXP */
    NULL,    /* EXT_ASTSSUM */
    NULL,    /* EXT_BRCMTST */
    NULL,    /* EXT_HNDRD_ACTL */
    NULL,    /* EXT_HNDRD_ASTS */
    NULL,    /* EXT_HNDRD_FCSCNT */
    NULL,    /* EXT_HNDRD_RECNT */
    NULL,    /* EXT_LPNXP */
    NULL,    /* EXT_MIICTL */
    NULL,    /* EXT_MIISTS */
    NULL,    /* EXT_PHYIDH */
    NULL,    /* EXT_PHYIDL */
    NULL,    /* E_ACTLSTS */
    NULL,    /* E_AEGSTS */
    NULL,    /* E_AMODE2 */
    NULL,    /* E_AMPHY */
    NULL,    /* E_ANADV */
    NULL,    /* E_ANEXP */
    NULL,    /* E_ANLPA */
    NULL,    /* E_ANNXP */
    NULL,    /* E_ASTSSUM */
    NULL,    /* E_BRCMTST */
    NULL,    /* E_HNDRD_ACTL */
    NULL,    /* E_HNDRD_ASTS */
    NULL,    /* E_HNDRD_FCSCNT */
    NULL,    /* E_HNDRD_RECNT */
    NULL,    /* E_LPNXP */
    NULL,    /* E_MIICTL */
    NULL,    /* E_MIISTS */
    NULL,    /* E_PHYIDH */
    NULL,    /* E_PHYIDL */
    &soc_robo_reg_list[SOC_REG_INT_FAST_AGE_CTLr_ROBO],
    NULL,    /* FAST_AGE_CTRL */
    NULL,    /* FAST_AGE_PORT */
    NULL,    /* FAST_AGE_VID */
    NULL,    /* FAST_AGING_CTL */
    &soc_robo_reg_list[SOC_REG_INT_FAST_AGING_PORTr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FAST_AGING_VIDr_ROBO],
    NULL,    /* FCON_BCST_TH_CTRL */
    NULL,    /* FCON_DIAG_CTRL */
    NULL,    /* FCON_DLF_TH_CTRL */
    NULL,    /* FCON_FLOWCON_STATUS0 */
    NULL,    /* FCON_FLOWCON_STATUS1 */
    NULL,    /* FCON_FLOWCON_STATUS2 */
    NULL,    /* FCON_FLOWCON_STATUS3 */
    NULL,    /* FCON_FLOWCON_STATUS4 */
    NULL,    /* FCON_FLOWCON_STATUS5 */
    NULL,    /* FCON_FLOWCON_STATUS6 */
    NULL,    /* FCON_FLOWCON_STATUS7 */
    NULL,    /* FCON_FLOWCON_STATUS8 */
    NULL,    /* FCON_FLOWCON_STATUS9 */
    NULL,    /* FCON_FLOWCON_STATUS10 */
    NULL,    /* FCON_FLOWCON_STATUS11 */
    NULL,    /* FCON_FLOWCON_STATUS12 */
    NULL,    /* FCON_FLOWCON_STATUS13 */
    NULL,    /* FCON_FLOWMIX */
    NULL,    /* FCON_GLOB_TH_CTRL_1 */
    NULL,    /* FCON_GLOB_TH_CTRL_2 */
    NULL,    /* FCON_MISC_CTRL */
    NULL,    /* FCON_MISC_TXFLOW_CTRL */
    NULL,    /* FCON_PERQ_TXDROP_CTRL */
    NULL,    /* FCON_Q0_100_TH_CTRL_1 */
    NULL,    /* FCON_Q0_100_TH_CTRL_2 */
    NULL,    /* FCON_Q0_TXDSC_CTRL_3 */
    NULL,    /* FCON_Q1_100_TH_CTRL_1 */
    NULL,    /* FCON_Q1_100_TH_CTRL_2 */
    NULL,    /* FCON_Q1_TXDSC_CTRL_3 */
    NULL,    /* FCON_Q2_100_TH_CTRL_1 */
    NULL,    /* FCON_Q2_100_TH_CTRL_2 */
    NULL,    /* FCON_Q2_TXDSC_CTRL_3 */
    NULL,    /* FCON_Q3_100_TH_CTRL_1 */
    NULL,    /* FCON_Q3_100_TH_CTRL_2 */
    NULL,    /* FCON_Q3_TXDSC_CTRL_3 */
    NULL,    /* FCON_RSRV_BUFNUM */
    NULL,    /* FCON_RXBASE_BUFNUM */
    NULL,    /* FCON_RX_FCON_CTRL */
    NULL,    /* FCON_SPARE0 */
    NULL,    /* FCON_SPARE1 */
    NULL,    /* FCON_SPARE2 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL0 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL1 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL2 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL3 */
    NULL,    /* FCON_TXQ_FULL_TH */
    NULL,    /* FC_CHIP_INFO */
    &soc_robo_reg_list[SOC_REG_INT_FC_CHIP_INFO_1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CHIP_INFO_2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_BUF_ERR_HISr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP01r_ROBO],
    NULL,    /* FC_CONG_PORTMAP8 */
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP16r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP23r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP45r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP67r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP89r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP1011r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP1213r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP1415r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_DIAG_CTRLr_ROBO],
    NULL,    /* FC_GIGA_INFO */
    &soc_robo_reg_list[SOC_REG_INT_FC_GIGA_INFO_1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_GIGA_INFO_2r_ROBO],
    NULL,    /* FC_IMP_THRESH_ADJUST_Q */
    NULL,    /* FC_MCAST_DROP_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_FC_MCAST_DROP_CTRL_1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_MCAST_DROP_CTRL_2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_MON_TXQr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PAUSE_DROP_CTRLr_ROBO],
    NULL,    /* FC_PAUSE_HIS */
    &soc_robo_reg_list[SOC_REG_INT_FC_PAUSE_HIS_1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PAUSE_HIS_2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PEAK_RXBYTEr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PEAK_TOTAL_USEDr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PEAK_TXQr_ROBO],
    NULL,    /* FC_PEAK_TXQ_45 */
    NULL,    /* FC_Q45_CONG_PORTMAP_8 */
    NULL,    /* FC_Q45_CONG_PORTMAP_0123 */
    NULL,    /* FC_Q45_CONG_PORTMAP_4567 */
    NULL,    /* FC_RXBUF_ERR_HIS */
    &soc_robo_reg_list[SOC_REG_INT_FC_RXBUF_ERR_HIS_1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RXBUF_ERR_HIS_2r_ROBO],
    NULL,    /* FC_RXPAUSE_HIS */
    &soc_robo_reg_list[SOC_REG_INT_FC_RXPAUSE_HIS_1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RXPAUSE_HIS_2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RX_HYSTr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RX_MAX_PTRr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RX_RSRVr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RX_RUNOFFr_ROBO],
    NULL,    /* FC_SPARE_REG */
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_DROP_Qr_ROBO],
    NULL,    /* FC_TOTAL_TH_DROP_Q45 */
    NULL,    /* FC_TOTAL_TH_DROP_Q_IMP */
    NULL,    /* FC_TOTAL_TH_DROP_Q_WAN */
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_HYST_Qr_ROBO],
    NULL,    /* FC_TOTAL_TH_HYST_Q45 */
    NULL,    /* FC_TOTAL_TH_HYST_Q_IMP */
    NULL,    /* FC_TOTAL_TH_HYST_Q_WAN */
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_PAUSE_Qr_ROBO],
    NULL,    /* FC_TOTAL_TH_PAUSE_Q45 */
    NULL,    /* FC_TOTAL_TH_PAUSE_Q_IMP */
    NULL,    /* FC_TOTAL_TH_PAUSE_Q_WAN */
    NULL,    /* FC_TOTAL_TH_RSRV_Q */
    NULL,    /* FC_TOTAL_USED */
    NULL,    /* FC_TXPAUSE_HIS */
    &soc_robo_reg_list[SOC_REG_INT_FC_TXPAUSE_HIS_1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXPAUSE_HIS_2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_DROP_Qr_ROBO],
    NULL,    /* FC_TXQ_TH_DROP_Q45 */
    NULL,    /* FC_TXQ_TH_DROP_Q_IMP */
    NULL,    /* FC_TXQ_TH_DROP_Q_WAN */
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_PAUSE_Qr_ROBO],
    NULL,    /* FC_TXQ_TH_PAUSE_Q45 */
    NULL,    /* FC_TXQ_TH_PAUSE_Q_IMP */
    NULL,    /* FC_TXQ_TH_PAUSE_Q_WAN */
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_RSRV_Qr_ROBO],
    NULL,    /* FC_TXQ_TH_RSRV_Q45 */
    NULL,    /* FC_TXQ_TH_RSRV_Q_IMP */
    NULL,    /* FC_TXQ_TH_RSRV_Q_WAN */
    NULL,    /* FLOW_MON_BUS */
    NULL,    /* FM_MEMADR */
    NULL,    /* FM_MEMDAT0 */
    NULL,    /* FM_MEMDAT1 */
    NULL,    /* FM_MEMDAT2 */
    NULL,    /* FM_MEMDAT3 */
    NULL,    /* FM_SIZE_CTL */
    NULL,    /* FORCE_FRAME_DROP */
    &soc_robo_reg_list[SOC_REG_INT_GARLCFG_BCM5396_A0r_ROBO],
    NULL,    /* GENMEM_ADDR */
    NULL,    /* GENMEM_CTL */
    NULL,    /* GENMEM_DATA */
    NULL,    /* GENMEM_DATA0 */
    NULL,    /* GENMEM_DATA1 */
    NULL,    /* GLB_ACTLSTS */
    NULL,    /* GLB_AEGSTS */
    NULL,    /* GLB_AMODE2 */
    NULL,    /* GLB_AMPHY */
    NULL,    /* GLB_ANADV */
    NULL,    /* GLB_ANEXP */
    NULL,    /* GLB_ANLPA */
    NULL,    /* GLB_ANNXP */
    NULL,    /* GLB_ASTSSUM */
    NULL,    /* GLB_BRCMTST */
    NULL,    /* GLB_HNDRD_ACTL */
    NULL,    /* GLB_HNDRD_ASTS */
    NULL,    /* GLB_HNDRD_FCSCNT */
    NULL,    /* GLB_HNDRD_RECNT */
    NULL,    /* GLB_LPNXP */
    NULL,    /* GLB_MIICTL */
    NULL,    /* GLB_MIISTS */
    NULL,    /* GLB_OVERFLOW_DROP_PKT_CNT */
    NULL,    /* GLB_PHYIDH */
    NULL,    /* GLB_PHYIDL */
    NULL,    /* GLB_VLAN_ING_FILTER_CTL */
    NULL,    /* GLOBAL_CONGESTION_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_GLOBAL_TRUNK_CTL_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_GMNGCFG_BCM5396_A0r_ROBO],
    NULL,    /* GREEN_MODE_DATA */
    NULL,    /* GREEN_MODE_DEBUG */
    NULL,    /* GREEN_MODE_SELECT */
    NULL,    /* GROUP_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_GRPADDR1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_GRPADDR2r_ROBO],
    NULL,    /* G_ANADV */
    NULL,    /* G_ANADV_EXT */
    NULL,    /* G_ANADV_EXT_P5 */
    NULL,    /* G_ANADV_EXT_P7 */
    NULL,    /* G_ANEXP */
    NULL,    /* G_ANEXP_EXT */
    NULL,    /* G_ANEXP_EXT_P5 */
    NULL,    /* G_ANEXP_EXT_P7 */
    NULL,    /* G_ANLPA */
    NULL,    /* G_ANLPA_EXT */
    NULL,    /* G_ANLPA_EXT_P5 */
    NULL,    /* G_ANLPA_EXT_P7 */
    NULL,    /* G_ANNXP */
    NULL,    /* G_ANNXP_EXT */
    NULL,    /* G_ANNXP_EXT_P5 */
    NULL,    /* G_ANNXP_EXT_P7 */
    NULL,    /* G_AUX_CTL */
    NULL,    /* G_AUX_CTL_EXT */
    NULL,    /* G_AUX_CTL_EXT_P5 */
    NULL,    /* G_AUX_CTL_EXT_P7 */
    NULL,    /* G_AUX_STS */
    NULL,    /* G_AUX_STS_EXT */
    NULL,    /* G_AUX_STS_EXT_P5 */
    NULL,    /* G_AUX_STS_EXT_P7 */
    NULL,    /* G_B1000T_CTL */
    NULL,    /* G_B1000T_CTL_EXT */
    NULL,    /* G_B1000T_CTL_EXT_P5 */
    NULL,    /* G_B1000T_CTL_EXT_P7 */
    NULL,    /* G_B1000T_STS */
    NULL,    /* G_B1000T_STS_EXT */
    NULL,    /* G_B1000T_STS_EXT_P5 */
    NULL,    /* G_B1000T_STS_EXT_P7 */
    NULL,    /* G_DSP_COEFFICIENT */
    NULL,    /* G_DSP_COEFFICIENT_ADDR */
    NULL,    /* G_DSP_COEFFICIENT_ADDR_EXT */
    NULL,    /* G_DSP_COEFFICIENT_ADDR_EXT_P5 */
    NULL,    /* G_DSP_COEFFICIENT_ADDR_EXT_P7 */
    NULL,    /* G_DSP_COEFFICIENT_EXT */
    NULL,    /* G_DSP_COEFFICIENT_EXT_P5 */
    NULL,    /* G_DSP_COEFFICIENT_EXT_P7 */
    NULL,    /* G_EXT_STS */
    NULL,    /* G_EXT_STS_EXT */
    NULL,    /* G_EXT_STS_EXT_P5 */
    NULL,    /* G_EXT_STS_EXT_P7 */
    NULL,    /* G_FALSE_CARR_CNT */
    NULL,    /* G_FALSE_CARR_CNT_EXT */
    NULL,    /* G_FALSE_CARR_CNT_EXT_P5 */
    NULL,    /* G_FALSE_CARR_CNT_EXT_P7 */
    NULL,    /* G_INTERRUPT_MSK */
    NULL,    /* G_INTERRUPT_MSK_EXT */
    NULL,    /* G_INTERRUPT_MSK_EXT_P5 */
    NULL,    /* G_INTERRUPT_MSK_EXT_P7 */
    NULL,    /* G_INTERRUPT_STS */
    NULL,    /* G_INTERRUPT_STS_EXT */
    NULL,    /* G_INTERRUPT_STS_EXT_P5 */
    NULL,    /* G_INTERRUPT_STS_EXT_P7 */
    NULL,    /* G_LPNXP */
    NULL,    /* G_LPNXP_EXT */
    NULL,    /* G_LPNXP_EXT_P5 */
    NULL,    /* G_LPNXP_EXT_P7 */
    NULL,    /* G_MASTER_SLAVE_SEED */
    NULL,    /* G_MASTER_SLAVE_SEED_EXT */
    NULL,    /* G_MASTER_SLAVE_SEED_EXT_P5 */
    NULL,    /* G_MASTER_SLAVE_SEED_EXT_P7 */
    NULL,    /* G_MIICTL */
    NULL,    /* G_MIICTL_EXT */
    NULL,    /* G_MIICTL_EXT_P5 */
    NULL,    /* G_MIICTL_EXT_P7 */
    NULL,    /* G_MIISTS */
    NULL,    /* G_MIISTS_EXT */
    NULL,    /* G_MIISTS_EXT_P5 */
    NULL,    /* G_MIISTS_EXT_P7 */
    NULL,    /* G_MISC_SHADOW */
    NULL,    /* G_MISC_SHADOW_EXT */
    NULL,    /* G_MISC_SHADOW_EXT_P5 */
    NULL,    /* G_MISC_SHADOW_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_PCTL_BCM5396_A0r_ROBO],
    NULL,    /* G_PHYIDH */
    NULL,    /* G_PHYIDH_EXT */
    NULL,    /* G_PHYIDH_EXT_P5 */
    NULL,    /* G_PHYIDH_EXT_P7 */
    NULL,    /* G_PHYIDL */
    NULL,    /* G_PHYIDL_EXT */
    NULL,    /* G_PHYIDL_EXT_P5 */
    NULL,    /* G_PHYIDL_EXT_P7 */
    NULL,    /* G_PHY_EXT_CTL */
    NULL,    /* G_PHY_EXT_CTL_EXT */
    NULL,    /* G_PHY_EXT_CTL_EXT_P5 */
    NULL,    /* G_PHY_EXT_CTL_EXT_P7 */
    NULL,    /* G_PHY_EXT_STS */
    NULL,    /* G_PHY_EXT_STS_EXT */
    NULL,    /* G_PHY_EXT_STS_EXT_P5 */
    NULL,    /* G_PHY_EXT_STS_EXT_P7 */
    NULL,    /* G_REC_ERR_CNT */
    NULL,    /* G_REC_ERR_CNT_EXT */
    NULL,    /* G_REC_ERR_CNT_EXT_P5 */
    NULL,    /* G_REC_ERR_CNT_EXT_P7 */
    NULL,    /* G_REC_NOTOK_CNT */
    NULL,    /* G_REC_NOTOK_CNT_EXT */
    NULL,    /* G_REC_NOTOK_CNT_EXT_P5 */
    NULL,    /* G_REC_NOTOK_CNT_EXT_P7 */
    NULL,    /* G_TEST1 */
    NULL,    /* G_TEST2 */
    NULL,    /* G_TEST1_EXT */
    NULL,    /* G_TEST1_EXT_P5 */
    NULL,    /* G_TEST1_EXT_P7 */
    NULL,    /* G_TEST2_EXT */
    NULL,    /* G_TEST2_EXT_P5 */
    NULL,    /* G_TEST2_EXT_P7 */
    NULL,    /* HL_PRTC_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_HNDRD_ACTL_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_HNDRD_ASTS_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_HNDRD_FCSCNT_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_HNDRD_RECNT_BCM5396_A0r_ROBO],
    NULL,    /* IEEE802P2_LLC */
    NULL,    /* IEEE_802_2_LLC */
    &soc_robo_reg_list[SOC_REG_INT_IGMIRCTL_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_IGMIRDIV_BCM5396_A0r_ROBO],
    NULL,    /* IGMIRMAC */
    NULL,    /* IMP0_PRT_ID */
    NULL,    /* IMP1_EGRESS_RATE_CTRL_CFG_REG */
    NULL,    /* IMP1_PRT_ID */
    NULL,    /* IMP_CTL */
    NULL,    /* IMP_EGRESS_RATE_CTRL_CFG_REG */
    NULL,    /* IMP_PCP2TC */
    NULL,    /* IMP_PCTL */
    NULL,    /* IMP_RGMII_CTL_GP */
    NULL,    /* IMP_RGMII_TIME_DLY_GP */
    NULL,    /* IMP_SLEEP_STS */
    NULL,    /* IMP_SLEEP_TIMER */
    NULL,    /* IMP_SOFTWARE_EGRESS_CTRL */
    NULL,    /* INGRESS_RMON */
    NULL,    /* INGRESS_SFLOW */
    NULL,    /* INGRESS_SFLOW_PORT */
    NULL,    /* INRANGEERRCOUNT */
    NULL,    /* INRANGEERRPKTS */
    NULL,    /* INTERNAL_CPU_DEBUG */
    NULL,    /* INTERNAL_CPU_MII_PORT_CONTROL */
    NULL,    /* INTERNAL_CPU_MMR_ADDRESS */
    NULL,    /* INTERNAL_CPU_MMR_DATA */
    NULL,    /* INTERRUPT */
    NULL,    /* INTERRUPT_EXT_P5 */
    NULL,    /* INT_EN */
    NULL,    /* INT_STS */
    NULL,    /* INT_TRIGGER */
    NULL,    /* IN_CPU_CTRL */
    NULL,    /* IPG_SHRNK_CTRL */
    NULL,    /* ISP_PORT_SEL_PBM */
    NULL,    /* ISP_SEL_PORTMAP */
    NULL,    /* ISP_TPID */
    NULL,    /* ISP_VID */
    NULL,    /* IVM_EVM_HIT_ENTRY */
    NULL,    /* JUMBOPKT */
    &soc_robo_reg_list[SOC_REG_INT_JUMBO_PORT_MASKr_ROBO],
    NULL,    /* L4PORT_RANGE_CHECKER */
    NULL,    /* LCPLL_CTRL_H */
    NULL,    /* LCPLL_CTRL_L */
    NULL,    /* LCPLL_STATE_OUTPUT */
    &soc_robo_reg_list[SOC_REG_INT_LDMETER_UPDATE_RATECTLr_ROBO],
    NULL,    /* LD_FRM_SA */
    NULL,    /* LED0_ST */
    NULL,    /* LED1_ST */
    NULL,    /* LED2_ST */
    NULL,    /* LED3_ST */
    &soc_robo_reg_list[SOC_REG_INT_LEDA_CTLr_ROBO],
    NULL,    /* LEDA_ST */
    NULL,    /* LEDB_ST */
    NULL,    /* LEDC_ST */
    NULL,    /* LEDD_ST */
    NULL,    /* LED_CONTROL */
    NULL,    /* LED_EN_MAP */
    NULL,    /* LED_FLSH_CTL */
    NULL,    /* LED_FUNC0_CTL */
    NULL,    /* LED_FUNC1_CTL */
    NULL,    /* LED_FUNC_MAP */
    NULL,    /* LED_MODE_MAP_0 */
    NULL,    /* LED_MODE_MAP_1 */
    NULL,    /* LED_OPTIONS */
    NULL,    /* LED_OUTPUT_ENABLE */
    NULL,    /* LED_PORTMAP */
    NULL,    /* LED_REFLSH_CTL */
    &soc_robo_reg_list[SOC_REG_INT_LNKSTS_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LNKSTSCHG_BCM5396_A0r_ROBO],
    NULL,    /* LOW_POWER_CTRL */
    NULL,    /* LPDET_CFG */
    NULL,    /* LPDET_SA */
    &soc_robo_reg_list[SOC_REG_INT_LPNXP_BCM5396_A0r_ROBO],
    NULL,    /* LPNXP_EXT_P5 */
    NULL,    /* LP_STA_GP */
    NULL,    /* LRN_CNT_CTL */
    NULL,    /* LSA_MII_PORT */
    NULL,    /* LSA_PORT */
    NULL,    /* MAC2VLAN_CTL */
    NULL,    /* MAC_FM_DROP_CTL */
    NULL,    /* MAC_SEC_CON0 */
    NULL,    /* MAC_SEC_CON1 */
    NULL,    /* MAC_SEC_CON2 */
    NULL,    /* MAC_SEC_CON3 */
    NULL,    /* MAC_SEC_CON4 */
    NULL,    /* MAC_TRUNK_CTL */
    &soc_robo_reg_list[SOC_REG_INT_MARLA_FWD_ENTRY0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MARLA_FWD_ENTRY1r_ROBO],
    NULL,    /* MARLA_SRCH_RSLT */
    &soc_robo_reg_list[SOC_REG_INT_MARLA_SRCH_RSLT_0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MARLA_SRCH_RSLT_1r_ROBO],
    NULL,    /* MAX_ICMPV4_SIZE */
    NULL,    /* MAX_ICMPV4_SIZE_REG */
    NULL,    /* MAX_ICMPV6_SIZE */
    NULL,    /* MAX_ICMPV6_SIZE_REG */
    NULL,    /* MCAST_SUP0 */
    NULL,    /* MCAST_SUP1 */
    NULL,    /* MDIO_ADDR_P */
    NULL,    /* MDIO_ADDR_P8 */
    NULL,    /* MDIO_ADDR_WAN */
    NULL,    /* MDIO_BASE_ADDR */
    NULL,    /* MDIO_DIRECT_ACCESS */
    NULL,    /* MDIO_IMP_ADDR */
    NULL,    /* MDIO_PORT7_ADDR */
    NULL,    /* MDIO_WAN_ADDR */
    NULL,    /* MEMORY_TEST_CTRL */
    NULL,    /* MEMORY_TEST_CTRL_1 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_ADDRr_ROBO],
    NULL,    /* MEM_ADDR_0 */
    NULL,    /* MEM_ADDR_1 */
    NULL,    /* MEM_ADDR_2 */
    NULL,    /* MEM_ADDR_3 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_ARL_B0_HIr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_ARL_B0_LOr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_ARL_B1_HIr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_ARL_B1_LOr_ROBO],
    NULL,    /* MEM_ARL_HIGH */
    NULL,    /* MEM_ARL_LOW */
    NULL,    /* MEM_BFC_ADDR */
    NULL,    /* MEM_BFC_DATA */
    &soc_robo_reg_list[SOC_REG_INT_MEM_BTM_DATAr_ROBO],
    NULL,    /* MEM_BTM_DATA0 */
    NULL,    /* MEM_BTM_DATA1 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_CTRLr_ROBO],
    NULL,    /* MEM_DATA_0 */
    NULL,    /* MEM_DATA_1 */
    NULL,    /* MEM_DATA_2 */
    NULL,    /* MEM_DATA_3 */
    NULL,    /* MEM_DATA_4 */
    NULL,    /* MEM_DATA_5 */
    NULL,    /* MEM_DATA_6 */
    NULL,    /* MEM_DATA_7 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_DATA_HIGHr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_DATA_LOWr_ROBO],
    NULL,    /* MEM_DEBUG_DATA_0_0 */
    NULL,    /* MEM_DEBUG_DATA_0_1 */
    NULL,    /* MEM_DEBUG_DATA_1_0 */
    NULL,    /* MEM_DEBUG_DATA_1_1 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_ADDRr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA4r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA5r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA6r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA7r_ROBO],
    NULL,    /* MEM_INDEX */
    NULL,    /* MEM_KEY_0 */
    NULL,    /* MEM_KEY_1 */
    NULL,    /* MEM_KEY_2 */
    NULL,    /* MEM_KEY_3 */
    NULL,    /* MEM_KEY_4 */
    NULL,    /* MEM_KEY_5 */
    NULL,    /* MEM_KEY_6 */
    NULL,    /* MEM_KEY_7 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_MARL_B0_HIr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_ARL_B0_LOr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_MARL_B1_HIr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_ARL_B1_LOr_ROBO],
    NULL,    /* MEM_MARL_HIGH */
    NULL,    /* MEM_MARL_LOW */
    NULL,    /* MEM_SRCH_ADDR_0 */
    NULL,    /* MEM_SRCH_CTRL */
    NULL,    /* MEM_SRCH_DATA_0 */
    NULL,    /* MEM_SRCH_DATA_1 */
    NULL,    /* MEM_SRCH_INDEX */
    NULL,    /* MEM_SRCH_KEY_2 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_TEST_CTLr_ROBO],
    NULL,    /* MEM_TEST_CTRL_0 */
    NULL,    /* MEM_TEST_CTRL_1 */
    NULL,    /* MEM_TEST_CTRL_2 */
    NULL,    /* MEM_TEST_CTRL_3 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_VLAN_DATAr_ROBO],
    NULL,    /* MIBDIAG_PAGE */
    NULL,    /* MIBDIGA_PAGE */
    NULL,    /* MIBKILLOVR */
    NULL,    /* MIB_GD_FM_MAX_SIZE */
    NULL,    /* MIB_PORT_SEL */
    &soc_robo_reg_list[SOC_REG_INT_MIB_SELECTr_ROBO],
    NULL,    /* MIB_SNAPSHOT_CTL */
    &soc_robo_reg_list[SOC_REG_INT_MIICTL_BCM5396_A0r_ROBO],
    NULL,    /* MIICTL_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_MIISTS_BCM5396_A0r_ROBO],
    NULL,    /* MIISTS_EXT_P5 */
    &soc_robo_reg_list[SOC_REG_INT_MII_PCTL_BCM5396_A0r_ROBO],
    NULL,    /* MINIMUM_TCP_HDR_SZ */
    NULL,    /* MIN_TCP_HEADER_SIZE */
    &soc_robo_reg_list[SOC_REG_INT_MIRCAPCTL_BCM5396_A0r_ROBO],
    NULL,    /* MIRRORCTL */
    &soc_robo_reg_list[SOC_REG_INT_MISC_CTLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MLF_DROP_MAP_BCM5396_A0r_ROBO],
    NULL,    /* MLF_IMPC_FWD_MAP */
    NULL,    /* MLF_IPMC_FWD_MAP */
    NULL,    /* MNGPID */
    &soc_robo_reg_list[SOC_REG_INT_MODEL_IDr_ROBO],
    NULL,    /* MODULE_ID0 */
    NULL,    /* MODULE_ID1 */
    NULL,    /* MONITOR_TOTAL_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ0_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ1_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ2_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ3_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ4_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ5_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ6_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ7_BUF_USED_COUNT */
    NULL,    /* MONITOR_TX_PORT_CTRL */
    NULL,    /* MPORTVEC0 */
    NULL,    /* MPORTVEC1 */
    NULL,    /* MPORTVEC2 */
    NULL,    /* MPORTVEC3 */
    NULL,    /* MPORTVEC4 */
    NULL,    /* MPORTVEC5 */
    NULL,    /* MR_STA */
    NULL,    /* MST_AGE */
    &soc_robo_reg_list[SOC_REG_INT_MST_CON_BCM5396_A0r_ROBO],
    NULL,    /* MST_TAB */
    &soc_robo_reg_list[SOC_REG_INT_MST_TBLr_ROBO],
    NULL,    /* MULTIPORT_ADDR0 */
    NULL,    /* MULTIPORT_ADDR1 */
    NULL,    /* MULTIPORT_ADDR2 */
    NULL,    /* MULTIPORT_ADDR3 */
    NULL,    /* MULTIPORT_ADDR4 */
    NULL,    /* MULTIPORT_ADDR5 */
    NULL,    /* MULTI_PORT_CTL */
    &soc_robo_reg_list[SOC_REG_INT_NEW_CONTROL_BCM5396_A0r_ROBO],
    NULL,    /* NEW_CTRL */
    NULL,    /* NEW_PRI_MAP */
    NULL,    /* OTHER_CHECKER */
    NULL,    /* OTHER_TABLE_DATA0 */
    NULL,    /* OTHER_TABLE_DATA1 */
    NULL,    /* OTHER_TABLE_DATA2 */
    NULL,    /* OTHER_TABLE_INDEX */
    NULL,    /* OTPROM_STATUS */
    NULL,    /* OTP_ADDR_REG */
    NULL,    /* OTP_CTL_REG */
    NULL,    /* OTP_RD_DATA */
    NULL,    /* OTP_STS_REG */
    NULL,    /* OTP_WR_DATA */
    NULL,    /* OUTOFRANGEERRPKTS */
    NULL,    /* OUTRANGEERRCOUNT */
    NULL,    /* P5_RGMII_TIME_DLY_GP */
    NULL,    /* P8_PCP2TC */
    NULL,    /* PAGEREG */
    NULL,    /* PAUSESTS */
    NULL,    /* PAUSE_CAP */
    NULL,    /* PAUSE_FM_SA */
    &soc_robo_reg_list[SOC_REG_INT_PAUSE_FRM_CTRLr_ROBO],
    NULL,    /* PAUSE_QUANTA */
    NULL,    /* PBPTRFIFO */
    NULL,    /* PBPTRFIFO_0 */
    NULL,    /* PBPTRFIFO_1 */
    NULL,    /* PCP_VALUE_CTRL */
    NULL,    /* PEAK_TEMP_MON_RESU */
    NULL,    /* PEAK_TOTAL_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ0_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ1_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ2_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ3_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ4_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ5_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ6_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ7_BUF_USED_COUNT */
    &soc_robo_reg_list[SOC_REG_INT_PHYIDH_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PHYIDL_BCM5396_A0r_ROBO],
    NULL,    /* PHYINFO_PHYIDH */
    NULL,    /* PHYINFO_PHYIDL */
    NULL,    /* PHYSCAN_CTL */
    NULL,    /* PHY_CTRL */
    NULL,    /* PHY_INT_STS */
    NULL,    /* PHY_LED_FUNC */
    NULL,    /* PHY_PWR_DOWN */
    &soc_robo_reg_list[SOC_REG_INT_PHY_STATr_ROBO],
    NULL,    /* PHY_STS */
    NULL,    /* PKTS1024TO1522OCTETS */
    NULL,    /* PKTS1024TOMAXOCTETS */
    NULL,    /* PKTS1024TOMAXPKTOCTETS */
    NULL,    /* PKTS128TO255OCTETS */
    NULL,    /* PKTS1523TO2047 */
    NULL,    /* PKTS2048TO4095 */
    NULL,    /* PKTS256TO511OCTETS */
    NULL,    /* PKTS4096TO8191 */
    NULL,    /* PKTS512TO1023OCTETS */
    NULL,    /* PKTS64OCTETS */
    NULL,    /* PKTS65TO127OCTETS */
    NULL,    /* PKTS8192TO9728 */
    NULL,    /* PKT_MARK_CTL */
    NULL,    /* PLL_CTRL */
    NULL,    /* PLL_CTRL_0 */
    NULL,    /* PLL_CTRL_1 */
    NULL,    /* PLL_CTRL_2 */
    NULL,    /* PLL_FREQ_SEL */
    NULL,    /* PLL_STS */
    NULL,    /* PLL_TEST */
    NULL,    /* PLL_TEST_CTRL_I */
    NULL,    /* PLL_TEST_CTRL_II */
    NULL,    /* PN_PCP2TC */
    NULL,    /* PORT4_RGMII_CTL_GP */
    NULL,    /* PORT5_RGMII_CTL_GP */
    NULL,    /* PORT7_RGMII_CTL_GP */
    NULL,    /* PORT7_RGMII_TIME_DLY_GP */
    &soc_robo_reg_list[SOC_REG_INT_PORTVEC1_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PORTVEC2_BCM5396_A0r_ROBO],
    NULL,    /* PORT_CROSS_CONNECT */
    NULL,    /* PORT_EAP1_CON */
    NULL,    /* PORT_EAP_CON */
    NULL,    /* PORT_EAP_DA */
    NULL,    /* PORT_EGCTL */
    NULL,    /* PORT_ERC_CON */
    NULL,    /* PORT_ERC_CON_IMP */
    NULL,    /* PORT_IRC1_CON */
    &soc_robo_reg_list[SOC_REG_INT_PORT_IRC_CON_BCM5396_A0r_ROBO],
    NULL,    /* PORT_MAX_LEARN */
    NULL,    /* PORT_SA_CNT */
    NULL,    /* PORT_SEC_CON */
    NULL,    /* PORT_VLAN1_CTL */
    &soc_robo_reg_list[SOC_REG_INT_PORT_VLAN_CTL_BCM5396_A0r_ROBO],
    NULL,    /* PORT_VLAN_CTL_IMP */
    NULL,    /* PORT_XOFF_STS */
    NULL,    /* POST_LED_CTRL */
    NULL,    /* PRBS_CTL */
    NULL,    /* PRBS_STA */
    NULL,    /* PRESERVE_PKT_FORMAT */
    NULL,    /* PROFILE_CTL */
    NULL,    /* PROTECTED_SEL */
    NULL,    /* PROTOCOL2VLAN_CTL */
    NULL,    /* PRS_FIFO_DEBUG_CTRL */
    NULL,    /* PRS_FIFO_DEBUG_DATA */
    NULL,    /* PTEST */
    NULL,    /* PWR_DOWN_MODE */
    &soc_robo_reg_list[SOC_REG_INT_QOS_1P1Q_PRI_MAPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_1P_EN_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_CTL_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP1_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP2_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP3r_ROBO],
    NULL,    /* QOS_D_TOS_TH */
    &soc_robo_reg_list[SOC_REG_INT_QOS_EN_DIFFSERVr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_EN_TRAFFIC_PRI_REMAPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_ETHERPRI_CTRLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_GLOBAL_CTRLr_ROBO],
    NULL,    /* QOS_MIB_QUE_SEL */
    NULL,    /* QOS_M_TOS_TH */
    NULL,    /* QOS_PAUSE_EN */
    NULL,    /* QOS_REASON_CODE */
    &soc_robo_reg_list[SOC_REG_INT_QOS_RX_CTRL_Pr_ROBO],
    NULL,    /* QOS_R_TOS_TH */
    NULL,    /* QOS_TCI_TH */
    NULL,    /* QOS_TOS_DIF_CTL */
    NULL,    /* QOS_TOS_DIF_EN */
    &soc_robo_reg_list[SOC_REG_INT_QOS_TRAFFIC_PRI_REMAPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_TX_CTRLr_ROBO],
    NULL,    /* QOS_T_TOS_TH */
    &soc_robo_reg_list[SOC_REG_INT_QOS_WEIGHTr_ROBO],
    NULL,    /* QUEUE_CONGESTION_STATUS0 */
    NULL,    /* QUEUE_CONGESTION_STATUS1 */
    NULL,    /* QUEUE_CONGESTION_STATUS2 */
    NULL,    /* QUEUE_CONGESTION_STATUS3 */
    NULL,    /* QUEUE_CONGESTION_STATUS4 */
    NULL,    /* QUEUE_CONGESTION_STATUS5 */
    NULL,    /* QUEUE_REGION_STATUS */
    NULL,    /* RANGE_CHECKER */
    NULL,    /* RANGE_CHECKER_CTL */
    NULL,    /* RANGE_CHECKER_FIELD_SEL */
    NULL,    /* RATE_INBAND */
    NULL,    /* RATE_METER0 */
    NULL,    /* RATE_METER1 */
    NULL,    /* RATE_OUTBAND */
    NULL,    /* RCM_CTL */
    NULL,    /* RCM_DATA0 */
    NULL,    /* RCM_DATA1 */
    NULL,    /* RCM_DATA2 */
    NULL,    /* RCM_DATA3 */
    NULL,    /* RCM_DATA4 */
    NULL,    /* RCM_PORT */
    NULL,    /* REGULATOR_CTRL */
    NULL,    /* REGULATOR_UNLOCK */
    NULL,    /* REGULATOR_VOLT_SEL */
    NULL,    /* RESE_AV_EN_CTRL */
    NULL,    /* RESE_C4_BW_CNTL */
    NULL,    /* RESE_C5_BW_CNTL */
    NULL,    /* RESE_EGRESS_TM_STAMP */
    NULL,    /* RESE_MAX_AV_PKT_SZ */
    NULL,    /* RESE_SLOT_ADJ */
    NULL,    /* RESE_SLOT_TICK_CNTR */
    NULL,    /* RESE_TM_ADJ */
    NULL,    /* RESE_TM_BASE */
    NULL,    /* RGMII_CTL_GP */
    NULL,    /* RGMII_CTL_GP48 */
    NULL,    /* RGMII_CTL_GP49 */
    NULL,    /* RGMII_CTL_GP50 */
    &soc_robo_reg_list[SOC_REG_INT_RGMII_CTRLr_ROBO],
    NULL,    /* RGMII_CTRL_GP25 */
    NULL,    /* RGMII_CTRL_GP26 */
    NULL,    /* RGMII_CTRL_IMP */
    &soc_robo_reg_list[SOC_REG_INT_RGMII_TIME_DELAY_CTRLr_ROBO],
    NULL,    /* RGMII_TIME_DLY_CTRL_GP25 */
    NULL,    /* RGMII_TIME_DLY_CTRL_GP26 */
    NULL,    /* RGMII_TIME_DLY_CTRL_IMP */
    NULL,    /* RGMII_TIME_DLY_GP */
    NULL,    /* RGMII_TIME_DLY_GP48 */
    NULL,    /* RGMII_TIME_DLY_GP49 */
    NULL,    /* RGMII_TIME_DLY_GP50 */
    NULL,    /* RMONSTEER */
    NULL,    /* RM_PINS_DEBUG */
    NULL,    /* RST_TABLE_MEM */
    NULL,    /* RST_TABLE_MEM1 */
    &soc_robo_reg_list[SOC_REG_INT_RSV_MCAST_CTRLr_ROBO],
    NULL,    /* RXALIGNMENTERRORS */
    NULL,    /* RXBROADCASTPKT */
    NULL,    /* RXBROADCASTPKTS */
    NULL,    /* RXDISCARD */
    &soc_robo_reg_list[SOC_REG_INT_RXDROPPKTS_BCM5396_A0r_ROBO],
    NULL,    /* RXEXCESSSIZEDISC */
    &soc_robo_reg_list[SOC_REG_INT_RXFCSERRORS_BCM5396_A0r_ROBO],
    NULL,    /* RXFRAGMENTS */
    NULL,    /* RXFWDDISCPKTS */
    &soc_robo_reg_list[SOC_REG_INT_RXGOODOCTETS_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXGOODPKTSr_ROBO],
    NULL,    /* RXJABBERPKTS */
    NULL,    /* RXJABBERS */
    NULL,    /* RXMULTICASTPKTS */
    NULL,    /* RXOCTETS */
    &soc_robo_reg_list[SOC_REG_INT_RXOVERSIZEPKTS_BCM5396_A0r_ROBO],
    NULL,    /* RXPAUSEPKTS */
    &soc_robo_reg_list[SOC_REG_INT_RXPAUSESTSr_ROBO],
    NULL,    /* RXPKTS1024TOMAXPKT */
    NULL,    /* RXPKTS128TO255OCTETS */
    NULL,    /* RXPKTS256TO511OCTETS */
    NULL,    /* RXPKTS512TO1023OCTETS */
    NULL,    /* RXPKTS64OCTETS */
    NULL,    /* RXPKTS65TO127OCTETS */
    NULL,    /* RXQOSOCTETS */
    NULL,    /* RXQOSPKTS */
    NULL,    /* RXSACHANGES */
    NULL,    /* RXSYMBLERR */
    NULL,    /* RXSYMBOLERR */
    NULL,    /* RXUNDERSIZEPKTS */
    &soc_robo_reg_list[SOC_REG_INT_RXUNICASTPKTS_BCM5396_A0r_ROBO],
    NULL,    /* RX_GLOBAL_CTL */
    NULL,    /* RX_JUMBO_PACKET_COUNTER */
    NULL,    /* RX_PAUSE_PASS */
    NULL,    /* SCAN_RSLT_GP */
    NULL,    /* SCAN_RSLT_IMP */
    NULL,    /* SCAN_RSLT_P */
    NULL,    /* SCAN_TIMEOUT */
    &soc_robo_reg_list[SOC_REG_INT_SDACTLSTSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDAEGSTSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDAMODE2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDAMPHYr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDANADVr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDANEXPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDANLPAr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDANNXPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDASTSSUMr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDBRCMTSTr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDHNDRD_ACTLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDHNDRD_ASTSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDHNDRD_FCSCNTr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDHNDRD_RECNTr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDLPNXPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDMIICTLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDMIISTSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDPHYIDHr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SDPHYIDLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SD_DEFAULTr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SD_SEL_EARLYr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SD_SIGNAL_DETCr_ROBO],
    NULL,    /* SECURITY_BYPASS_CTL */
    NULL,    /* SECURITY_GLOBAL_CTL */
    NULL,    /* SEC_DPMSK */
    NULL,    /* SEC_SPMSK */
    NULL,    /* SEC_TDIP0 */
    NULL,    /* SEC_TDIP1 */
    NULL,    /* SERDES_CTRL */
    NULL,    /* SFT_LRN_CTL */
    NULL,    /* SGMII_CLR_CTL */
    NULL,    /* SGMII_CTL_GP */
    NULL,    /* SGMII_STA_GP */
    NULL,    /* SIP_REG */
    NULL,    /* SLICE_MAP_P */
    NULL,    /* SLICE_MAP_P8 */
    NULL,    /* SPARE_REG0 */
    NULL,    /* SPARE_REG1 */
    NULL,    /* SPARE_REG2 */
    &soc_robo_reg_list[SOC_REG_INT_SPDSTS_BCM5396_A0r_ROBO],
    NULL,    /* SPECIAL_MNGT */
    NULL,    /* SPICTL */
    NULL,    /* SPIDIO0 */
    NULL,    /* SPIDIO1 */
    NULL,    /* SPIDIO2 */
    NULL,    /* SPIDIO3 */
    NULL,    /* SPIDIO4 */
    NULL,    /* SPIDIO5 */
    NULL,    /* SPIDIO6 */
    NULL,    /* SPIDIO7 */
    NULL,    /* SPISTS */
    &soc_robo_reg_list[SOC_REG_INT_SPTAGT_BCM5396_A0r_ROBO],
    NULL,    /* SPT_MULTI_ADDR_BPS_CTRL */
    NULL,    /* SRCADRCHG */
    NULL,    /* STP_BYPASS_CTL */
    NULL,    /* STRAP_PIN_STATUS */
    NULL,    /* STRAP_STS */
    &soc_robo_reg_list[SOC_REG_INT_STRAP_VALUEr_ROBO],
    NULL,    /* STS_CTL */
    NULL,    /* STS_OVERRIDE_GMIIP */
    &soc_robo_reg_list[SOC_REG_INT_STS_OVERRIDE_GP_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_STS_OVERRIDE_IMPr_ROBO],
    NULL,    /* STS_OVERRIDE_P */
    NULL,    /* STS_OVERRIDE_P24 */
    NULL,    /* STS_OVERRIDE_WAN_P */
    NULL,    /* SWITCH_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_SWMODE_BCM5396_A0r_ROBO],
    NULL,    /* SW_FLOW_CON */
    NULL,    /* SW_XOFF_PORT_CTL */
    NULL,    /* S_ANADV */
    NULL,    /* S_ANEXP */
    NULL,    /* S_ANLPA1 */
    NULL,    /* S_ANLPA2 */
    NULL,    /* S_ANNXP */
    NULL,    /* S_EEE_LPI_DURATION */
    NULL,    /* S_EEE_LPI_EVENT */
    NULL,    /* S_EXT_STS */
    NULL,    /* S_INRANGEERRCOUNT */
    NULL,    /* S_INRANGEERRPKTS */
    NULL,    /* S_JUMBOPKT */
    NULL,    /* S_MIICTL */
    NULL,    /* S_MIISTS */
    NULL,    /* S_OUTOFRANGEERRPKTS */
    NULL,    /* S_OUTRANGEERRCOUNT */
    NULL,    /* S_PHYIDH */
    NULL,    /* S_PHYIDL */
    NULL,    /* S_PKTS1024TO1522OCTETS */
    NULL,    /* S_PKTS1024TOMAXOCTETS */
    NULL,    /* S_PKTS1024TOMAXPKTOCTETS */
    NULL,    /* S_PKTS128TO255OCTETS */
    NULL,    /* S_PKTS1523TO2047 */
    NULL,    /* S_PKTS2048TO4095 */
    NULL,    /* S_PKTS256TO511OCTETS */
    NULL,    /* S_PKTS4096TO8191 */
    NULL,    /* S_PKTS512TO1023OCTETS */
    NULL,    /* S_PKTS64OCTETS */
    NULL,    /* S_PKTS65TO127OCTETS */
    NULL,    /* S_PKTS8192TO9728 */
    NULL,    /* S_RXALIGNMENTERRORS */
    NULL,    /* S_RXBROADCASTPKT */
    NULL,    /* S_RXBROADCASTPKTS */
    NULL,    /* S_RXDISCARD */
    NULL,    /* S_RXDROPPKTS */
    NULL,    /* S_RXEXCESSSIZEDISC */
    NULL,    /* S_RXFCSERRORS */
    NULL,    /* S_RXFRAGMENTS */
    NULL,    /* S_RXFWDDISCPKTS */
    NULL,    /* S_RXGOODOCTETS */
    NULL,    /* S_RXJABBERPKTS */
    NULL,    /* S_RXJABBERS */
    NULL,    /* S_RXMULTICASTPKTS */
    NULL,    /* S_RXOCTETS */
    NULL,    /* S_RXOVERSIZEPKTS */
    NULL,    /* S_RXPAUSEPKTS */
    NULL,    /* S_RXPKTS1024TOMAXPKT */
    NULL,    /* S_RXPKTS128TO255OCTETS */
    NULL,    /* S_RXPKTS256TO511OCTETS */
    NULL,    /* S_RXPKTS512TO1023OCTETS */
    NULL,    /* S_RXPKTS64OCTETS */
    NULL,    /* S_RXPKTS65TO127OCTETS */
    NULL,    /* S_RXQOSOCTETS */
    NULL,    /* S_RXQOSPKTS */
    NULL,    /* S_RXSACHANGES */
    NULL,    /* S_RXSYMBLERR */
    NULL,    /* S_RXSYMBOLERR */
    NULL,    /* S_RXUNDERSIZEPKTS */
    NULL,    /* S_RXUNICASTPKTS */
    NULL,    /* S_RX_JUMBO_PACKET_COUNTER */
    NULL,    /* S_TXBROADCASTPKTS */
    NULL,    /* S_TXCOLLISIONS */
    NULL,    /* S_TXDEFERREDTRANSMIT */
    NULL,    /* S_TXDROPPKTS */
    NULL,    /* S_TXEXCESSIVECOLLISION */
    NULL,    /* S_TXFRAMEINDISC */
    NULL,    /* S_TXLATECOLLISION */
    NULL,    /* S_TXMULTICASTPKTS */
    NULL,    /* S_TXMULTIPLECOLLISION */
    NULL,    /* S_TXMULTIPLECOLLISIONS */
    NULL,    /* S_TXOCTETS */
    NULL,    /* S_TXPAUSEPKTS */
    NULL,    /* S_TXPKTS1024TOMAXPKT */
    NULL,    /* S_TXPKTS128TO255OCTETS */
    NULL,    /* S_TXPKTS256TO511OCTETS */
    NULL,    /* S_TXPKTS512TO1023OCTETS */
    NULL,    /* S_TXPKTS64OCTETS */
    NULL,    /* S_TXPKTS65TO127OCTETS */
    NULL,    /* S_TXPORTCONGESTIONDROP */
    NULL,    /* S_TXQOS0OCTETS */
    NULL,    /* S_TXQOS0PKTS */
    NULL,    /* S_TXQOS1OCTETS */
    NULL,    /* S_TXQOS1PKTS */
    NULL,    /* S_TXQOS2OCTETS */
    NULL,    /* S_TXQOS2PKTS */
    NULL,    /* S_TXQOS3OCTETS */
    NULL,    /* S_TXQOS3PKTS */
    NULL,    /* S_TXQOSOCTETS */
    NULL,    /* S_TXQOSPKTS */
    NULL,    /* S_TXQPKTQ0 */
    NULL,    /* S_TXQPKTQ1 */
    NULL,    /* S_TXQPKTQ2 */
    NULL,    /* S_TXQPKTQ3 */
    NULL,    /* S_TXQPKTQ4 */
    NULL,    /* S_TXQPKTQ5 */
    NULL,    /* S_TXQQ0OCTETS */
    NULL,    /* S_TXQQ0PACKET */
    NULL,    /* S_TXQQ1OCTETS */
    NULL,    /* S_TXQQ1PACKET */
    NULL,    /* S_TXQQ2OCTETS */
    NULL,    /* S_TXQQ2PACKET */
    NULL,    /* S_TXQQ3OCTETS */
    NULL,    /* S_TXQQ3PACKET */
    NULL,    /* S_TXQQ4OCTETS */
    NULL,    /* S_TXQQ4PACKET */
    NULL,    /* S_TXQQ5OCTETS */
    NULL,    /* S_TXQQ5PACKET */
    NULL,    /* S_TXQQ6OCTETS */
    NULL,    /* S_TXQQ6PACKET */
    NULL,    /* S_TXQQ7OCTETS */
    NULL,    /* S_TXQQ7PACKET */
    NULL,    /* S_TXQQSEL0CONGESTIONDROP */
    NULL,    /* S_TXQQSEL1CONGESTIONDROP */
    NULL,    /* S_TXSINGLECOLLISION */
    NULL,    /* S_TXSINGLECOLLISIONS */
    NULL,    /* S_TXUNICASTPKTS */
    NULL,    /* S_TX_JUMBO_PACKET_COUNTER */
    NULL,    /* TBI_CTL */
    NULL,    /* TC2COS_MAP */
    NULL,    /* TCAM_BIST_CONTROL */
    NULL,    /* TCAM_BIST_CTL */
    NULL,    /* TCAM_BIST_STATUS */
    NULL,    /* TCAM_BIST_STS0 */
    NULL,    /* TCAM_BIST_STS1 */
    NULL,    /* TCAM_CHKSUM_STS */
    NULL,    /* TCAM_CTL */
    NULL,    /* TCAM_CTRL */
    NULL,    /* TCAM_TEST_COMPARE_STATUS */
    NULL,    /* TCP_UDP_ACTION_REG */
    NULL,    /* TCP_UDP_HIT_REG */
    NULL,    /* TCP_UDP_KEY_REG */
    NULL,    /* TCP_UDP_WILDCARD_ACTION_REG */
    NULL,    /* TC_DP2DSCP_MAP0 */
    NULL,    /* TC_DP2DSCP_MAP1 */
    NULL,    /* TC_DP2DSCP_MAP2 */
    NULL,    /* TC_DP2DSCP_MAP3 */
    NULL,    /* TC_DP2DSCP_MAP4 */
    NULL,    /* TC_DP2DSCP_MAP5 */
    NULL,    /* TC_DP2DSCP_MAP6 */
    NULL,    /* TC_DP2DSCP_MAP7 */
    NULL,    /* TC_GROUP_CTRL */
    NULL,    /* TEMP_MON_CAL */
    NULL,    /* TEMP_MON_CTL */
    NULL,    /* TEMP_MON_RESU */
    NULL,    /* TEMP_MON_SPEC_CTL */
    NULL,    /* TH_PCTL */
    NULL,    /* TM_STAMP_RPT_CTRL */
    NULL,    /* TM_STAMP_STATUS */
    NULL,    /* TOTAL_CONGESTION_ON_THRESHOLD */
    NULL,    /* TOTAL_DLF_DROP_THRESH_Q1 */
    NULL,    /* TOTAL_DLF_DROP_THRESH_Q2 */
    NULL,    /* TOTAL_DLF_DROP_THRESH_Q3 */
    NULL,    /* TOTAL_DROP_THRESH_Q1 */
    NULL,    /* TOTAL_DROP_THRESH_Q2 */
    NULL,    /* TOTAL_DROP_THRESH_Q3 */
    NULL,    /* TOTAL_HYST_COUNT */
    NULL,    /* TOTAL_HYST_THRESH_Q1 */
    NULL,    /* TOTAL_HYST_THRESH_Q2 */
    NULL,    /* TOTAL_HYST_THRESH_Q3 */
    NULL,    /* TOTAL_LIMIT_THRESHOLD */
    NULL,    /* TOTAL_MC_DROP_IMP_THRESH */
    NULL,    /* TOTAL_PAUSE_IMP_THRESH */
    NULL,    /* TOTAL_PROTECTION_ON_THRESHOLD */
    NULL,    /* TOTAL_REGION_STATUS */
    NULL,    /* TRREG_CTRL */
    NULL,    /* TRUNK_GRP0_CTL */
    NULL,    /* TRUNK_GRP1_CTL */
    NULL,    /* TRUNK_GRP2_CTL */
    NULL,    /* TRUNK_GRP3_CTL */
    NULL,    /* TRUNK_GRP_00_CTL */
    NULL,    /* TRUNK_GRP_01_CTL */
    NULL,    /* TRUNK_GRP_02_CTL */
    NULL,    /* TRUNK_GRP_03_CTL */
    NULL,    /* TRUNK_GRP_04_CTL */
    NULL,    /* TRUNK_GRP_05_CTL */
    NULL,    /* TRUNK_GRP_06_CTL */
    NULL,    /* TRUNK_GRP_07_CTL */
    NULL,    /* TRUNK_GRP_08_CTL */
    NULL,    /* TRUNK_GRP_09_CTL */
    NULL,    /* TRUNK_GRP_10_CTL */
    NULL,    /* TRUNK_GRP_11_CTL */
    NULL,    /* TRUNK_GRP_12_CTL */
    NULL,    /* TRUNK_GRP_13_CTL */
    &soc_robo_reg_list[SOC_REG_INT_TRUNK_GRP_CTLr_ROBO],
    NULL,    /* TRUST_C1P_CTL */
    NULL,    /* TRUST_CVID */
    NULL,    /* TRUST_CVLAN */
    NULL,    /* TRUST_DSCP_CTL */
    NULL,    /* TRUST_S1P_CTL */
    NULL,    /* TXBROADCASTPKTS */
    &soc_robo_reg_list[SOC_REG_INT_TXCOLLISIONS_BCM5396_A0r_ROBO],
    NULL,    /* TXDEFERREDTRANSMIT */
    &soc_robo_reg_list[SOC_REG_INT_TXDROPPKTS_BCM5396_A0r_ROBO],
    NULL,    /* TXEXCESSIVECOLLISION */
    NULL,    /* TXFRAMEINDISC */
    &soc_robo_reg_list[SOC_REG_INT_TXGOODPKTSr_ROBO],
    NULL,    /* TXLATECOLLISION */
    NULL,    /* TXMULTICASTPKTS */
    NULL,    /* TXMULTIPLECOLLISION */
    NULL,    /* TXMULTIPLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_TXOCTETS_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXPAUSEPKTS_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXPAUSESTSr_ROBO],
    NULL,    /* TXPKTS1024TOMAXPKT */
    NULL,    /* TXPKTS128TO255OCTETS */
    NULL,    /* TXPKTS256TO511OCTETS */
    NULL,    /* TXPKTS512TO1023OCTETS */
    NULL,    /* TXPKTS64OCTETS */
    NULL,    /* TXPKTS65TO127OCTETS */
    NULL,    /* TXPORTCONGESTIONDROP */
    NULL,    /* TXQOS0OCTETS */
    NULL,    /* TXQOS0PKTS */
    NULL,    /* TXQOS1OCTETS */
    NULL,    /* TXQOS1PKTS */
    NULL,    /* TXQOS2OCTETS */
    NULL,    /* TXQOS2PKTS */
    NULL,    /* TXQOS3OCTETS */
    NULL,    /* TXQOS3PKTS */
    NULL,    /* TXQOSOCTETS */
    NULL,    /* TXQOSPKTS */
    NULL,    /* TXQPKTQ0 */
    NULL,    /* TXQPKTQ1 */
    NULL,    /* TXQPKTQ2 */
    NULL,    /* TXQPKTQ3 */
    NULL,    /* TXQPKTQ4 */
    NULL,    /* TXQPKTQ5 */
    NULL,    /* TXQQ0OCTETS */
    NULL,    /* TXQQ0PACKET */
    NULL,    /* TXQQ1OCTETS */
    NULL,    /* TXQQ1PACKET */
    NULL,    /* TXQQ2OCTETS */
    NULL,    /* TXQQ2PACKET */
    NULL,    /* TXQQ3OCTETS */
    NULL,    /* TXQQ3PACKET */
    NULL,    /* TXQQ4OCTETS */
    NULL,    /* TXQQ4PACKET */
    NULL,    /* TXQQ5OCTETS */
    NULL,    /* TXQQ5PACKET */
    NULL,    /* TXQQ6OCTETS */
    NULL,    /* TXQQ6PACKET */
    NULL,    /* TXQQ7OCTETS */
    NULL,    /* TXQQ7PACKET */
    NULL,    /* TXQQSEL0CONGESTIONDROP */
    NULL,    /* TXQQSEL1CONGESTIONDROP */
    NULL,    /* TXQ_BACKPRESSURE_GE0_CTL */
    NULL,    /* TXQ_BACKPRESSURE_GE1_CTL */
    NULL,    /* TXQ_BACKPRESSURE_GE2_CTL */
    NULL,    /* TXQ_BACKPRESSURE_GE3_CTL */
    NULL,    /* TXQ_BACKPRESSURE_IMP_CTL */
    NULL,    /* TXQ_DROP_CNT_COS_SELECT_0 */
    NULL,    /* TXQ_DROP_CNT_COS_SELECT_1 */
    &soc_robo_reg_list[SOC_REG_INT_TXQ_FLUSH_MODEr_ROBO],
    NULL,    /* TXQ_HYST_A_COUNT */
    NULL,    /* TXQ_HYST_B_COUNT */
    NULL,    /* TXQ_Q0_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q0_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q0_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q1_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q1_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q1_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q2_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q2_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q2_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q3_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q3_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q3_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q4_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q4_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q4_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q5_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q5_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q5_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q6_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q6_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q6_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q7_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q7_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q7_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_WEIGHT_QUOTA_SZ */
    NULL,    /* TXSINGLECOLLISION */
    NULL,    /* TXSINGLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_TXUNICASTPKTS_BCM5396_A0r_ROBO],
    NULL,    /* TX_EQZ_COEF */
    NULL,    /* TX_JUMBO_PACKET_COUNTER */
    NULL,    /* TX_PAUSE_PASS */
    NULL,    /* UDF_0_A_0_8 */
    NULL,    /* UDF_0_B_0_8 */
    NULL,    /* UDF_0_C_0_8 */
    NULL,    /* UDF_0_D_0_11 */
    NULL,    /* UDF_1_A_0_8 */
    NULL,    /* UDF_1_B_0_8 */
    NULL,    /* UDF_1_C_0_8 */
    NULL,    /* UDF_2_A_0_8 */
    NULL,    /* UDF_2_B_0_8 */
    NULL,    /* UDF_2_C_0_8 */
    NULL,    /* UDF_OFFSET0_P */
    NULL,    /* UDF_OFFSET0_P8 */
    NULL,    /* UDF_OFFSET2_P */
    NULL,    /* UDF_OFFSET3_P */
    NULL,    /* UDF_OFFSET4_EXP */
    NULL,    /* UDF_OFFSET4_GP */
    NULL,    /* UDF_OFFSET4_IMP */
    NULL,    /* UDF_OFFSET4_P */
    NULL,    /* UDF_OFFSET4_P8 */
    NULL,    /* UDF_OFFSET5_P */
    NULL,    /* UDF_OFFSET5_P8 */
    NULL,    /* ULF_DROP_MAP */
    &soc_robo_reg_list[SOC_REG_INT_ULF_FORWARD_MAPr_ROBO],
    NULL,    /* VID_RANGE_CHECKER */
    NULL,    /* VLAN2VLAN_CTL */
    NULL,    /* VLAN_BYPASS_CTL */
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL0_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL1_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL2_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL3_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL4_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL5_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL6r_ROBO],
    NULL,    /* VLAN_GLOBAL_CTL */
    NULL,    /* VLAN_MAC_ADDR_INDX */
    NULL,    /* VLAN_MAC_CTRL */
    NULL,    /* VLAN_MAC_HASHSEL */
    NULL,    /* VLAN_MAC_TBL_ACS */
    NULL,    /* VLAN_MAC_TBL_DATA */
    NULL,    /* VLAN_MULTI_PORT_ADDR_CTL */
    &soc_robo_reg_list[SOC_REG_INT_VLAN_REMAP_BCM5396_A0r_ROBO],
    NULL,    /* VREG_UNLOCK */
    NULL,    /* WAN_PORT_SEL */
    NULL,    /* WAN_SLEEP_TIMER */
    NULL,    /* WATCH_DOG_CTRL */
    NULL,    /* WATCH_DOG_RPT1 */
    NULL,    /* WATCH_DOG_RPT2 */
    NULL,    /* WATCH_DOG_RPT3 */
    NULL,    /* X1K_ANADV */
    NULL,    /* X1K_ANEXP */
    NULL,    /* X1K_ANLPA */
    NULL,    /* X1K_ANNXP */
    NULL,    /* X1K_BER_CRC_RXCNT */
    NULL,    /* X1K_BRCMTST */
    NULL,    /* X1K_CTL1 */
    NULL,    /* X1K_CTL2 */
    NULL,    /* X1K_CTL3 */
    NULL,    /* X1K_CTL4 */
    NULL,    /* X1K_EXT_MIISTS */
    NULL,    /* X1K_FORCE_TXD1 */
    NULL,    /* X1K_FORCE_TXD2 */
    NULL,    /* X1K_LPNXP */
    NULL,    /* X1K_MIICTL */
    NULL,    /* X1K_MIISTS */
    NULL,    /* X1K_PATT_GEN_CTL */
    NULL,    /* X1K_PATT_GEN_STS */
    NULL,    /* X1K_PHYIDH */
    NULL,    /* X1K_PHYIDL */
    NULL,    /* X1K_PRBS_CTL */
    NULL,    /* X1K_PRBS_STS */
    NULL,    /* X1K_STS1 */
    NULL,    /* X1K_STS2 */
    NULL,    /* X1K_STS3 */
    NULL,    /* X1K_TST_MOD */
    NULL,    /* XOFF_PORT_HISTORY */
    NULL     /* XOFF_TRIG_PORT_CTRL */
};

static soc_mem_info_t *soc_memories_bcm5396_a0[] = {
    NULL,    /* CFP_ACT_POL */
    NULL,    /* CFP_DATA */
    NULL,    /* CFP_DATA_MASK */
    NULL,    /* CFP_MASK */
    NULL,    /* CFP_METER */
    NULL,    /* CFP_RATE_METER */
    NULL,    /* CFP_STAT */
    NULL,    /* CFP_STAT_IB */
    NULL,    /* CFP_STAT_OB */
    NULL,    /* CFP_TCAM_CHAIN_MASK */
    NULL,    /* CFP_TCAM_CHAIN_SC */
    NULL,    /* CFP_TCAM_IPV4_MASK */
    NULL,    /* CFP_TCAM_IPV4_S0 */
    NULL,    /* CFP_TCAM_IPV4_S1 */
    NULL,    /* CFP_TCAM_IPV4_S2 */
    NULL,    /* CFP_TCAM_IPV4_S0_MASK */
    NULL,    /* CFP_TCAM_IPV4_S1_MASK */
    NULL,    /* CFP_TCAM_IPV4_S2_MASK */
    NULL,    /* CFP_TCAM_IPV4_SC */
    NULL,    /* CFP_TCAM_IPV6_MASK */
    NULL,    /* CFP_TCAM_IPV6_S0 */
    NULL,    /* CFP_TCAM_IPV6_S1 */
    NULL,    /* CFP_TCAM_IPV6_S2 */
    NULL,    /* CFP_TCAM_IPV6_S0_MASK */
    NULL,    /* CFP_TCAM_IPV6_S1_MASK */
    NULL,    /* CFP_TCAM_IPV6_S2_MASK */
    NULL,    /* CFP_TCAM_IPV6_SC */
    NULL,    /* CFP_TCAM_MASK */
    NULL,    /* CFP_TCAM_NONIP_MASK */
    NULL,    /* CFP_TCAM_NONIP_SC */
    NULL,    /* CFP_TCAM_S0 */
    NULL,    /* CFP_TCAM_S1 */
    NULL,    /* CFP_TCAM_S2 */
    NULL,    /* CFP_TCAM_S3 */
    NULL,    /* CFP_TCAM_S4 */
    NULL,    /* CFP_TCAM_S5 */
    NULL,    /* CFP_TCAM_SC */
    NULL,    /* DPTC2PCP */
    NULL,    /* DSCPECN2TCDP */
    NULL,    /* EGRESS_VID_REMARK */
    NULL,    /* ERC_PORT */
    NULL,    /* EVM_ACT */
    NULL,    /* EVM_KEY_DATA */
    NULL,    /* EVM_KEY_DATA_MASK */
    NULL,    /* EVM_KEY_MASK */
    NULL,    /* FLOW2VLAN */
    NULL,    /* GEN_MEMORY */
    NULL,    /* INT_8051_RAM */
    NULL,    /* INT_8051_ROM */
    NULL,    /* IRC_PORT */
    NULL,    /* IVM_ACT */
    NULL,    /* IVM_KEY_DATA_0 */
    NULL,    /* IVM_KEY_DATA_1 */
    NULL,    /* IVM_KEY_DATA_2 */
    NULL,    /* IVM_KEY_DATA_3 */
    NULL,    /* IVM_KEY_DATA_MASK */
    NULL,    /* IVM_KEY_MASK_0 */
    NULL,    /* IVM_KEY_MASK_1 */
    NULL,    /* IVM_KEY_MASK_2 */
    NULL,    /* IVM_KEY_MASK_3 */
    &soc_robo_mem_list[SOC_MEM_INT_L2_ARL_BCM5396_A0m_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_L2_ARL_SW_BCM5396_A0m_ROBO],
    NULL,    /* L2_MARL */
    &soc_robo_mem_list[SOC_MEM_INT_L2_MARL_SW_BCM5396_A0m_ROBO],
    NULL,    /* MAC2VLAN */
    NULL,    /* MARL_PBMP */
    NULL,    /* MCAST_VPORT_MAP */
    &soc_robo_mem_list[SOC_MEM_INT_MSPT_TAB_BCM5396_A0m_ROBO],
    NULL,    /* PCP2DPTC */
    NULL,    /* PORT_MASK */
    NULL,    /* PROTOCOL2VLAN */
    NULL,    /* SA_LRN_CNT */
    NULL,    /* STSEC_COUNTER0 */
    NULL,    /* STSEC_COUNTER1 */
    NULL,    /* STSEC_COUNTER2 */
    NULL,    /* STSEC_MAC0 */
    NULL,    /* STSEC_MAC1 */
    NULL,    /* STSEC_MAC2 */
    NULL,    /* TCDP2DSCPECN */
    NULL,    /* VLAN2VLAN */
    &soc_robo_mem_list[SOC_MEM_INT_VLAN_1Q_BCM5396_A0m_ROBO],
    NULL     /* VPORT_VID_MAP */
};

/*
 * Packet Statistics Counter Map for bcm5396_a0
 *
 * NOTE: soc_attach verifies this map is correct and prints warnings if
 * not. The map should contain only registers with a single field named
 * COUNT, and all such registers should be in the map.
 *
 * The soc_counter_map array is a list of counter registers in the order
 * found in the internal address map and counter DMA buffer.
 * counter_map[0 to NUM_COUNTER-1] corresponds to internal addresses
 * COUNTER_REG_FIRST through COUNTER_REG_LAST.
 *
 * This map structure, contents, and size are exposed only to provide a
 * convenient way to loop through all available counters.
 */

static soc_ctr_ref_t _ge_counters_bcm5396_a0[] = {
    {INDEX(    RXDROPPKTSr), 0}, /* 0x008 */
    {INDEX( RXUNICASTPKTSr), 0}, /* 0x00c */
    {INDEX(RXOVERSIZEPKTSr), 0}, /* 0x00c */
    {INDEX(      TXOCTETSr), 0}, /* 0x004 */
    {INDEX(   TXPAUSEPKTSr), 0}, /* 0x004 */
    {INDEX( TXUNICASTPKTSr), 0}, /* 0x004 */
    {INDEX(    TXDROPPKTSr), 0}, /* 0x000 */
    {INDEX(   RXFCSERRORSr), 0}, /* 0x008 */
    {INDEX(    RXGOODPKTSr), 0}, /* 0x008 */
    {INDEX(    TXGOODPKTSr), 0}, /* 0x000 */
    {INDEX(  TXCOLLISIONSr), 0}, /* 0x000 */
    {INDEX(  RXGOODOCTETSr), 0}, /* 0x00c */
};

/*
 * The array to put into chip parameters.
 * This array is indexed by SOC_CTR_TYPE_xxx (soc_ctr_types_t)
 */
static soc_cmap_t soc_counter_maps_bcm5396_a0[SOC_CTR_NUM_TYPES] = {
    {NULL, 0},                        /* FE */
    {_ge_counters_bcm5396_a0, 12},    /* GE */
    {NULL, 0},                        /* GFE */
    {NULL, 0},                        /* HG */
    {NULL, 0},                         /* XE */
    {NULL, 0},                        /* CPU */
    {NULL, 0},                         /* RX */
    {NULL, 0}                         /* TX */
};

static soc_block_info_t soc_blocks_bcm5396_a0[] = {
	{ SOC_BLK_CPIC,	0,	0,	2	},	/* 0 C0 */
	{ SOC_BLK_EXP,	0,	0,	3	},	/* 1 E0 */
	{ SOC_BLK_GPIC,	0,	0,	0	},	/* 2 G0 */
	{ SOC_BLK_GPIC,	1,	0,	1	},	/* 3 G1 */
	{ SOC_BLK_SPI,	0,	0,	4	},	/* 4 S0 */
	{ SOC_BLK_SYS,	0,	0,	5	},	/* 5 S0 */
	{ -1,		-1,	-1,	-1	}	/* end */
};

static soc_port_info_t soc_ports_bcm5396_a0[] = {
	{ 2,	0	},	/* 0 G0.0 */
	{ 2,	1	},	/* 1 G0.1 */
	{ 2,	2	},	/* 2 G0.2 */
	{ 2,	3	},	/* 3 G0.3 */
	{ 2,	4	},	/* 4 G0.4 */
	{ 2,	5	},	/* 5 G0.5 */
	{ 2,	6	},	/* 6 G0.6 */
	{ 2,	7	},	/* 7 G0.7 */
	{ 3,	0	},	/* 8 G1.0 */
	{ 3,	1	},	/* 9 G1.1 */
	{ 3,	2	},	/* 10 G1.2 */
	{ 3,	3	},	/* 11 G1.3 */
	{ 3,	4	},	/* 12 G1.4 */
	{ 3,	5	},	/* 13 G1.5 */
	{ 3,	6	},	/* 14 G1.6 */
	{ 3,	7	},	/* 15 G1.7 */
	{ 0,	0	},	/* 16 C0.0 */
	{ -1,	-1	}	/* end */
};

/* Forward declaration of init function */
static void chip_init_bcm5396_a0(void);

soc_driver_t soc_driver_bcm5396_a0 = {
	/* type           */	SOC_CHIP_BCM5396_A0,
	/* chip_string    */	"dino16",
	/* origin         */	"/projects/ntsw-sw/btcswcvs/taiwan/regs/bcm5396_a0",
	/* pci_vendor     */	BROADCOM_VENDOR_ID,
	/* pci_device     */	BCM5396_DEVICE_ID,
	/* pci_revision   */	BCM5396_A0_REV_ID,
	/* num_cos        */	4,
	/* reg_info       */	soc_registers_bcm5396_a0,
	/* mem_info       */	soc_memories_bcm5396_a0,
	/* soc_mem_t      */	NULL,
	/* block_info     */	soc_blocks_bcm5396_a0,
	/* port_info      */	soc_ports_bcm5396_a0,
	/* counter_maps   */	soc_counter_maps_bcm5396_a0,
	/* features       */	soc_features_bcm5396_a0,
	/* init           */	chip_init_bcm5396_a0,
	/* services       */	&drv_bcm5396_services
};  /* soc_driver */

/* Chip specific bottom matter from memory file */

/****************************************************************
 *
 * Function:    chip_init_bcm5396_a0
 * Purpose:
 *     Initialize software internals for bcm5396_a0 device:
 *         Initialize null memories
 * Parameters:  void
 * Returns:     void
 *
 ****************************************************************/
static void
chip_init_bcm5396_a0(void)
{

}

/* End of chip specific bottom matter */

#endif /* BCM_5396_A0 */
