/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: bcm53118_a0.c 1.34 Broadcom SDK $
 * $Copyright: Copyright 2011 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 * File:	bcm53118_a0.c
 * Purpose:	bcm53118_a0 chip specific information (register, memories, etc)
 */


#include <sal/core/libc.h>
#include <soc/defs.h>
#include <soc/mem.h>
#include <soc/mcm/robo/memregs.h>
#include <soc/mcm/robo/driver.h>
#include <soc/mcm/robo/allenum.h>
#include <soc/mcm/robo/intenum.h>

#if defined(BCM_53118_A0)
#include <soc/robo/bcm53118_service.h>

/* Chip specific top matter from memory file */

/* These are the null memory descriptions for BCM53118_A0 */

/* End of chip specific top matter */

static soc_reg_info_t *soc_registers_bcm53118_a0[] = {
    NULL,    /* ACTLSTS */
    NULL,    /* ACT_POL_DATA */
    NULL,    /* ACT_POL_DATA0 */
    NULL,    /* ACT_POL_DATA1 */
    NULL,    /* AEGSTS */
    NULL,    /* AGEOUT_CTL */
    NULL,    /* AGEOUT_EN_VID */
    NULL,    /* AMODE2 */
    NULL,    /* AMPHY */
    NULL,    /* ANADV */
    NULL,    /* ANADV_EXT_P5 */
    NULL,    /* ANEXP */
    NULL,    /* ANEXP_EXT_P5 */
    NULL,    /* ANLPA */
    NULL,    /* ANLPAR */
    NULL,    /* ANLPA_EXT_P5 */
    NULL,    /* ANNXP */
    NULL,    /* ANNXP_EXT_P5 */
    NULL,    /* ARLA_ENTRY */
    NULL,    /* ARLA_ENTRY0 */
    NULL,    /* ARLA_ENTRY1 */
    NULL,    /* ARLA_ENTRY_0 */
    NULL,    /* ARLA_ENTRY_1 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_FWD_ENTRY0_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_FWD_ENTRY1_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_FWD_ENTRY2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_FWD_ENTRY3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_MACr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_MACVID_ENTRY0_BCM5398_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_MACVID_ENTRY1_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_MACVID_ENTRY2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_MACVID_ENTRY3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_RWCTL_BCM5396_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_ADR_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_CTL_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_0_BCM5395_A0r_ROBO],
    NULL,    /* ARLA_SRCH_RSLT_0 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_1_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_MACVID_0_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_SRCH_RSLT_MACVID_1_BCM5395_A0r_ROBO],
    NULL,    /* ARLA_SRCH_RSLT_MACVID */
    NULL,    /* ARLA_SRCH_RSLT_MACVID_0 */
    NULL,    /* ARLA_SRCH_RSLT_MACVID_1 */
    NULL,    /* ARLA_SRCH_RSLT_VID */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VIDr_ROBO],
    NULL,    /* ARLA_VID_ENTRY */
    NULL,    /* ARLA_VID_ENTRY0 */
    NULL,    /* ARLA_VID_ENTRY1 */
    NULL,    /* ARLA_VID_ENTRY_0 */
    NULL,    /* ARLA_VID_ENTRY_1 */
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VTBL_ADDR_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VTBL_ENTRY_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_ARLA_VTBL_RWCTRL_BCM5395_A0r_ROBO],
    NULL,    /* ARL_SPAREREG0 */
    NULL,    /* ARL_SPAREREG1 */
    NULL,    /* ARL_SPAREREG2 */
    NULL,    /* ARL_SPAREREG3 */
    NULL,    /* ASTSSUM */
    NULL,    /* AUTH_8021X_CTL1 */
    NULL,    /* AUTH_8021X_CTL2 */
    NULL,    /* AUX_CONTROL_STATUS */
    NULL,    /* AUX_CONTROL_STATUS_EXT_P5 */
    NULL,    /* AUX_MODE */
    NULL,    /* AUX_MODE2 */
    NULL,    /* AUX_MODE2_EXT_P5 */
    NULL,    /* AUX_MODE_EXT_P5 */
    NULL,    /* AUX_MULTI_PHY */
    NULL,    /* AUX_MULTI_PHY_EXT_P5 */
    NULL,    /* AUX_STATUS_SUMMARY */
    NULL,    /* AUX_STATUS_SUMMARY_EXT_P5 */
    NULL,    /* AVB_AV_EN_CTRL */
    NULL,    /* AVB_C4_BW_CNTL */
    NULL,    /* AVB_C5_BW_CNTL */
    NULL,    /* AVB_EGRESS_TM_STAMP */
    NULL,    /* AVB_EGRESS_TS_PORTMAP */
    NULL,    /* AVB_EGRESS_TS_TM_STAMP */
    NULL,    /* AVB_LNK_STATUS */
    NULL,    /* AVB_MAX_AV_PKT_SZ */
    NULL,    /* AVB_SLOT_ADJ */
    NULL,    /* AVB_SLOT_TICK_CNTR */
    NULL,    /* AVB_TM_ADJ */
    NULL,    /* AVB_TM_BASE */
    NULL,    /* B100X_AUX_CONTROL */
    NULL,    /* B100X_AUX_CONTROL_EXT_P5 */
    NULL,    /* B100X_AUX_STATUS */
    NULL,    /* B100X_AUX_STATUS_EXT_P5 */
    NULL,    /* B100X_DISCONNECT_COUNTER */
    NULL,    /* B100X_DISCONNECT_COUNTER_EXT_P5 */
    NULL,    /* B100X_FALSE_CARRIER_SENSE_COUNTER */
    NULL,    /* B100X_FALSE_CARRIER_SENSE_COUNTER_EXT_P5 */
    NULL,    /* B100X_RX_ERROR_COUNTER */
    NULL,    /* B100X_RX_ERROR_COUNTER_EXT_P5 */
    NULL,    /* B10T_AUX_STATUS */
    NULL,    /* B10T_AUX_STATUS_EXT_P5 */
    NULL,    /* BCAST_FWD_MAP */
    &soc_robo_reg_list[SOC_REG_INT_BC_SUP_PKTDROP_CNT_IMPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_BC_SUP_PKTDROP_CNT_P_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_BC_SUP_RATECTRL_IMPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_BC_SUP_RATECTRL_P_BCM53118_A0r_ROBO],
    NULL,    /* BG_SEL */
    NULL,    /* BIST_STS */
    &soc_robo_reg_list[SOC_REG_INT_BIST_STS0_BCM53118_A0r_ROBO],
    NULL,    /* BIST_STS1 */
    NULL,    /* BONDING_PAD */
    &soc_robo_reg_list[SOC_REG_INT_BONDING_PAD_STATUS_BCM53118_A0r_ROBO],
    NULL,    /* BOND_DIRECT_PIN */
    &soc_robo_reg_list[SOC_REG_INT_BPDU_MCADDRr_ROBO],
    NULL,    /* BRCMTST */
    &soc_robo_reg_list[SOC_REG_INT_BRCM_HDR_CTRL_BCM53118_A0r_ROBO],
    NULL,    /* BRCM_TAG_CTRL */
    NULL,    /* BROADCOM_TEST */
    NULL,    /* BROADCOM_TEST_EXT_P5 */
    NULL,    /* BUFCON_MEMADR */
    NULL,    /* BUFCON_MEMDAT0 */
    NULL,    /* BUFCON_MEMDAT1 */
    &soc_robo_reg_list[SOC_REG_INT_C4_WEIGHTr_ROBO],
    NULL,    /* CFP_ACC */
    NULL,    /* CFP_CTL_REG */
    NULL,    /* CFP_DATA */
    NULL,    /* CFP_EN_CTRL */
    NULL,    /* CFP_GLOBAL_CTL */
    NULL,    /* CFP_MASK */
    NULL,    /* CFP_RC */
    NULL,    /* CFP_TEST */
    NULL,    /* CFP_UDF_0_A */
    NULL,    /* CFP_UDF_0_B08 */
    NULL,    /* CFP_UDF_0_C */
    NULL,    /* CFP_UDF_1_A */
    NULL,    /* CFP_UDF_1_C */
    NULL,    /* CFP_UDF_2_A */
    NULL,    /* CFP_UDF_2_B */
    NULL,    /* CFP_UDF_2_C */
    NULL,    /* CFP_UDF_3_D */
    NULL,    /* CFP_UDF_A */
    NULL,    /* CFP_UDF_B */
    NULL,    /* CFP_UDF_C */
    NULL,    /* CFP_UDF_D */
    NULL,    /* CFP_UNLCK */
    NULL,    /* CHIP0_PORT_AGE */
    &soc_robo_reg_list[SOC_REG_INT_CHIP_REVID_BCM5396_A0r_ROBO],
    NULL,    /* CHIP_RST_CTL */
    &soc_robo_reg_list[SOC_REG_INT_CLASS_PCPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CLKSETr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_COMM_IRC_CON_BCM5395_A0r_ROBO],
    NULL,    /* COS_VALUE_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_CPU2COS_MAP_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CPU_ADDRESSr_ROBO],
    NULL,    /* CPU_DATA1_SHARE */
    NULL,    /* CPU_DATA_SHARE */
    &soc_robo_reg_list[SOC_REG_INT_CPU_MEM_RD_ENr_ROBO],
    NULL,    /* CPU_OTP_ADDR */
    NULL,    /* CPU_OTP_CTL */
    NULL,    /* CPU_OTP_RD_DATA */
    NULL,    /* CPU_OTP_STATUS */
    NULL,    /* CPU_OTP_WR_DATA */
    &soc_robo_reg_list[SOC_REG_INT_CPU_RAM_ROM_SELr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_CPU_READ_DATAr_ROBO],
    NULL,    /* CPU_RESOURCE_ARBITER */
    NULL,    /* CRC16_GP */
    NULL,    /* CTRL_REG */
    NULL,    /* DEBUG_CONGESTION */
    &soc_robo_reg_list[SOC_REG_INT_DEBUG_REG_BCM53115_A0r_ROBO],
    NULL,    /* DEBUG_STS */
    &soc_robo_reg_list[SOC_REG_INT_DEFAULT_1Q_TAG_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_DEFAULT_1Q_TAG_IMP_BCM53118_A0r_ROBO],
    NULL,    /* DEF_PORT_QOS_CFG */
    &soc_robo_reg_list[SOC_REG_INT_DF_TIMER_BCM5395_A0r_ROBO],
    NULL,    /* DIAGNOSIS */
    &soc_robo_reg_list[SOC_REG_INT_DIRECT_CTRL_PIN_BCM53118_A0r_ROBO],
    NULL,    /* DIRECT_INPUT_CTRL_VALUE */
    &soc_robo_reg_list[SOC_REG_INT_DIS_LEARNr_ROBO],
    NULL,    /* DMA_CTRL */
    NULL,    /* DMA_LPB_BUF_ADDR */
    NULL,    /* DMA_LPB_BUF_SIZE */
    NULL,    /* DOS_ATTACK_FILTER_DROP_CTL */
    NULL,    /* DOS_ATTACK_FILTER_EVENT */
    &soc_robo_reg_list[SOC_REG_INT_DOS_CTRL_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_DOS_DIS_LRN_REG_BCM53115_A0r_ROBO],
    NULL,    /* DOU_TAG_TPID */
    NULL,    /* DP_CTRL */
    NULL,    /* DSCP2TC_DP_MAP0 */
    NULL,    /* DSCP2TC_DP_MAP1 */
    NULL,    /* DSCP2TC_DP_MAP2 */
    NULL,    /* DSCP2TC_DP_MAP3 */
    NULL,    /* DSCP2TC_DP_MAP4 */
    NULL,    /* DSCP2TC_DP_MAP5 */
    NULL,    /* DSCP2TC_DP_MAP6 */
    NULL,    /* DSCP2TC_DP_MAP7 */
    NULL,    /* DTAG_GLO_CTL */
    &soc_robo_reg_list[SOC_REG_INT_DOU_TAG_TPIDr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_DUPSTS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EAP_DIP_BCM5398_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EAP_GLO_CON_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EAP_MULTI_ADDR_CTRLr_ROBO],
    NULL,    /* EAP_PORT_CTL */
    &soc_robo_reg_list[SOC_REG_INT_EAV_LNK_STATUS_BCM53118_A0r_ROBO],
    NULL,    /* EEE_DEBUG */
    NULL,    /* EEE_EN_CTRL */
    NULL,    /* EEE_GLB_CONG_TH */
    NULL,    /* EEE_LINK_DLY_TIMER */
    NULL,    /* EEE_LPI_ASSERT */
    NULL,    /* EEE_LPI_DURATION */
    NULL,    /* EEE_LPI_EVENT */
    NULL,    /* EEE_LPI_INDICATE */
    NULL,    /* EEE_MIN_LP_TIMER_G */
    NULL,    /* EEE_MIN_LP_TIMER_G_IMP */
    NULL,    /* EEE_MIN_LP_TIMER_H */
    NULL,    /* EEE_MIN_LP_TIMER_H_IMP */
    NULL,    /* EEE_PHY_CTRL */
    NULL,    /* EEE_PIPELINE_TIMER */
    NULL,    /* EEE_RX_IDLE_SYMBOL */
    NULL,    /* EEE_SLEEP_TIMER_G */
    NULL,    /* EEE_SLEEP_TIMER_G_IMP */
    NULL,    /* EEE_SLEEP_TIMER_H */
    NULL,    /* EEE_SLEEP_TIMER_H_IMP */
    NULL,    /* EEE_STATE */
    NULL,    /* EEE_TXQ_CONG_TH */
    NULL,    /* EEE_WAKE_TIMER_G */
    NULL,    /* EEE_WAKE_TIMER_G_IMP */
    NULL,    /* EEE_WAKE_TIMER_H */
    NULL,    /* EEE_WAKE_TIMER_H_IMP */
    &soc_robo_reg_list[SOC_REG_INT_EGMIRCTL_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EGMIRDIV_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_EGMIRMAC_BCM5389_A0r_ROBO],
    NULL,    /* EGRESS_NAVB_PKT_TC2PCP_MAP */
    NULL,    /* EGRESS_NAVB_PKT_TC2PCP_MAP_IMP */
    &soc_robo_reg_list[SOC_REG_INT_EGRESS_NRESE_PKT_TC2PCP_MAP_BCM53118_A0r_ROBO],
    NULL,    /* EGRESS_NRESE_PKT_TC2PCP_MAP_8 */
    NULL,    /* EGRESS_NRESE_PKT_TC2PCP_MAP_IMP */
    NULL,    /* EGRESS_RMON */
    NULL,    /* EGRESS_SFLOW */
    NULL,    /* EGRESS_VID_RMK_TBL_ACS */
    NULL,    /* EGRESS_VID_RMK_TBL_DATA */
    NULL,    /* EN_IMP_CONG_REMAP */
    NULL,    /* EN_IMP_HIGH_RATE */
    NULL,    /* EN_TOTAL_MC_DROP_IMP */
    NULL,    /* EQZ_CTRL */
    NULL,    /* EXP_PORT */
    NULL,    /* EXTPHY_SCAN_CTL */
    NULL,    /* EXT_ACTLSTS */
    NULL,    /* EXT_AEGSTS */
    NULL,    /* EXT_AMODE2 */
    NULL,    /* EXT_AMPHY */
    NULL,    /* EXT_ANADV */
    NULL,    /* EXT_ANEXP */
    NULL,    /* EXT_ANLPA */
    NULL,    /* EXT_ANNXP */
    NULL,    /* EXT_ASTSSUM */
    NULL,    /* EXT_BRCMTST */
    NULL,    /* EXT_HNDRD_ACTL */
    NULL,    /* EXT_HNDRD_ASTS */
    NULL,    /* EXT_HNDRD_FCSCNT */
    NULL,    /* EXT_HNDRD_RECNT */
    NULL,    /* EXT_LPNXP */
    NULL,    /* EXT_MIICTL */
    NULL,    /* EXT_MIISTS */
    NULL,    /* EXT_PHYIDH */
    NULL,    /* EXT_PHYIDL */
    NULL,    /* E_ACTLSTS */
    NULL,    /* E_AEGSTS */
    NULL,    /* E_AMODE2 */
    NULL,    /* E_AMPHY */
    NULL,    /* E_ANADV */
    NULL,    /* E_ANEXP */
    NULL,    /* E_ANLPA */
    NULL,    /* E_ANNXP */
    NULL,    /* E_ASTSSUM */
    NULL,    /* E_BRCMTST */
    NULL,    /* E_HNDRD_ACTL */
    NULL,    /* E_HNDRD_ASTS */
    NULL,    /* E_HNDRD_FCSCNT */
    NULL,    /* E_HNDRD_RECNT */
    NULL,    /* E_LPNXP */
    NULL,    /* E_MIICTL */
    NULL,    /* E_MIISTS */
    NULL,    /* E_PHYIDH */
    NULL,    /* E_PHYIDL */
    NULL,    /* FAST_AGE_CTL */
    &soc_robo_reg_list[SOC_REG_INT_FAST_AGE_CTRLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FAST_AGE_PORTr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FAST_AGING_VID_BCM5398_A0r_ROBO],
    NULL,    /* FAST_AGING_CTL */
    NULL,    /* FAST_AGING_PORT */
    NULL,    /* FAST_AGING_VID */
    NULL,    /* FCON_BCST_TH_CTRL */
    NULL,    /* FCON_DIAG_CTRL */
    NULL,    /* FCON_DLF_TH_CTRL */
    NULL,    /* FCON_FLOWCON_STATUS0 */
    NULL,    /* FCON_FLOWCON_STATUS1 */
    NULL,    /* FCON_FLOWCON_STATUS2 */
    NULL,    /* FCON_FLOWCON_STATUS3 */
    NULL,    /* FCON_FLOWCON_STATUS4 */
    NULL,    /* FCON_FLOWCON_STATUS5 */
    NULL,    /* FCON_FLOWCON_STATUS6 */
    NULL,    /* FCON_FLOWCON_STATUS7 */
    NULL,    /* FCON_FLOWCON_STATUS8 */
    NULL,    /* FCON_FLOWCON_STATUS9 */
    NULL,    /* FCON_FLOWCON_STATUS10 */
    NULL,    /* FCON_FLOWCON_STATUS11 */
    NULL,    /* FCON_FLOWCON_STATUS12 */
    NULL,    /* FCON_FLOWCON_STATUS13 */
    NULL,    /* FCON_FLOWMIX */
    NULL,    /* FCON_GLOB_TH_CTRL_1 */
    NULL,    /* FCON_GLOB_TH_CTRL_2 */
    NULL,    /* FCON_MISC_CTRL */
    NULL,    /* FCON_MISC_TXFLOW_CTRL */
    NULL,    /* FCON_PERQ_TXDROP_CTRL */
    NULL,    /* FCON_Q0_100_TH_CTRL_1 */
    NULL,    /* FCON_Q0_100_TH_CTRL_2 */
    NULL,    /* FCON_Q0_TXDSC_CTRL_3 */
    NULL,    /* FCON_Q1_100_TH_CTRL_1 */
    NULL,    /* FCON_Q1_100_TH_CTRL_2 */
    NULL,    /* FCON_Q1_TXDSC_CTRL_3 */
    NULL,    /* FCON_Q2_100_TH_CTRL_1 */
    NULL,    /* FCON_Q2_100_TH_CTRL_2 */
    NULL,    /* FCON_Q2_TXDSC_CTRL_3 */
    NULL,    /* FCON_Q3_100_TH_CTRL_1 */
    NULL,    /* FCON_Q3_100_TH_CTRL_2 */
    NULL,    /* FCON_Q3_TXDSC_CTRL_3 */
    NULL,    /* FCON_RSRV_BUFNUM */
    NULL,    /* FCON_RXBASE_BUFNUM */
    NULL,    /* FCON_RX_FCON_CTRL */
    NULL,    /* FCON_SPARE0 */
    NULL,    /* FCON_SPARE1 */
    NULL,    /* FCON_SPARE2 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL0 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL1 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL2 */
    NULL,    /* FCON_STRICT_HIQ_PRE_CTRL3 */
    NULL,    /* FCON_TXQ_FULL_TH */
    &soc_robo_reg_list[SOC_REG_INT_FC_CHIP_INFO_BCM5398_A0r_ROBO],
    NULL,    /* FC_CHIP_INFO_1 */
    NULL,    /* FC_CHIP_INFO_2 */
    NULL,    /* FC_CONG_BUF_ERR_HIS */
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP01r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP8_BCM5395_A0r_ROBO],
    NULL,    /* FC_CONG_PORTMAP16 */
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP23r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP45r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_CONG_PORTMAP67r_ROBO],
    NULL,    /* FC_CONG_PORTMAP89 */
    NULL,    /* FC_CONG_PORTMAP1011 */
    NULL,    /* FC_CONG_PORTMAP1213 */
    NULL,    /* FC_CONG_PORTMAP1415 */
    &soc_robo_reg_list[SOC_REG_INT_FC_DIAG_CTRL_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_GIGA_INFO_BCM5398_A0r_ROBO],
    NULL,    /* FC_GIGA_INFO_1 */
    NULL,    /* FC_GIGA_INFO_2 */
    NULL,    /* FC_IMP_THRESH_ADJUST_Q */
    &soc_robo_reg_list[SOC_REG_INT_FC_MCAST_DROP_CTRLr_ROBO],
    NULL,    /* FC_MCAST_DROP_CTRL_1 */
    NULL,    /* FC_MCAST_DROP_CTRL_2 */
    &soc_robo_reg_list[SOC_REG_INT_FC_MON_TXQ_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PAUSE_DROP_CTRL_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PAUSE_HISr_ROBO],
    NULL,    /* FC_PAUSE_HIS_1 */
    NULL,    /* FC_PAUSE_HIS_2 */
    &soc_robo_reg_list[SOC_REG_INT_FC_PEAK_RXBYTE_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PEAK_TOTAL_USED_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PEAK_TXQ_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_PEAK_TXQ_45_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_Q45_CONG_PORTMAP_8r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_Q45_CONG_PORTMAP_0123r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_Q45_CONG_PORTMAP_4567r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RXBUF_ERR_HISr_ROBO],
    NULL,    /* FC_RXBUF_ERR_HIS_1 */
    NULL,    /* FC_RXBUF_ERR_HIS_2 */
    &soc_robo_reg_list[SOC_REG_INT_FC_RXPAUSE_HISr_ROBO],
    NULL,    /* FC_RXPAUSE_HIS_1 */
    NULL,    /* FC_RXPAUSE_HIS_2 */
    &soc_robo_reg_list[SOC_REG_INT_FC_RX_HYST_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RX_MAX_PTR_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RX_RSRV_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_RX_RUNOFF_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_SPARE_REG_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_DROP_Q_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_DROP_Q45_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_DROP_Q_IMP_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_DROP_Q_WANr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_HYST_Q_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_HYST_Q45_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_HYST_Q_IMP_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_HYST_Q_WANr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_PAUSE_Q_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_PAUSE_Q45_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_PAUSE_Q_IMP_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_PAUSE_Q_WANr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_TH_RSRV_Q_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TOTAL_USED_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXPAUSE_HISr_ROBO],
    NULL,    /* FC_TXPAUSE_HIS_1 */
    NULL,    /* FC_TXPAUSE_HIS_2 */
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_DROP_Q_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_DROP_Q45_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_DROP_Q_IMP_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_DROP_Q_WANr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_PAUSE_Q_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_PAUSE_Q45_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_PAUSE_Q_IMP_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_PAUSE_Q_WANr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_RSRV_Q_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_RSRV_Q45_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_RSRV_Q_IMP_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_FC_TXQ_TH_RSRV_Q_WAN_BCM53118_A0r_ROBO],
    NULL,    /* FLOW_MON_BUS */
    NULL,    /* FM_MEMADR */
    NULL,    /* FM_MEMDAT0 */
    NULL,    /* FM_MEMDAT1 */
    NULL,    /* FM_MEMDAT2 */
    NULL,    /* FM_MEMDAT3 */
    NULL,    /* FM_SIZE_CTL */
    &soc_robo_reg_list[SOC_REG_INT_FORCE_FRAME_DROPr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_GARLCFG_BCM53118_A0r_ROBO],
    NULL,    /* GENMEM_ADDR */
    NULL,    /* GENMEM_CTL */
    NULL,    /* GENMEM_DATA */
    NULL,    /* GENMEM_DATA0 */
    NULL,    /* GENMEM_DATA1 */
    NULL,    /* GLB_ACTLSTS */
    NULL,    /* GLB_AEGSTS */
    NULL,    /* GLB_AMODE2 */
    NULL,    /* GLB_AMPHY */
    NULL,    /* GLB_ANADV */
    NULL,    /* GLB_ANEXP */
    NULL,    /* GLB_ANLPA */
    NULL,    /* GLB_ANNXP */
    NULL,    /* GLB_ASTSSUM */
    NULL,    /* GLB_BRCMTST */
    NULL,    /* GLB_HNDRD_ACTL */
    NULL,    /* GLB_HNDRD_ASTS */
    NULL,    /* GLB_HNDRD_FCSCNT */
    NULL,    /* GLB_HNDRD_RECNT */
    NULL,    /* GLB_LPNXP */
    NULL,    /* GLB_MIICTL */
    NULL,    /* GLB_MIISTS */
    NULL,    /* GLB_OVERFLOW_DROP_PKT_CNT */
    NULL,    /* GLB_PHYIDH */
    NULL,    /* GLB_PHYIDL */
    NULL,    /* GLB_VLAN_ING_FILTER_CTL */
    NULL,    /* GLOBAL_CONGESTION_CTRL */
    NULL,    /* GLOBAL_TRUNK_CTL */
    &soc_robo_reg_list[SOC_REG_INT_GMNGCFG_BCM53115_A0r_ROBO],
    NULL,    /* GREEN_MODE_DATA */
    NULL,    /* GREEN_MODE_DEBUG */
    NULL,    /* GREEN_MODE_SELECT */
    NULL,    /* GROUP_CTRL */
    NULL,    /* GRPADDR1 */
    NULL,    /* GRPADDR2 */
    &soc_robo_reg_list[SOC_REG_INT_G_ANADV_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_ANADV_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_ANADV_EXT_P5 */
    NULL,    /* G_ANADV_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_ANEXP_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_ANEXP_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_ANEXP_EXT_P5 */
    NULL,    /* G_ANEXP_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_ANLPA_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_ANLPA_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_ANLPA_EXT_P5 */
    NULL,    /* G_ANLPA_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_ANNXP_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_ANNXP_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_ANNXP_EXT_P5 */
    NULL,    /* G_ANNXP_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_AUX_CTLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_AUX_CTL_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_AUX_CTL_EXT_P5 */
    NULL,    /* G_AUX_CTL_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_AUX_STSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_AUX_STS_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_AUX_STS_EXT_P5 */
    NULL,    /* G_AUX_STS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_B1000T_CTL_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_B1000T_CTL_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_B1000T_CTL_EXT_P5 */
    NULL,    /* G_B1000T_CTL_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_B1000T_STS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_B1000T_STS_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_B1000T_STS_EXT_P5 */
    NULL,    /* G_B1000T_STS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_DSP_COEFFICIENTr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_DSP_COEFFICIENT_ADDRr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_DSP_COEFFICIENT_ADDR_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_DSP_COEFFICIENT_ADDR_EXT_P5 */
    NULL,    /* G_DSP_COEFFICIENT_ADDR_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_DSP_COEFFICIENT_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_DSP_COEFFICIENT_EXT_P5 */
    NULL,    /* G_DSP_COEFFICIENT_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_EXT_STS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_EXT_STS_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_EXT_STS_EXT_P5 */
    NULL,    /* G_EXT_STS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_FALSE_CARR_CNT_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_FALSE_CARR_CNT_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_FALSE_CARR_CNT_EXT_P5 */
    NULL,    /* G_FALSE_CARR_CNT_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_INTERRUPT_MSKr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_INTERRUPT_MSK_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_INTERRUPT_MSK_EXT_P5 */
    NULL,    /* G_INTERRUPT_MSK_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_INTERRUPT_STSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_INTERRUPT_STS_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_INTERRUPT_STS_EXT_P5 */
    NULL,    /* G_INTERRUPT_STS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_LPNXP_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_LPNXP_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_LPNXP_EXT_P5 */
    NULL,    /* G_LPNXP_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_MASTER_SLAVE_SEEDr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_MASTER_SLAVE_SEED_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_MASTER_SLAVE_SEED_EXT_P5 */
    NULL,    /* G_MASTER_SLAVE_SEED_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_MIICTL_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_MIICTL_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_MIICTL_EXT_P5 */
    NULL,    /* G_MIICTL_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_MIISTS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_MIISTS_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_MIISTS_EXT_P5 */
    NULL,    /* G_MIISTS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_MISC_SHADOWr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_MISC_SHADOW_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_MISC_SHADOW_EXT_P5 */
    NULL,    /* G_MISC_SHADOW_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_PCTL_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_PHYIDH_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_PHYIDH_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_PHYIDH_EXT_P5 */
    NULL,    /* G_PHYIDH_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_PHYIDL_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_PHYIDL_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_PHYIDL_EXT_P5 */
    NULL,    /* G_PHYIDL_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_PHY_EXT_CTL_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_PHY_EXT_CTL_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_PHY_EXT_CTL_EXT_P5 */
    NULL,    /* G_PHY_EXT_CTL_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_PHY_EXT_STS_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_PHY_EXT_STS_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_PHY_EXT_STS_EXT_P5 */
    NULL,    /* G_PHY_EXT_STS_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_REC_ERR_CNT_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_REC_ERR_CNT_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_REC_ERR_CNT_EXT_P5 */
    NULL,    /* G_REC_ERR_CNT_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_REC_NOTOK_CNT_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_REC_NOTOK_CNT_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_REC_NOTOK_CNT_EXT_P5 */
    NULL,    /* G_REC_NOTOK_CNT_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_TEST1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_TEST2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_G_TEST1_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_TEST1_EXT_P5 */
    NULL,    /* G_TEST1_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_G_TEST2_EXT_BCM53115_A0r_ROBO],
    NULL,    /* G_TEST2_EXT_P5 */
    NULL,    /* G_TEST2_EXT_P7 */
    &soc_robo_reg_list[SOC_REG_INT_HL_PRTC_CTRL_BCM53118_A0r_ROBO],
    NULL,    /* HNDRD_ACTL */
    NULL,    /* HNDRD_ASTS */
    NULL,    /* HNDRD_FCSCNT */
    NULL,    /* HNDRD_RECNT */
    NULL,    /* IEEE802P2_LLC */
    NULL,    /* IEEE_802_2_LLC */
    &soc_robo_reg_list[SOC_REG_INT_IGMIRCTL_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_IGMIRDIV_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_IGMIRMAC_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_IMP0_PRT_IDr_ROBO],
    NULL,    /* IMP1_EGRESS_RATE_CTRL_CFG_REG */
    NULL,    /* IMP1_PRT_ID */
    &soc_robo_reg_list[SOC_REG_INT_IMP_CTLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_IMP_EGRESS_RATE_CTRL_CFG_REGr_ROBO],
    NULL,    /* IMP_PCP2TC */
    NULL,    /* IMP_PCTL */
    &soc_robo_reg_list[SOC_REG_INT_IMP_RGMII_CTL_GP_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_IMP_RGMII_TIME_DLY_GP_BCM53118_A0r_ROBO],
    NULL,    /* IMP_SLEEP_STS */
    NULL,    /* IMP_SLEEP_TIMER */
    NULL,    /* IMP_SOFTWARE_EGRESS_CTRL */
    NULL,    /* INGRESS_RMON */
    NULL,    /* INGRESS_SFLOW */
    NULL,    /* INGRESS_SFLOW_PORT */
    &soc_robo_reg_list[SOC_REG_INT_PKTS1523TO2047r_ROBO],
    NULL,    /* INRANGEERRPKTS */
    NULL,    /* INTERNAL_CPU_DEBUG */
    NULL,    /* INTERNAL_CPU_MII_PORT_CONTROL */
    NULL,    /* INTERNAL_CPU_MMR_ADDRESS */
    NULL,    /* INTERNAL_CPU_MMR_DATA */
    NULL,    /* INTERRUPT */
    NULL,    /* INTERRUPT_EXT_P5 */
    NULL,    /* INT_EN */
    NULL,    /* INT_STS */
    NULL,    /* INT_TRIGGER */
    NULL,    /* IN_CPU_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_IPG_SHRNK_CTRLr_ROBO],
    NULL,    /* ISP_PORT_SEL_PBM */
    &soc_robo_reg_list[SOC_REG_INT_ISP_SEL_PORTMAP_BCM53115_A0r_ROBO],
    NULL,    /* ISP_TPID */
    NULL,    /* ISP_VID */
    NULL,    /* IVM_EVM_HIT_ENTRY */
    &soc_robo_reg_list[SOC_REG_INT_RXEXCESSSIZEDISC_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_JUMBO_PORT_MASK_BCM5395_A0r_ROBO],
    NULL,    /* L4PORT_RANGE_CHECKER */
    NULL,    /* LCPLL_CTRL_H */
    NULL,    /* LCPLL_CTRL_L */
    NULL,    /* LCPLL_STATE_OUTPUT */
    NULL,    /* LDMETER_UPDATE_RATECTL */
    NULL,    /* LD_FRM_SA */
    NULL,    /* LED0_ST */
    NULL,    /* LED1_ST */
    NULL,    /* LED2_ST */
    NULL,    /* LED3_ST */
    NULL,    /* LEDA_CTL */
    NULL,    /* LEDA_ST */
    NULL,    /* LEDB_ST */
    NULL,    /* LEDC_ST */
    NULL,    /* LEDD_ST */
    NULL,    /* LED_CONTROL */
    &soc_robo_reg_list[SOC_REG_INT_LED_EN_MAP_BCM53118_A0r_ROBO],
    NULL,    /* LED_FLSH_CTL */
    &soc_robo_reg_list[SOC_REG_INT_LED_FUNC0_CTL_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_FUNC1_CTL_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_FUNC_MAP_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_MODE_MAP_0_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_MODE_MAP_1_BCM5395_A0r_ROBO],
    NULL,    /* LED_OPTIONS */
    &soc_robo_reg_list[SOC_REG_INT_LED_OUTPUT_ENABLE_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_PORTMAP_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LED_REFLSH_CTL_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LNKSTS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LNKSTSCHG_BCM5398_A0r_ROBO],
    NULL,    /* LOW_POWER_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_LPDET_CFG_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LPDET_SAr_ROBO],
    NULL,    /* LPNXP */
    NULL,    /* LPNXP_EXT_P5 */
    NULL,    /* LP_STA_GP */
    NULL,    /* LRN_CNT_CTL */
    &soc_robo_reg_list[SOC_REG_INT_LSA_MII_PORTr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_LSA_PORT_BCM53118_A0r_ROBO],
    NULL,    /* MAC2VLAN_CTL */
    NULL,    /* MAC_FM_DROP_CTL */
    NULL,    /* MAC_SEC_CON0 */
    NULL,    /* MAC_SEC_CON1 */
    NULL,    /* MAC_SEC_CON2 */
    NULL,    /* MAC_SEC_CON3 */
    NULL,    /* MAC_SEC_CON4 */
    &soc_robo_reg_list[SOC_REG_INT_MAC_TRUNK_CTLr_ROBO],
    NULL,    /* MARLA_FWD_ENTRY0 */
    NULL,    /* MARLA_FWD_ENTRY1 */
    NULL,    /* MARLA_SRCH_RSLT */
    NULL,    /* MARLA_SRCH_RSLT_0 */
    NULL,    /* MARLA_SRCH_RSLT_1 */
    NULL,    /* MAX_ICMPV4_SIZE */
    &soc_robo_reg_list[SOC_REG_INT_MAX_ICMPV4_SIZE_REGr_ROBO],
    NULL,    /* MAX_ICMPV6_SIZE */
    &soc_robo_reg_list[SOC_REG_INT_MAX_ICMPV6_SIZE_REGr_ROBO],
    NULL,    /* MCAST_SUP0 */
    NULL,    /* MCAST_SUP1 */
    NULL,    /* MDIO_ADDR_P */
    &soc_robo_reg_list[SOC_REG_INT_MDIO_ADDR_P8r_ROBO],
    NULL,    /* MDIO_ADDR_WAN */
    NULL,    /* MDIO_BASE_ADDR */
    NULL,    /* MDIO_DIRECT_ACCESS */
    NULL,    /* MDIO_IMP_ADDR */
    NULL,    /* MDIO_PORT7_ADDR */
    NULL,    /* MDIO_WAN_ADDR */
    NULL,    /* MEMORY_TEST_CTRL */
    NULL,    /* MEMORY_TEST_CTRL_1 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_ADDRr_ROBO],
    NULL,    /* MEM_ADDR_0 */
    NULL,    /* MEM_ADDR_1 */
    NULL,    /* MEM_ADDR_2 */
    NULL,    /* MEM_ADDR_3 */
    NULL,    /* MEM_ARL_B0_HI */
    NULL,    /* MEM_ARL_B0_LO */
    NULL,    /* MEM_ARL_B1_HI */
    NULL,    /* MEM_ARL_B1_LO */
    NULL,    /* MEM_ARL_HIGH */
    NULL,    /* MEM_ARL_LOW */
    &soc_robo_reg_list[SOC_REG_INT_MEM_BFC_ADDR_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_BFC_DATA_BCM5395_A0r_ROBO],
    NULL,    /* MEM_BTM_DATA */
    &soc_robo_reg_list[SOC_REG_INT_MEM_BTM_DATA0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_BTM_DATA1_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_CTRL_BCM5395_A0r_ROBO],
    NULL,    /* MEM_DATA_0 */
    NULL,    /* MEM_DATA_1 */
    NULL,    /* MEM_DATA_2 */
    NULL,    /* MEM_DATA_3 */
    NULL,    /* MEM_DATA_4 */
    NULL,    /* MEM_DATA_5 */
    NULL,    /* MEM_DATA_6 */
    NULL,    /* MEM_DATA_7 */
    NULL,    /* MEM_DATA_HIGH */
    NULL,    /* MEM_DATA_LOW */
    &soc_robo_reg_list[SOC_REG_INT_MEM_DEBUG_DATA_0_0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_DEBUG_DATA_0_1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_DEBUG_DATA_1_0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_DEBUG_DATA_1_1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_ADDR_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA0_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA1_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA2_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MEM_FRM_DATA3_BCM5395_A0r_ROBO],
    NULL,    /* MEM_FRM_DATA4 */
    NULL,    /* MEM_FRM_DATA5 */
    NULL,    /* MEM_FRM_DATA6 */
    NULL,    /* MEM_FRM_DATA7 */
    NULL,    /* MEM_INDEX */
    NULL,    /* MEM_KEY_0 */
    NULL,    /* MEM_KEY_1 */
    NULL,    /* MEM_KEY_2 */
    NULL,    /* MEM_KEY_3 */
    NULL,    /* MEM_KEY_4 */
    NULL,    /* MEM_KEY_5 */
    NULL,    /* MEM_KEY_6 */
    NULL,    /* MEM_KEY_7 */
    NULL,    /* MEM_MARL_B0_HI */
    NULL,    /* MEM_MARL_B0_LO */
    NULL,    /* MEM_MARL_B1_HI */
    NULL,    /* MEM_MARL_B1_LO */
    NULL,    /* MEM_MARL_HIGH */
    NULL,    /* MEM_MARL_LOW */
    NULL,    /* MEM_SRCH_ADDR_0 */
    NULL,    /* MEM_SRCH_CTRL */
    NULL,    /* MEM_SRCH_DATA_0 */
    NULL,    /* MEM_SRCH_DATA_1 */
    NULL,    /* MEM_SRCH_INDEX */
    NULL,    /* MEM_SRCH_KEY_2 */
    &soc_robo_reg_list[SOC_REG_INT_MEM_TEST_CTL_BCM53118_A0r_ROBO],
    NULL,    /* MEM_TEST_CTRL_0 */
    NULL,    /* MEM_TEST_CTRL_1 */
    NULL,    /* MEM_TEST_CTRL_2 */
    NULL,    /* MEM_TEST_CTRL_3 */
    NULL,    /* MEM_VLAN_DATA */
    NULL,    /* MIBDIAG_PAGE */
    NULL,    /* MIBDIGA_PAGE */
    NULL,    /* MIBKILLOVR */
    &soc_robo_reg_list[SOC_REG_INT_MIB_GD_FM_MAX_SIZE_BCM53115_A0r_ROBO],
    NULL,    /* MIB_PORT_SEL */
    NULL,    /* MIB_SELECT */
    &soc_robo_reg_list[SOC_REG_INT_MIB_SNAPSHOT_CTL_BCM5395_A0r_ROBO],
    NULL,    /* MIICTL */
    NULL,    /* MIICTL_EXT_P5 */
    NULL,    /* MIISTS */
    NULL,    /* MIISTS_EXT_P5 */
    NULL,    /* MII_PCTL */
    &soc_robo_reg_list[SOC_REG_INT_MINIMUM_TCP_HDR_SZr_ROBO],
    NULL,    /* MIN_TCP_HEADER_SIZE */
    &soc_robo_reg_list[SOC_REG_INT_MIRCAPCTL_BCM5395_A0r_ROBO],
    NULL,    /* MIRRORCTL */
    NULL,    /* MISC_CTL */
    &soc_robo_reg_list[SOC_REG_INT_MLF_DROP_MAP_BCM5389_A0r_ROBO],
    NULL,    /* MLF_IMPC_FWD_MAP */
    &soc_robo_reg_list[SOC_REG_INT_MLF_IPMC_FWD_MAP_BCM53115_A0r_ROBO],
    NULL,    /* MNGPID */
    &soc_robo_reg_list[SOC_REG_INT_MODEL_ID_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MODULE_ID0_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MODULE_ID1_BCM53115_A0r_ROBO],
    NULL,    /* MONITOR_TOTAL_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ0_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ1_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ2_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ3_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ4_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ5_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ6_BUF_USED_COUNT */
    NULL,    /* MONITOR_TXQ7_BUF_USED_COUNT */
    NULL,    /* MONITOR_TX_PORT_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_MPORTVEC0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MPORTVEC1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MPORTVEC2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MPORTVEC3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MPORTVEC4r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MPORTVEC5r_ROBO],
    NULL,    /* MR_STA */
    &soc_robo_reg_list[SOC_REG_INT_MST_AGE_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MST_CON_BCM53118_A0r_ROBO],
    NULL,    /* MST_TAB */
    &soc_robo_reg_list[SOC_REG_INT_MST_TBL_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MULTIPORT_ADDR0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MULTIPORT_ADDR1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MULTIPORT_ADDR2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MULTIPORT_ADDR3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MULTIPORT_ADDR4r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MULTIPORT_ADDR5r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_MULTI_PORT_CTLr_ROBO],
    NULL,    /* NEW_CONTROL */
    &soc_robo_reg_list[SOC_REG_INT_NEW_CTRLr_ROBO],
    NULL,    /* NEW_PRI_MAP */
    NULL,    /* OTHER_CHECKER */
    NULL,    /* OTHER_TABLE_DATA0 */
    NULL,    /* OTHER_TABLE_DATA1 */
    NULL,    /* OTHER_TABLE_DATA2 */
    NULL,    /* OTHER_TABLE_INDEX */
    NULL,    /* OTPROM_STATUS */
    &soc_robo_reg_list[SOC_REG_INT_OTP_ADDR_REGr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_OTP_CTL_REG_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_OTP_RD_DATAr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_OTP_STS_REGr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_OTP_WR_DATAr_ROBO],
    NULL,    /* OUTOFRANGEERRPKTS */
    &soc_robo_reg_list[SOC_REG_INT_PKTS2048TO4095r_ROBO],
    NULL,    /* P5_RGMII_TIME_DLY_GP */
    &soc_robo_reg_list[SOC_REG_INT_P8_PCP2TC_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PAGEREGr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PAUSESTS_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PAUSE_CAP_BCM5395_A0r_ROBO],
    NULL,    /* PAUSE_FM_SA */
    &soc_robo_reg_list[SOC_REG_INT_PAUSE_FRM_CTRL_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PAUSE_QUANTAr_ROBO],
    NULL,    /* PBPTRFIFO */
    &soc_robo_reg_list[SOC_REG_INT_PBPTRFIFO_0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PBPTRFIFO_1_BCM53118_A0r_ROBO],
    NULL,    /* PCP_VALUE_CTRL */
    NULL,    /* PEAK_TEMP_MON_RESU */
    NULL,    /* PEAK_TOTAL_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ0_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ1_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ2_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ3_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ4_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ5_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ6_BUF_USED_COUNT */
    NULL,    /* PEAK_TXQ7_BUF_USED_COUNT */
    NULL,    /* PHYIDH */
    NULL,    /* PHYIDL */
    NULL,    /* PHYINFO_PHYIDH */
    NULL,    /* PHYINFO_PHYIDL */
    NULL,    /* PHYSCAN_CTL */
    NULL,    /* PHY_CTRL */
    NULL,    /* PHY_INT_STS */
    &soc_robo_reg_list[SOC_REG_INT_PHY_LED_FUNCr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PHY_PWR_DOWN_BCM53118_A0r_ROBO],
    NULL,    /* PHY_STAT */
    NULL,    /* PHY_STS */
    NULL,    /* PKTS1024TO1522OCTETS */
    NULL,    /* PKTS1024TOMAXOCTETS */
    &soc_robo_reg_list[SOC_REG_INT_PKTS1024TO1522OCTETS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PKTS1024TO1522OCTETS_BCM5389_A0r_ROBO],
    NULL,    /* PKTS1523TO2047 */
    NULL,    /* PKTS2048TO4095 */
    &soc_robo_reg_list[SOC_REG_INT_PKTS256TO511OCTETS_BCM5395_A0r_ROBO],
    NULL,    /* PKTS4096TO8191 */
    &soc_robo_reg_list[SOC_REG_INT_RXJABBERS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PKTS256TO511OCTETS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PKTS512TO1023OCTETS_BCM5389_A0r_ROBO],
    NULL,    /* PKTS8192TO9728 */
    NULL,    /* PKT_MARK_CTL */
    NULL,    /* PLL_CTRL */
    NULL,    /* PLL_CTRL_0 */
    NULL,    /* PLL_CTRL_1 */
    NULL,    /* PLL_CTRL_2 */
    &soc_robo_reg_list[SOC_REG_INT_PLL_FREQ_SELr_ROBO],
    NULL,    /* PLL_STS */
    NULL,    /* PLL_TEST */
    &soc_robo_reg_list[SOC_REG_INT_PLL_TEST_CTRL_I_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PLL_TEST_CTRL_II_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PN_PCP2TC_BCM53118_A0r_ROBO],
    NULL,    /* PORT4_RGMII_CTL_GP */
    NULL,    /* PORT5_RGMII_CTL_GP */
    NULL,    /* PORT7_RGMII_CTL_GP */
    NULL,    /* PORT7_RGMII_TIME_DLY_GP */
    NULL,    /* PORTVEC1 */
    NULL,    /* PORTVEC2 */
    NULL,    /* PORT_CROSS_CONNECT */
    NULL,    /* PORT_EAP1_CON */
    &soc_robo_reg_list[SOC_REG_INT_PORT_EAP_CON_BCM5395_A0r_ROBO],
    NULL,    /* PORT_EAP_DA */
    NULL,    /* PORT_EGCTL */
    &soc_robo_reg_list[SOC_REG_INT_PORT_ERC_CON_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PORT_ERC_CON_IMPr_ROBO],
    NULL,    /* PORT_IRC1_CON */
    NULL,    /* PORT_IRC_CON */
    NULL,    /* PORT_MAX_LEARN */
    NULL,    /* PORT_SA_CNT */
    NULL,    /* PORT_SEC_CON */
    NULL,    /* PORT_VLAN1_CTL */
    &soc_robo_reg_list[SOC_REG_INT_PORT_VLAN_CTL_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PORT_VLAN_CTL_IMPr_ROBO],
    NULL,    /* PORT_XOFF_STS */
    NULL,    /* POST_LED_CTRL */
    NULL,    /* PRBS_CTL */
    NULL,    /* PRBS_STA */
    NULL,    /* PRESERVE_PKT_FORMAT */
    NULL,    /* PROFILE_CTL */
    &soc_robo_reg_list[SOC_REG_INT_PROTECTED_SEL_BCM5389_A0r_ROBO],
    NULL,    /* PROTOCOL2VLAN_CTL */
    &soc_robo_reg_list[SOC_REG_INT_PRS_FIFO_DEBUG_CTRLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PRS_FIFO_DEBUG_DATAr_ROBO],
    NULL,    /* PTEST */
    NULL,    /* PWR_DOWN_MODE */
    NULL,    /* QOS_1P1Q_PRI_MAP */
    &soc_robo_reg_list[SOC_REG_INT_QOS_1P_EN_BCM5389_A0r_ROBO],
    NULL,    /* QOS_CTL */
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP0_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP1_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP2_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_QOS_DIFF_DSCP3_BCM53118_A0r_ROBO],
    NULL,    /* QOS_D_TOS_TH */
    &soc_robo_reg_list[SOC_REG_INT_QOS_EN_DIFFSERV_BCM5389_A0r_ROBO],
    NULL,    /* QOS_EN_TRAFFIC_PRI_REMAP */
    NULL,    /* QOS_ETHERPRI_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_QOS_GLOBAL_CTRL_BCM5395_A0r_ROBO],
    NULL,    /* QOS_MIB_QUE_SEL */
    NULL,    /* QOS_M_TOS_TH */
    NULL,    /* QOS_PAUSE_EN */
    NULL,    /* QOS_REASON_CODE */
    NULL,    /* QOS_RX_CTRL_P */
    NULL,    /* QOS_R_TOS_TH */
    NULL,    /* QOS_TCI_TH */
    NULL,    /* QOS_TOS_DIF_CTL */
    NULL,    /* QOS_TOS_DIF_EN */
    NULL,    /* QOS_TRAFFIC_PRI_REMAP */
    &soc_robo_reg_list[SOC_REG_INT_QOS_TX_CTRL_BCM5395_A0r_ROBO],
    NULL,    /* QOS_T_TOS_TH */
    &soc_robo_reg_list[SOC_REG_INT_QOS_WEIGHTr_ROBO],
    NULL,    /* QUEUE_CONGESTION_STATUS0 */
    NULL,    /* QUEUE_CONGESTION_STATUS1 */
    NULL,    /* QUEUE_CONGESTION_STATUS2 */
    NULL,    /* QUEUE_CONGESTION_STATUS3 */
    NULL,    /* QUEUE_CONGESTION_STATUS4 */
    NULL,    /* QUEUE_CONGESTION_STATUS5 */
    NULL,    /* QUEUE_REGION_STATUS */
    NULL,    /* RANGE_CHECKER */
    NULL,    /* RANGE_CHECKER_CTL */
    NULL,    /* RANGE_CHECKER_FIELD_SEL */
    NULL,    /* RATE_INBAND */
    NULL,    /* RATE_METER0 */
    NULL,    /* RATE_METER1 */
    NULL,    /* RATE_OUTBAND */
    NULL,    /* RCM_CTL */
    NULL,    /* RCM_DATA0 */
    NULL,    /* RCM_DATA1 */
    NULL,    /* RCM_DATA2 */
    NULL,    /* RCM_DATA3 */
    NULL,    /* RCM_DATA4 */
    NULL,    /* RCM_PORT */
    NULL,    /* REGULATOR_CTRL */
    NULL,    /* REGULATOR_UNLOCK */
    NULL,    /* REGULATOR_VOLT_SEL */
    &soc_robo_reg_list[SOC_REG_INT_RESE_AV_EN_CTRL_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RESE_C4_BW_CNTL_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RESE_C5_BW_CNTL_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RESE_EGRESS_TM_STAMP_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RESE_MAX_AV_PKT_SZr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RESE_SLOT_ADJr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RESE_SLOT_TICK_CNTRr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RESE_TM_ADJr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RESE_TM_BASEr_ROBO],
    NULL,    /* RGMII_CTL_GP */
    NULL,    /* RGMII_CTL_GP48 */
    NULL,    /* RGMII_CTL_GP49 */
    NULL,    /* RGMII_CTL_GP50 */
    NULL,    /* RGMII_CTRL */
    NULL,    /* RGMII_CTRL_GP25 */
    NULL,    /* RGMII_CTRL_GP26 */
    NULL,    /* RGMII_CTRL_IMP */
    NULL,    /* RGMII_TIME_DELAY_CTRL */
    NULL,    /* RGMII_TIME_DLY_CTRL_GP25 */
    NULL,    /* RGMII_TIME_DLY_CTRL_GP26 */
    NULL,    /* RGMII_TIME_DLY_CTRL_IMP */
    NULL,    /* RGMII_TIME_DLY_GP */
    NULL,    /* RGMII_TIME_DLY_GP48 */
    NULL,    /* RGMII_TIME_DLY_GP49 */
    NULL,    /* RGMII_TIME_DLY_GP50 */
    &soc_robo_reg_list[SOC_REG_INT_RMONSTEER_BCM53115_A0r_ROBO],
    NULL,    /* RM_PINS_DEBUG */
    NULL,    /* RST_TABLE_MEM */
    NULL,    /* RST_TABLE_MEM1 */
    &soc_robo_reg_list[SOC_REG_INT_RSV_MCAST_CTRL_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXALIGNMENTERRORS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXBROADCASTPKT_BCM5395_A0r_ROBO],
    NULL,    /* RXBROADCASTPKTS */
    &soc_robo_reg_list[SOC_REG_INT_RXDISCARDr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXDROPPKTS_BCM5395_A0r_ROBO],
    NULL,    /* RXEXCESSSIZEDISC */
    &soc_robo_reg_list[SOC_REG_INT_RXDROPPKTS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXQOSPKTS_BCM5389_A0r_ROBO],
    NULL,    /* RXFWDDISCPKTS */
    &soc_robo_reg_list[SOC_REG_INT_RXGOODOCTETS_BCM5395_A0r_ROBO],
    NULL,    /* RXGOODPKTS */
    NULL,    /* RXJABBERPKTS */
    &soc_robo_reg_list[SOC_REG_INT_RXJABBERS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXFRAGMENTS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXOCTETS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXFCSERRORS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_PKTS128TO255OCTETS_BCM5389_A0r_ROBO],
    NULL,    /* RXPAUSESTS */
    NULL,    /* RXPKTS1024TOMAXPKT */
    NULL,    /* RXPKTS128TO255OCTETS */
    NULL,    /* RXPKTS256TO511OCTETS */
    NULL,    /* RXPKTS512TO1023OCTETS */
    NULL,    /* RXPKTS64OCTETS */
    NULL,    /* RXPKTS65TO127OCTETS */
    NULL,    /* RXQOSOCTETS */
    NULL,    /* RXQOSPKTS */
    &soc_robo_reg_list[SOC_REG_INT_RXSACHANGES_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXSYMBLERR_BCM5395_A0r_ROBO],
    NULL,    /* RXSYMBOLERR */
    &soc_robo_reg_list[SOC_REG_INT_RXUNDERSIZEPKTS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RXSACHANGES_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_RX_GLOBAL_CTL_BCM5395_A0r_ROBO],
    NULL,    /* RX_JUMBO_PACKET_COUNTER */
    &soc_robo_reg_list[SOC_REG_INT_RX_PAUSE_PASS_BCM53118_A0r_ROBO],
    NULL,    /* SCAN_RSLT_GP */
    NULL,    /* SCAN_RSLT_IMP */
    NULL,    /* SCAN_RSLT_P */
    NULL,    /* SCAN_TIMEOUT */
    NULL,    /* SDACTLSTS */
    NULL,    /* SDAEGSTS */
    NULL,    /* SDAMODE2 */
    NULL,    /* SDAMPHY */
    NULL,    /* SDANADV */
    NULL,    /* SDANEXP */
    NULL,    /* SDANLPA */
    NULL,    /* SDANNXP */
    NULL,    /* SDASTSSUM */
    NULL,    /* SDBRCMTST */
    NULL,    /* SDHNDRD_ACTL */
    NULL,    /* SDHNDRD_ASTS */
    NULL,    /* SDHNDRD_FCSCNT */
    NULL,    /* SDHNDRD_RECNT */
    NULL,    /* SDLPNXP */
    NULL,    /* SDMIICTL */
    NULL,    /* SDMIISTS */
    NULL,    /* SDPHYIDH */
    NULL,    /* SDPHYIDL */
    NULL,    /* SD_DEFAULT */
    NULL,    /* SD_SEL_EARLY */
    NULL,    /* SD_SIGNAL_DETC */
    NULL,    /* SECURITY_BYPASS_CTL */
    NULL,    /* SECURITY_GLOBAL_CTL */
    NULL,    /* SEC_DPMSK */
    NULL,    /* SEC_SPMSK */
    NULL,    /* SEC_TDIP0 */
    NULL,    /* SEC_TDIP1 */
    NULL,    /* SERDES_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_SFT_LRN_CTLr_ROBO],
    NULL,    /* SGMII_CLR_CTL */
    NULL,    /* SGMII_CTL_GP */
    NULL,    /* SGMII_STA_GP */
    NULL,    /* SIP_REG */
    NULL,    /* SLICE_MAP_P */
    NULL,    /* SLICE_MAP_P8 */
    NULL,    /* SPARE_REG0 */
    NULL,    /* SPARE_REG1 */
    NULL,    /* SPARE_REG2 */
    &soc_robo_reg_list[SOC_REG_INT_SPDSTS_BCM5389_A0r_ROBO],
    NULL,    /* SPECIAL_MNGT */
    NULL,    /* SPICTL */
    &soc_robo_reg_list[SOC_REG_INT_SPIDIO0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPIDIO1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPIDIO2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPIDIO3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPIDIO4r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPIDIO5r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPIDIO6r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPIDIO7r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPISTSr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPTAGT_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SPT_MULTI_ADDR_BPS_CTRLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_SRCADRCHGr_ROBO],
    NULL,    /* STP_BYPASS_CTL */
    NULL,    /* STRAP_PIN_STATUS */
    NULL,    /* STRAP_STS */
    &soc_robo_reg_list[SOC_REG_INT_STRAP_VALUE_BCM53118_A0r_ROBO],
    NULL,    /* STS_CTL */
    &soc_robo_reg_list[SOC_REG_INT_STS_OVERRIDE_GMIIP_BCM53118_A0r_ROBO],
    NULL,    /* STS_OVERRIDE_GP */
    &soc_robo_reg_list[SOC_REG_INT_STS_OVERRIDE_IMP_BCM5389_A0r_ROBO],
    NULL,    /* STS_OVERRIDE_P */
    NULL,    /* STS_OVERRIDE_P24 */
    NULL,    /* STS_OVERRIDE_WAN_P */
    NULL,    /* SWITCH_CTRL */
    &soc_robo_reg_list[SOC_REG_INT_SWMODE_BCM5389_A0r_ROBO],
    NULL,    /* SW_FLOW_CON */
    NULL,    /* SW_XOFF_PORT_CTL */
    NULL,    /* S_ANADV */
    NULL,    /* S_ANEXP */
    NULL,    /* S_ANLPA1 */
    NULL,    /* S_ANLPA2 */
    NULL,    /* S_ANNXP */
    NULL,    /* S_EEE_LPI_DURATION */
    NULL,    /* S_EEE_LPI_EVENT */
    NULL,    /* S_EXT_STS */
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS1523TO2047_BCM5395_A0r_ROBO],
    NULL,    /* S_INRANGEERRPKTS */
    &soc_robo_reg_list[SOC_REG_INT_S_JUMBOPKTr_ROBO],
    NULL,    /* S_MIICTL */
    NULL,    /* S_MIISTS */
    NULL,    /* S_OUTOFRANGEERRPKTS */
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS2048TO4095_BCM5395_A0r_ROBO],
    NULL,    /* S_PHYIDH */
    NULL,    /* S_PHYIDL */
    NULL,    /* S_PKTS1024TO1522OCTETS */
    NULL,    /* S_PKTS1024TOMAXOCTETS */
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS1024TO1522OCTETS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS128TO255OCTETS_BCM5395_A0r_ROBO],
    NULL,    /* S_PKTS1523TO2047 */
    NULL,    /* S_PKTS2048TO4095 */
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS256TO511OCTETS_BCM5395_A0r_ROBO],
    NULL,    /* S_PKTS4096TO8191 */
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS512TO1023OCTETS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS64OCTETS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_PKTS65TO127OCTETS_BCM5395_A0r_ROBO],
    NULL,    /* S_PKTS8192TO9728 */
    &soc_robo_reg_list[SOC_REG_INT_S_RXALIGNMENTERRORS_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXBROADCASTPKT_BCM5395_A0r_ROBO],
    NULL,    /* S_RXBROADCASTPKTS */
    &soc_robo_reg_list[SOC_REG_INT_S_RXDISCARDr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXDROPPKTS_BCM53115_A0r_ROBO],
    NULL,    /* S_RXEXCESSSIZEDISC */
    &soc_robo_reg_list[SOC_REG_INT_S_RXFCSERRORS_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXFRAGMENTS_BCM5395_A0r_ROBO],
    NULL,    /* S_RXFWDDISCPKTS */
    &soc_robo_reg_list[SOC_REG_INT_S_RXGOODOCTETS_BCM5395_A0r_ROBO],
    NULL,    /* S_RXJABBERPKTS */
    &soc_robo_reg_list[SOC_REG_INT_S_RXJABBERS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXMULTICASTPKTS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXOCTETS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXOVERSIZEPKTS_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXPAUSEPKTS_BCM5395_A0r_ROBO],
    NULL,    /* S_RXPKTS1024TOMAXPKT */
    NULL,    /* S_RXPKTS128TO255OCTETS */
    NULL,    /* S_RXPKTS256TO511OCTETS */
    NULL,    /* S_RXPKTS512TO1023OCTETS */
    NULL,    /* S_RXPKTS64OCTETS */
    NULL,    /* S_RXPKTS65TO127OCTETS */
    NULL,    /* S_RXQOSOCTETS */
    NULL,    /* S_RXQOSPKTS */
    &soc_robo_reg_list[SOC_REG_INT_S_RXSACHANGES_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXSYMBLERR_BCM53115_A0r_ROBO],
    NULL,    /* S_RXSYMBOLERR */
    &soc_robo_reg_list[SOC_REG_INT_S_RXUNDERSIZEPKTS_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_RXUNICASTPKTS_BCM5395_A0r_ROBO],
    NULL,    /* S_RX_JUMBO_PACKET_COUNTER */
    &soc_robo_reg_list[SOC_REG_INT_S_TXBROADCASTPKTS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXCOLLISIONS_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXDEFERREDTRANSMIT_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXDROPPKTS_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXEXCESSIVECOLLISION_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXFRAMEINDISC_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXLATECOLLISION_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXMULTICASTPKTS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXMULTIPLECOLLISION_BCM53115_A0r_ROBO],
    NULL,    /* S_TXMULTIPLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_S_TXOCTETS_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXPAUSEPKTS_BCM5395_A0r_ROBO],
    NULL,    /* S_TXPKTS1024TOMAXPKT */
    NULL,    /* S_TXPKTS128TO255OCTETS */
    NULL,    /* S_TXPKTS256TO511OCTETS */
    NULL,    /* S_TXPKTS512TO1023OCTETS */
    NULL,    /* S_TXPKTS64OCTETS */
    NULL,    /* S_TXPKTS65TO127OCTETS */
    NULL,    /* S_TXPORTCONGESTIONDROP */
    NULL,    /* S_TXQOS0OCTETS */
    NULL,    /* S_TXQOS0PKTS */
    NULL,    /* S_TXQOS1OCTETS */
    NULL,    /* S_TXQOS1PKTS */
    NULL,    /* S_TXQOS2OCTETS */
    NULL,    /* S_TXQOS2PKTS */
    NULL,    /* S_TXQOS3OCTETS */
    NULL,    /* S_TXQOS3PKTS */
    NULL,    /* S_TXQOSOCTETS */
    NULL,    /* S_TXQOSPKTS */
    &soc_robo_reg_list[SOC_REG_INT_S_TXQPKTQ0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQPKTQ1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQPKTQ2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQPKTQ3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQPKTQ4r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_S_TXQPKTQ5r_ROBO],
    NULL,    /* S_TXQQ0OCTETS */
    NULL,    /* S_TXQQ0PACKET */
    NULL,    /* S_TXQQ1OCTETS */
    NULL,    /* S_TXQQ1PACKET */
    NULL,    /* S_TXQQ2OCTETS */
    NULL,    /* S_TXQQ2PACKET */
    NULL,    /* S_TXQQ3OCTETS */
    NULL,    /* S_TXQQ3PACKET */
    NULL,    /* S_TXQQ4OCTETS */
    NULL,    /* S_TXQQ4PACKET */
    NULL,    /* S_TXQQ5OCTETS */
    NULL,    /* S_TXQQ5PACKET */
    NULL,    /* S_TXQQ6OCTETS */
    NULL,    /* S_TXQQ6PACKET */
    NULL,    /* S_TXQQ7OCTETS */
    NULL,    /* S_TXQQ7PACKET */
    NULL,    /* S_TXQQSEL0CONGESTIONDROP */
    NULL,    /* S_TXQQSEL1CONGESTIONDROP */
    &soc_robo_reg_list[SOC_REG_INT_S_TXSINGLECOLLISION_BCM53115_A0r_ROBO],
    NULL,    /* S_TXSINGLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_S_TXUNICASTPKTS_BCM5395_A0r_ROBO],
    NULL,    /* S_TX_JUMBO_PACKET_COUNTER */
    NULL,    /* TBI_CTL */
    &soc_robo_reg_list[SOC_REG_INT_TC2COS_MAPr_ROBO],
    NULL,    /* TCAM_BIST_CONTROL */
    NULL,    /* TCAM_BIST_CTL */
    NULL,    /* TCAM_BIST_STATUS */
    NULL,    /* TCAM_BIST_STS0 */
    NULL,    /* TCAM_BIST_STS1 */
    NULL,    /* TCAM_CHKSUM_STS */
    NULL,    /* TCAM_CTL */
    NULL,    /* TCAM_CTRL */
    NULL,    /* TCAM_TEST_COMPARE_STATUS */
    NULL,    /* TCP_UDP_ACTION_REG */
    NULL,    /* TCP_UDP_HIT_REG */
    NULL,    /* TCP_UDP_KEY_REG */
    NULL,    /* TCP_UDP_WILDCARD_ACTION_REG */
    NULL,    /* TC_DP2DSCP_MAP0 */
    NULL,    /* TC_DP2DSCP_MAP1 */
    NULL,    /* TC_DP2DSCP_MAP2 */
    NULL,    /* TC_DP2DSCP_MAP3 */
    NULL,    /* TC_DP2DSCP_MAP4 */
    NULL,    /* TC_DP2DSCP_MAP5 */
    NULL,    /* TC_DP2DSCP_MAP6 */
    NULL,    /* TC_DP2DSCP_MAP7 */
    NULL,    /* TC_GROUP_CTRL */
    NULL,    /* TEMP_MON_CAL */
    NULL,    /* TEMP_MON_CTL */
    NULL,    /* TEMP_MON_RESU */
    NULL,    /* TEMP_MON_SPEC_CTL */
    NULL,    /* TH_PCTL */
    &soc_robo_reg_list[SOC_REG_INT_TM_STAMP_RPT_CTRLr_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TM_STAMP_STATUS_BCM53118_A0r_ROBO],
    NULL,    /* TOTAL_CONGESTION_ON_THRESHOLD */
    NULL,    /* TOTAL_DLF_DROP_THRESH_Q1 */
    NULL,    /* TOTAL_DLF_DROP_THRESH_Q2 */
    NULL,    /* TOTAL_DLF_DROP_THRESH_Q3 */
    NULL,    /* TOTAL_DROP_THRESH_Q1 */
    NULL,    /* TOTAL_DROP_THRESH_Q2 */
    NULL,    /* TOTAL_DROP_THRESH_Q3 */
    NULL,    /* TOTAL_HYST_COUNT */
    NULL,    /* TOTAL_HYST_THRESH_Q1 */
    NULL,    /* TOTAL_HYST_THRESH_Q2 */
    NULL,    /* TOTAL_HYST_THRESH_Q3 */
    NULL,    /* TOTAL_LIMIT_THRESHOLD */
    NULL,    /* TOTAL_MC_DROP_IMP_THRESH */
    NULL,    /* TOTAL_PAUSE_IMP_THRESH */
    NULL,    /* TOTAL_PROTECTION_ON_THRESHOLD */
    NULL,    /* TOTAL_REGION_STATUS */
    &soc_robo_reg_list[SOC_REG_INT_TRREG_CTRL_BCM53118_A0r_ROBO],
    NULL,    /* TRUNK_GRP0_CTL */
    NULL,    /* TRUNK_GRP1_CTL */
    NULL,    /* TRUNK_GRP2_CTL */
    NULL,    /* TRUNK_GRP3_CTL */
    NULL,    /* TRUNK_GRP_00_CTL */
    NULL,    /* TRUNK_GRP_01_CTL */
    NULL,    /* TRUNK_GRP_02_CTL */
    NULL,    /* TRUNK_GRP_03_CTL */
    NULL,    /* TRUNK_GRP_04_CTL */
    NULL,    /* TRUNK_GRP_05_CTL */
    NULL,    /* TRUNK_GRP_06_CTL */
    NULL,    /* TRUNK_GRP_07_CTL */
    NULL,    /* TRUNK_GRP_08_CTL */
    NULL,    /* TRUNK_GRP_09_CTL */
    NULL,    /* TRUNK_GRP_10_CTL */
    NULL,    /* TRUNK_GRP_11_CTL */
    NULL,    /* TRUNK_GRP_12_CTL */
    NULL,    /* TRUNK_GRP_13_CTL */
    &soc_robo_reg_list[SOC_REG_INT_TRUNK_GRP_CTL_BCM53115_A0r_ROBO],
    NULL,    /* TRUST_C1P_CTL */
    NULL,    /* TRUST_CVID */
    NULL,    /* TRUST_CVLAN */
    NULL,    /* TRUST_DSCP_CTL */
    NULL,    /* TRUST_S1P_CTL */
    &soc_robo_reg_list[SOC_REG_INT_TXBROADCASTPKTS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXCOLLISIONS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXDEFERREDTRANSMIT_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXDROPPKTS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXEXCESSIVECOLLISION_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXFRAMEINDISC_BCM5389_A0r_ROBO],
    NULL,    /* TXGOODPKTS */
    &soc_robo_reg_list[SOC_REG_INT_TXLATECOLLISION_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXMULTICASTPKTS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXMULTIPLECOLLISION_BCM5389_A0r_ROBO],
    NULL,    /* TXMULTIPLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_TXOCTETS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXPAUSEPKTS_BCM5389_A0r_ROBO],
    NULL,    /* TXPAUSESTS */
    NULL,    /* TXPKTS1024TOMAXPKT */
    NULL,    /* TXPKTS128TO255OCTETS */
    NULL,    /* TXPKTS256TO511OCTETS */
    NULL,    /* TXPKTS512TO1023OCTETS */
    NULL,    /* TXPKTS64OCTETS */
    NULL,    /* TXPKTS65TO127OCTETS */
    NULL,    /* TXPORTCONGESTIONDROP */
    NULL,    /* TXQOS0OCTETS */
    NULL,    /* TXQOS0PKTS */
    NULL,    /* TXQOS1OCTETS */
    NULL,    /* TXQOS1PKTS */
    NULL,    /* TXQOS2OCTETS */
    NULL,    /* TXQOS2PKTS */
    NULL,    /* TXQOS3OCTETS */
    NULL,    /* TXQOS3PKTS */
    NULL,    /* TXQOSOCTETS */
    NULL,    /* TXQOSPKTS */
    &soc_robo_reg_list[SOC_REG_INT_TXQOSPKTS_BCM5389_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQPKTQ1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQPKTQ2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQPKTQ3r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQPKTQ4r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_TXQPKTQ5_BCM53115_A0r_ROBO],
    NULL,    /* TXQQ0OCTETS */
    NULL,    /* TXQQ0PACKET */
    NULL,    /* TXQQ1OCTETS */
    NULL,    /* TXQQ1PACKET */
    NULL,    /* TXQQ2OCTETS */
    NULL,    /* TXQQ2PACKET */
    NULL,    /* TXQQ3OCTETS */
    NULL,    /* TXQQ3PACKET */
    NULL,    /* TXQQ4OCTETS */
    NULL,    /* TXQQ4PACKET */
    NULL,    /* TXQQ5OCTETS */
    NULL,    /* TXQQ5PACKET */
    NULL,    /* TXQQ6OCTETS */
    NULL,    /* TXQQ6PACKET */
    NULL,    /* TXQQ7OCTETS */
    NULL,    /* TXQQ7PACKET */
    NULL,    /* TXQQSEL0CONGESTIONDROP */
    NULL,    /* TXQQSEL1CONGESTIONDROP */
    NULL,    /* TXQ_BACKPRESSURE_GE0_CTL */
    NULL,    /* TXQ_BACKPRESSURE_GE1_CTL */
    NULL,    /* TXQ_BACKPRESSURE_GE2_CTL */
    NULL,    /* TXQ_BACKPRESSURE_GE3_CTL */
    NULL,    /* TXQ_BACKPRESSURE_IMP_CTL */
    NULL,    /* TXQ_DROP_CNT_COS_SELECT_0 */
    NULL,    /* TXQ_DROP_CNT_COS_SELECT_1 */
    &soc_robo_reg_list[SOC_REG_INT_TXQ_FLUSH_MODE_BCM5398_A0r_ROBO],
    NULL,    /* TXQ_HYST_A_COUNT */
    NULL,    /* TXQ_HYST_B_COUNT */
    NULL,    /* TXQ_Q0_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q0_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q0_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q1_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q1_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q1_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q2_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q2_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q2_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q3_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q3_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q3_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q4_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q4_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q4_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q5_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q5_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q5_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q6_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q6_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q6_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q7_CONGESTION_ON_THRESHOLD */
    NULL,    /* TXQ_Q7_OVERS_ON_THRESHOLD */
    NULL,    /* TXQ_Q7_PROTECTION_ON_THRESHOLD */
    NULL,    /* TXQ_WEIGHT_QUOTA_SZ */
    &soc_robo_reg_list[SOC_REG_INT_TXSINGLECOLLISION_BCM5389_A0r_ROBO],
    NULL,    /* TXSINGLECOLLISIONS */
    &soc_robo_reg_list[SOC_REG_INT_TXUNICASTPKTS_BCM5389_A0r_ROBO],
    NULL,    /* TX_EQZ_COEF */
    NULL,    /* TX_JUMBO_PACKET_COUNTER */
    &soc_robo_reg_list[SOC_REG_INT_TX_PAUSE_PASSr_ROBO],
    NULL,    /* UDF_0_A_0_8 */
    NULL,    /* UDF_0_B_0_8 */
    NULL,    /* UDF_0_C_0_8 */
    NULL,    /* UDF_0_D_0_11 */
    NULL,    /* UDF_1_A_0_8 */
    NULL,    /* UDF_1_B_0_8 */
    NULL,    /* UDF_1_C_0_8 */
    NULL,    /* UDF_2_A_0_8 */
    NULL,    /* UDF_2_B_0_8 */
    NULL,    /* UDF_2_C_0_8 */
    NULL,    /* UDF_OFFSET0_P */
    NULL,    /* UDF_OFFSET0_P8 */
    NULL,    /* UDF_OFFSET2_P */
    NULL,    /* UDF_OFFSET3_P */
    NULL,    /* UDF_OFFSET4_EXP */
    NULL,    /* UDF_OFFSET4_GP */
    NULL,    /* UDF_OFFSET4_IMP */
    NULL,    /* UDF_OFFSET4_P */
    NULL,    /* UDF_OFFSET4_P8 */
    NULL,    /* UDF_OFFSET5_P */
    NULL,    /* UDF_OFFSET5_P8 */
    &soc_robo_reg_list[SOC_REG_INT_ULF_DROP_MAP_BCM5389_A0r_ROBO],
    NULL,    /* ULF_FORWARD_MAP */
    NULL,    /* VID_RANGE_CHECKER */
    NULL,    /* VLAN2VLAN_CTL */
    NULL,    /* VLAN_BYPASS_CTL */
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL0_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL1_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL2_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL3_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL4_BCM53115_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL5_BCM53118_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_VLAN_CTRL6_BCM53118_A0r_ROBO],
    NULL,    /* VLAN_GLOBAL_CTL */
    NULL,    /* VLAN_MAC_ADDR_INDX */
    NULL,    /* VLAN_MAC_CTRL */
    NULL,    /* VLAN_MAC_HASHSEL */
    NULL,    /* VLAN_MAC_TBL_ACS */
    NULL,    /* VLAN_MAC_TBL_DATA */
    &soc_robo_reg_list[SOC_REG_INT_VLAN_MULTI_PORT_ADDR_CTLr_ROBO],
    NULL,    /* VLAN_REMAP */
    NULL,    /* VREG_UNLOCK */
    &soc_robo_reg_list[SOC_REG_INT_WAN_PORT_SEL_BCM53118_A0r_ROBO],
    NULL,    /* WAN_SLEEP_TIMER */
    &soc_robo_reg_list[SOC_REG_INT_WATCH_DOG_CTRL_BCM5395_A0r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_WATCH_DOG_RPT1r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_WATCH_DOG_RPT2r_ROBO],
    &soc_robo_reg_list[SOC_REG_INT_WATCH_DOG_RPT3r_ROBO],
    NULL,    /* X1K_ANADV */
    NULL,    /* X1K_ANEXP */
    NULL,    /* X1K_ANLPA */
    NULL,    /* X1K_ANNXP */
    NULL,    /* X1K_BER_CRC_RXCNT */
    NULL,    /* X1K_BRCMTST */
    NULL,    /* X1K_CTL1 */
    NULL,    /* X1K_CTL2 */
    NULL,    /* X1K_CTL3 */
    NULL,    /* X1K_CTL4 */
    NULL,    /* X1K_EXT_MIISTS */
    NULL,    /* X1K_FORCE_TXD1 */
    NULL,    /* X1K_FORCE_TXD2 */
    NULL,    /* X1K_LPNXP */
    NULL,    /* X1K_MIICTL */
    NULL,    /* X1K_MIISTS */
    NULL,    /* X1K_PATT_GEN_CTL */
    NULL,    /* X1K_PATT_GEN_STS */
    NULL,    /* X1K_PHYIDH */
    NULL,    /* X1K_PHYIDL */
    NULL,    /* X1K_PRBS_CTL */
    NULL,    /* X1K_PRBS_STS */
    NULL,    /* X1K_STS1 */
    NULL,    /* X1K_STS2 */
    NULL,    /* X1K_STS3 */
    NULL,    /* X1K_TST_MOD */
    NULL,    /* XOFF_PORT_HISTORY */
    NULL     /* XOFF_TRIG_PORT_CTRL */
};

static soc_mem_info_t *soc_memories_bcm53118_a0[] = {
    NULL,    /* CFP_ACT_POL */
    NULL,    /* CFP_DATA */
    NULL,    /* CFP_DATA_MASK */
    NULL,    /* CFP_MASK */
    NULL,    /* CFP_METER */
    NULL,    /* CFP_RATE_METER */
    NULL,    /* CFP_STAT */
    NULL,    /* CFP_STAT_IB */
    NULL,    /* CFP_STAT_OB */
    NULL,    /* CFP_TCAM_CHAIN_MASK */
    NULL,    /* CFP_TCAM_CHAIN_SC */
    NULL,    /* CFP_TCAM_IPV4_MASK */
    NULL,    /* CFP_TCAM_IPV4_S0 */
    NULL,    /* CFP_TCAM_IPV4_S1 */
    NULL,    /* CFP_TCAM_IPV4_S2 */
    NULL,    /* CFP_TCAM_IPV4_S0_MASK */
    NULL,    /* CFP_TCAM_IPV4_S1_MASK */
    NULL,    /* CFP_TCAM_IPV4_S2_MASK */
    NULL,    /* CFP_TCAM_IPV4_SC */
    NULL,    /* CFP_TCAM_IPV6_MASK */
    NULL,    /* CFP_TCAM_IPV6_S0 */
    NULL,    /* CFP_TCAM_IPV6_S1 */
    NULL,    /* CFP_TCAM_IPV6_S2 */
    NULL,    /* CFP_TCAM_IPV6_S0_MASK */
    NULL,    /* CFP_TCAM_IPV6_S1_MASK */
    NULL,    /* CFP_TCAM_IPV6_S2_MASK */
    NULL,    /* CFP_TCAM_IPV6_SC */
    NULL,    /* CFP_TCAM_MASK */
    NULL,    /* CFP_TCAM_NONIP_MASK */
    NULL,    /* CFP_TCAM_NONIP_SC */
    NULL,    /* CFP_TCAM_S0 */
    NULL,    /* CFP_TCAM_S1 */
    NULL,    /* CFP_TCAM_S2 */
    NULL,    /* CFP_TCAM_S3 */
    NULL,    /* CFP_TCAM_S4 */
    NULL,    /* CFP_TCAM_S5 */
    NULL,    /* CFP_TCAM_SC */
    NULL,    /* DPTC2PCP */
    NULL,    /* DSCPECN2TCDP */
    NULL,    /* EGRESS_VID_REMARK */
    NULL,    /* ERC_PORT */
    NULL,    /* EVM_ACT */
    NULL,    /* EVM_KEY_DATA */
    NULL,    /* EVM_KEY_DATA_MASK */
    NULL,    /* EVM_KEY_MASK */
    NULL,    /* FLOW2VLAN */
    &soc_robo_mem_list[SOC_MEM_INT_GEN_MEMORYm_ROBO],
    NULL,    /* INT_8051_RAM */
    NULL,    /* INT_8051_ROM */
    NULL,    /* IRC_PORT */
    NULL,    /* IVM_ACT */
    NULL,    /* IVM_KEY_DATA_0 */
    NULL,    /* IVM_KEY_DATA_1 */
    NULL,    /* IVM_KEY_DATA_2 */
    NULL,    /* IVM_KEY_DATA_3 */
    NULL,    /* IVM_KEY_DATA_MASK */
    NULL,    /* IVM_KEY_MASK_0 */
    NULL,    /* IVM_KEY_MASK_1 */
    NULL,    /* IVM_KEY_MASK_2 */
    NULL,    /* IVM_KEY_MASK_3 */
    &soc_robo_mem_list[SOC_MEM_INT_L2_ARL_BCM53118_A0m_ROBO],
    &soc_robo_mem_list[SOC_MEM_INT_L2_ARL_SW_BCM5395_A0m_ROBO],
    NULL,    /* L2_MARL */
    &soc_robo_mem_list[SOC_MEM_INT_L2_MARL_SW_BCM5395_A0m_ROBO],
    NULL,    /* MAC2VLAN */
    NULL,    /* MARL_PBMP */
    NULL,    /* MCAST_VPORT_MAP */
    &soc_robo_mem_list[SOC_MEM_INT_MSPT_TAB_BCM53118_A0m_ROBO],
    NULL,    /* PCP2DPTC */
    NULL,    /* PORT_MASK */
    NULL,    /* PROTOCOL2VLAN */
    NULL,    /* SA_LRN_CNT */
    NULL,    /* STSEC_COUNTER0 */
    NULL,    /* STSEC_COUNTER1 */
    NULL,    /* STSEC_COUNTER2 */
    NULL,    /* STSEC_MAC0 */
    NULL,    /* STSEC_MAC1 */
    NULL,    /* STSEC_MAC2 */
    NULL,    /* TCDP2DSCPECN */
    NULL,    /* VLAN2VLAN */
    &soc_robo_mem_list[SOC_MEM_INT_VLAN_1Q_BCM5395_A0m_ROBO],
    NULL     /* VPORT_VID_MAP */
};

/*
 * Packet Statistics Counter Map for bcm53118_a0
 *
 * NOTE: soc_attach verifies this map is correct and prints warnings if
 * not. The map should contain only registers with a single field named
 * COUNT, and all such registers should be in the map.
 *
 * The soc_counter_map array is a list of counter registers in the order
 * found in the internal address map and counter DMA buffer.
 * counter_map[0 to NUM_COUNTER-1] corresponds to internal addresses
 * COUNTER_REG_FIRST through COUNTER_REG_LAST.
 *
 * This map structure, contents, and size are exposed only to provide a
 * convenient way to loop through all available counters.
 */

static soc_ctr_ref_t _ge_counters_bcm53118_a0[] = {
    {INDEX(      TXOCTETSr), 0}, /* 0x000 */
    {INDEX(     INVALID_Rr), 0}, /* 0x004 */
    {INDEX(    TXDROPPKTSr), 0}, /* 0x008 */
    {INDEX(      TXQPKTQ0r), 0}, /* 0x00c */
    {INDEX(TXBROADCASTPKTSr), 0}, /* 0x010 */
    {INDEX(TXMULTICASTPKTSr), 0}, /* 0x014 */
    {INDEX( TXUNICASTPKTSr), 0}, /* 0x018 */
    {INDEX(  TXCOLLISIONSr), 0}, /* 0x01c */
    {INDEX(TXSINGLECOLLISIONr), 0}, /* 0x020 */
    {INDEX(TXMULTIPLECOLLISIONr), 0}, /* 0x024 */
    {INDEX(TXDEFERREDTRANSMITr), 0}, /* 0x028 */
    {INDEX(TXLATECOLLISIONr), 0}, /* 0x02c */
    {INDEX(TXEXCESSIVECOLLISIONr), 0}, /* 0x030 */
    {INDEX( TXFRAMEINDISCr), 0}, /* 0x034 */
    {INDEX(   TXPAUSEPKTSr), 0}, /* 0x038 */
    {INDEX(      TXQPKTQ1r), 0}, /* 0x03c */
    {INDEX(      TXQPKTQ2r), 0}, /* 0x040 */
    {INDEX(      TXQPKTQ3r), 0}, /* 0x044 */
    {INDEX(      TXQPKTQ4r), 0}, /* 0x048 */
    {INDEX(      TXQPKTQ5r), 0}, /* 0x04c */
    {INDEX(      RXOCTETSr), 0}, /* 0x050 */
    {INDEX(     INVALID_Rr), 0}, /* 0x054 */
    {INDEX(RXUNDERSIZEPKTSr), 0}, /* 0x058 */
    {INDEX(   RXPAUSEPKTSr), 0}, /* 0x05c */
    {INDEX(  PKTS64OCTETSr), 0}, /* 0x060 */
    {INDEX(PKTS65TO127OCTETSr), 0}, /* 0x064 */
    {INDEX(PKTS128TO255OCTETSr), 0}, /* 0x068 */
    {INDEX(PKTS256TO511OCTETSr), 0}, /* 0x06c */
    {INDEX(PKTS512TO1023OCTETSr), 0}, /* 0x070 */
    {INDEX(PKTS1024TOMAXPKTOCTETSr), 0}, /* 0x074 */
    {INDEX(RXOVERSIZEPKTSr), 0}, /* 0x078 */
    {INDEX(     RXJABBERSr), 0}, /* 0x07c */
    {INDEX(RXALIGNMENTERRORSr), 0}, /* 0x080 */
    {INDEX(   RXFCSERRORSr), 0}, /* 0x084 */
    {INDEX(  RXGOODOCTETSr), 0}, /* 0x088 */
    {INDEX(     INVALID_Rr), 0}, /* 0x08c */
    {INDEX(    RXDROPPKTSr), 0}, /* 0x090 */
    {INDEX( RXUNICASTPKTSr), 0}, /* 0x094 */
    {INDEX(RXMULTICASTPKTSr), 0}, /* 0x098 */
    {INDEX(RXBROADCASTPKTr), 0}, /* 0x09c */
    {INDEX(   RXSACHANGESr), 0}, /* 0x0a0 */
    {INDEX(   RXFRAGMENTSr), 0}, /* 0x0a4 */
    {INDEX(      JUMBOPKTr), 0}, /* 0x0a8 */
    {INDEX(    RXSYMBLERRr), 0}, /* 0x0ac */
    {INDEX(INRANGEERRCOUNTr), 0}, /* 0x0b0 */
    {INDEX(OUTRANGEERRCOUNTr), 0}, /* 0x0b4 */
    {INDEX(     INVALID_Rr), 0}, /* 0x0b8 */
    {INDEX(     INVALID_Rr), 0}, /* 0x0bc */
    {INDEX(     RXDISCARDr), 0}, /* 0x0c0 */
};

/*
 * The array to put into chip parameters.
 * This array is indexed by SOC_CTR_TYPE_xxx (soc_ctr_types_t)
 */
static soc_cmap_t soc_counter_maps_bcm53118_a0[SOC_CTR_NUM_TYPES] = {
    {NULL, 0},                        /* FE */
    {_ge_counters_bcm53118_a0, 49},    /* GE */
    {NULL, 0},                        /* GFE */
    {NULL, 0},                        /* HG */
    {NULL, 0},                         /* XE */
    {NULL, 0},                        /* CPU */
    {NULL, 0},                         /* RX */
    {NULL, 0}                         /* TX */
};

static soc_block_info_t soc_blocks_bcm53118_a0[] = {
	{ SOC_BLK_CPIC,	0,	0,	8	},	/* 0 C0 */
	{ SOC_BLK_EXP,	0,	0,	9	},	/* 1 E0 */
	{ SOC_BLK_GPIC,	0,	0,	0	},	/* 2 G0 */
	{ SOC_BLK_GPIC,	1,	0,	1	},	/* 3 G1 */
	{ SOC_BLK_GPIC,	2,	0,	2	},	/* 4 G2 */
	{ SOC_BLK_GPIC,	3,	0,	3	},	/* 5 G3 */
	{ SOC_BLK_GPIC,	4,	0,	4	},	/* 6 G4 */
	{ SOC_BLK_GPIC,	5,	0,	5	},	/* 7 G5 */
	{ SOC_BLK_GPIC,	6,	0,	6	},	/* 8 G6 */
	{ SOC_BLK_GPIC,	7,	0,	7	},	/* 9 G7 */
	{ SOC_BLK_SPI,	0,	0,	10	},	/* 10 S0 */
	{ SOC_BLK_SYS,	0,	0,	11	},	/* 11 S0 */
	{ -1,		-1,	-1,	-1	}	/* end */
};

static soc_port_info_t soc_ports_bcm53118_a0[] = {
	{ 2,	0	},	/* 0 G0.0 */
	{ 3,	0	},	/* 1 G1.0 */
	{ 4,	0	},	/* 2 G2.0 */
	{ 5,	0	},	/* 3 G3.0 */
	{ 6,	0	},	/* 4 G4.0 */
	{ 7,	0	},	/* 5 G5.0 */
	{ 8,	0	},	/* 6 G6.0 */
	{ 9,	0	},	/* 7 G7.0 */
	{ 0,	0	},	/* 8 C0.0 */
	{ -1,	-1	}	/* end */
};

/* Forward declaration of init function */
static void chip_init_bcm53118_a0(void);

soc_driver_t soc_driver_bcm53118_a0 = {
	/* type           */	SOC_CHIP_BCM53118_A0,
	/* chip_string    */	"blackbird",
	/* origin         */	" Not located in Server Need Verified",
	/* pci_vendor     */	BROADCOM_VENDOR_ID,
	/* pci_device     */	BCM53118_DEVICE_ID,
	/* pci_revision   */	BCM53118_A0_REV_ID,
	/* num_cos        */	4,
	/* reg_info       */	soc_registers_bcm53118_a0,
	/* mem_info       */	soc_memories_bcm53118_a0,
	/* soc_mem_t      */	NULL,
	/* block_info     */	soc_blocks_bcm53118_a0,
	/* port_info      */	soc_ports_bcm53118_a0,
	/* counter_maps   */	soc_counter_maps_bcm53118_a0,
	/* features       */	soc_features_bcm53118_a0,
	/* init           */	chip_init_bcm53118_a0,
	/* services       */	&drv_bcm53118_services
};  /* soc_driver */

/* Chip specific bottom matter from memory file */

/****************************************************************
 *
 * Function:    chip_init_bcm53118_a0
 * Purpose:
 *     Initialize software internals for bcm53118_a0 device:
 *         Initialize null memories
 * Parameters:  void
 * Returns:     void
 *
 ****************************************************************/
static void
chip_init_bcm53118_a0(void)
{

}

/* End of chip specific bottom matter */

#endif /* BCM_53118_A0 */
