/*
 *
 * $Id: g2xx_pp_rule_encode.h 1.4.108.1 Broadcom SDK $
 * $Copyright: Copyright 2011 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 * g2xx_pp_rule_encode.h: Guadalupe2k V1.3 PPE rule encoding header file
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 * Script can be found at TBD
 */

#ifndef _SB_G2XX_FE_PP_RULE_ENCODE_H_
#define _SB_G2XX_FE_PP_RULE_ENCODE_H_

#include <soc/error.h>

/*
 * Cam Entry
 */

typedef struct {
    uint32_t m_uMask6;
    uint32_t m_uMask5;
    uint32_t m_uMask4;
    uint32_t m_uMask3;
    uint32_t m_uMask2;
    uint32_t m_uMask1;
    uint32_t m_uMask0;
    uint32_t m_uData6;
    uint32_t m_uData5;
    uint32_t m_uData4;
    uint32_t m_uData3;
    uint32_t m_uData2;
    uint32_t m_uData1;
    uint32_t m_uData0;
    uint32_t m_uValid;
} sbG2XXFePpCamEntry_t;

void
sbG2XXFePpCamEntry_Init(sbG2XXFePpCamEntry_t *pCam);

void
sbG2XXFePpCamEntry_Pack(int unit, sbG2XXFePpCamEntry_t *pFr, uint8_t *pTo);

void
sbG2XXFePpCamEntry_Unpack(int unit, sbG2XXFePpCamEntry_t *pTo, uint8_t *pFr);

/*
 * Ram Entry
 */

typedef struct {
    uint32_t m_uLengthUnits;
    uint32_t m_uLengthMask;
    uint32_t m_uLengthPtr;
    uint32_t m_uStateMask;
    uint32_t m_uState;
    uint32_t m_uHashStart;
    uint32_t m_uHashTemplateId;
    uint32_t m_uCheckerOffset;
    uint32_t m_uCheckerType;
    uint32_t m_uHeaderAValid;
    uint32_t m_uHeaderAType;
    uint32_t m_uHeaderALength;
    uint32_t m_uHeaderBValid;
    uint32_t m_uHeaderBType;
    uint32_t m_uHeaderBLength;
    uint32_t m_uShift;
    uint32_t m_uVariableMask;
    uint32_t m_uVariable;
} sbG2XXFePpRamEntry_t;

void
sbG2XXFePpRamEntry_Init(sbG2XXFePpRamEntry_t *pRam);

void
sbG2XXFePpRamEntry_Pack(int unit, sbG2XXFePpRamEntry_t *pFr, uint8_t *pTo);

void
sbG2XXFePpRamEntry_Unpack(int unit, sbG2XXFePpRamEntry_t *pTo, uint8_t *pFr);

/*
 * Cam State
 */

typedef struct {
    uint32_t customer;
    uint32_t provider;
    uint32_t oamloop;
    uint32_t tpid;
    uint32_t twintpid;
    uint32_t pbb;
    uint32_t ipv4mc;
    uint32_t lsmmatch;
    uint32_t uState;
    uint32_t portid;
} sbG2XXFePpCamState_t;

void
sbG2XXFePpCamState_Init(sbG2XXFePpCamState_t *pCam);

#define SB_G2XX_FE_PP_CAM_STATE_PACK(x) ( 0x000000 \
   | (x.customer << 0) \
   | (x.provider << 1) \
   | (x.oamloop << 2) \
   | (x.tpid << 3) \
   | (x.twintpid << 4) \
   | (x.pbb << 5) \
   | (x.ipv4mc << 6) \
   | (x.lsmmatch << 7) \
   | (x.uState << 8) \
   | (x.portid << 16) \
)

typedef enum {
    SB_G2XX_FE_PP_CAM_STATE_CODE_CT,
    SB_G2XX_FE_PP_CAM_STATE_CODE_PT0,
    SB_G2XX_FE_PP_CAM_STATE_CODE_PT1,
    SB_G2XX_FE_PP_CAM_STATE_CODE_OL,
    SB_G2XX_FE_PP_CAM_STATE_CODE_TT,
    SB_G2XX_FE_PP_CAM_STATE_CODE_PBB,
    SB_G2XX_FE_PP_CAM_STATE_CODE_V4MC,
    SB_G2XX_FE_PP_CAM_STATE_CODE_LSM,
    SB_G2XX_FE_PP_CAM_STATE_CODE_NON_LSM,
    SB_G2XX_FE_PP_CAM_STATE_CODE_DONT_CARE,
    SB_G2XX_FE_PP_CAM_STATE_CODE_MAX
} sbG2XXFePpCamStateCode_t;

sbStatus_t
sbG2XXFePpCamStateCode_Decode(
    sbG2XXFePpCamState_t *pCamStateData,
    sbG2XXFePpCamState_t *pCamStateMask,
    sbG2XXFePpCamStateCode_t camStateCode
);

#define SB_G2XX_FE_PP_CAM_STATE_PACK_N(x) ( \
     0xffffff - (0x000000 \
                 | (x.customer << 0) \
                 | (x.provider << 1) \
                 | (x.oamloop << 2) \
                 | (x.tpid << 3) \
                 | (x.twintpid << 4) \
                 | (x.pbb << 5) \
                 | (x.ipv4mc << 6) \
                 | (x.lsmmatch << 7) \
                 | (x.uState << 8) \
                 | (x.portid << 16) \
                ) \
)

typedef enum {
    SB_G2XX_FE_PP_CAM_UPDATE_CODE_LSM,
    SB_G2XX_FE_PP_CAM_UPDATE_CODE_NON_LSM,
    SB_G2XX_FE_PP_CAM_UPDATE_CODE_NO_CHANGE,
    SB_G2XX_FE_PP_CAM_UPDATE_CODE_MAX
} sbG2XXFePpCamUpdateCode_t;

sbStatus_t
sbG2XXFePpCamUpdateCode_Decode(
    sbG2XXFePpCamState_t *pRamStateData,
    sbG2XXFePpCamState_t *pRamStateMask,
    sbG2XXFePpCamUpdateCode_t camUpdateCode
);

/*
 * Ram Variable
 */

typedef struct {
    uint32_t stream;
    uint32_t mim_transit;
    uint32_t lsm;
    uint32_t numlbs;
    uint32_t oamen;
    uint32_t loopback;
    uint32_t lm_enable;
    uint32_t dm_enable;
    uint32_t vrrp;
    uint32_t pwe_ping;
    uint32_t pwe_y1731;
    uint32_t pwe_bfd;
    uint32_t lsp_gal;
    uint32_t traffictype;
    uint32_t l2cp;
    uint32_t l2cpslow;
    uint32_t pim;
    uint32_t igmp;
    uint32_t oamloop;
} sbG2XXFePpRamVariable_t;

void
sbG2XXFePpRamVariable_Init(sbG2XXFePpRamVariable_t *pRam);

#define SB_G2XX_FE_PP_RAM_VARIABLE_PACK(x) ( 0x00000000 \
   | (x.stream << 0) \
   | (x.mim_transit << 3) \
   | (x.lsm << 4) \
   | (x.numlbs << 6) \
   | (x.oamen << 10) \
   | (x.loopback << 11) \
   | (x.lm_enable << 12) \
   | (x.dm_enable << 13) \
   | (x.vrrp << 15) \
   | (x.pwe_ping << 20) \
   | (x.pwe_y1731 << 21) \
   | (x.pwe_bfd << 22) \
   | (x.lsp_gal << 23) \
   | (x.traffictype << 24) \
   | (x.l2cp << 27) \
   | (x.l2cpslow << 28) \
   | (x.pim << 29) \
   | (x.igmp << 30) \
   | (x.oamloop << 31) \
)

typedef enum {
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_MIM_TRANSIT,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LSM,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_NON_LSM,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LABEL0,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LABEL1,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LABEL2,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LABEL3,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_OamLabelPresent,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LOOPBACK,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_lm_enable,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_dm_enable,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_VRRP,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_PWE3_LSP_PING,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_PWE3_Y1731,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_PWE3_BFD,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LSP_GAL,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LSP_PING,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LSP_Y1731,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_LSP_BFD,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_MULTICAST,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_BROADCAST,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_L2CP,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_L2CPSLOW,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_IPV4_PIM,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_IGMP,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_PREFIX5,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_BAD_LABEL,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_FOUR_LABEL,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_CATCH_ALL,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_NO_CHANGE,
    SB_G2XX_FE_PP_RAM_VARIABLE_CODE_MAX
} sbG2XXFePpRamVariableCode_t;

sbStatus_t
sbG2XXFePpRamVariableCode_Decode(
    sbG2XXFePpRamVariable_t *pRamVariable,
    sbG2XXFePpRamVariable_t *pRamVariableMask,
    sbG2XXFePpRamVariableCode_t ramVariableCode
);


/* CAM0 */
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_00_ENTRY 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_01_ENTRY 1
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_02_ENTRY 2
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_03_ENTRY 3
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_04_ENTRY 4
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_05_ENTRY 5
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_06_ENTRY 6
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_07_ENTRY 7
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_08_ENTRY 8
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_09_ENTRY 9
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_10_ENTRY 10
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_11_ENTRY 11
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_12_ENTRY 12
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_13_ENTRY 13
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_14_ENTRY 14
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_15_ENTRY 15
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_16_ENTRY 16
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_17_ENTRY 17
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_18_ENTRY 18
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_19_ENTRY 19
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_20_ENTRY 20
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_21_ENTRY 21
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_22_ENTRY 22
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_23_ENTRY 23
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_24_ENTRY 24
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_25_ENTRY 25
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_26_ENTRY 26
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_27_ENTRY 27
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_28_ENTRY 28
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_29_ENTRY 29
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_30_ENTRY 30
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_31_ENTRY 31
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_32_ENTRY 32
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_33_ENTRY 33
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_34_ENTRY 34
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_35_ENTRY 35
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_36_ENTRY 36
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_37_ENTRY 37
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_38_ENTRY 38
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_39_ENTRY 39
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_40_ENTRY 40
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_41_ENTRY 41
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_42_ENTRY 42
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_43_ENTRY 43
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_44_ENTRY 44
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_45_ENTRY 45
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_46_ENTRY 46
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_47_ENTRY 47
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_48_ENTRY 48
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_49_ENTRY 49
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_50_ENTRY 50
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_51_ENTRY 51
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_52_ENTRY 52
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_53_ENTRY 53
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_54_ENTRY 54
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_55_ENTRY 55
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_56_ENTRY 56
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_57_ENTRY 57
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_58_ENTRY 58
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_59_ENTRY 59
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_60_ENTRY 60
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_61_ENTRY 61
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_62_ENTRY 62
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_63_ENTRY 63
#define SB_G2XX_FE_PP_RULE_S0_ETH_IPMULTICAST_ENTRY 64
#define SB_G2XX_FE_PP_RULE_S0_ETH_BROADCAST_ENTRY 65
#define SB_G2XX_FE_PP_RULE_S0_ETH_MULTICAST_ENTRY 66
#define SB_G2XX_FE_PP_RULE_S0_ETH_COMMON_ENTRY 67
#define SB_G2XX_FE_PP_RULE_S0_EGR_ERH_ENTRY 68
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_VLAN_TPID0_ENTRY 69
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_VLAN_TPID1_ENTRY 70
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_VLAN_TPID2_ENTRY 71
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_TPID0_ENTRY 72
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_TPID1_ENTRY 73
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_TPID2_ENTRY 74
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_ENTRY 75
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_IPV4_ENTRY 76
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_UNKNOWN_ENTRY 77
#define SB_G2XX_FE_PP_RULE_S1_EGR_ETYPE1_VLAN_ENTRY 78
#define SB_G2XX_FE_PP_RULE_S1_EGR_ETYPE1_IPV4_ENTRY 79
#define SB_G2XX_FE_PP_RULE_S1_EGR_ETYPE1_UNKNOWN_ENTRY 80
#define SB_G2XX_FE_PP_RULE_PAUSE_CAM0_ENTRY 81
#define SB_G2XX_FE_PP_RULE_MAX_CAM0 82

/* CAM1 */
#define SB_G2XX_FE_PP_RULE_S2_VLAN_IPV4_ENTRY 0
#define SB_G2XX_FE_PP_RULE_S2_VLAN_UNKNOWN_ENTRY 1
#define SB_G2XX_FE_PP_RULE_S2_EGR_VLAN_IPV4_ENTRY 2
#define SB_G2XX_FE_PP_RULE_S2_EGR_VLAN_UNKNOWN_ENTRY 3
#define SB_G2XX_FE_PP_RULE_PAUSE_CAM1_ENTRY 4
#define SB_G2XX_FE_PP_RULE_MAX_CAM1 5

/* CAM2 */
#define SB_G2XX_FE_PP_RULE_S4_ETYPE2_IPV4_ENTRY 0
#define SB_G2XX_FE_PP_RULE_S4_ETYPE2_UNKNOWN_ENTRY 1
#define SB_G2XX_FE_PP_RULE_S4_EGR_ETYPE2_IPV4_ENTRY 2
#define SB_G2XX_FE_PP_RULE_S4_EGR_ETYPE2_UNKNOWN_ENTRY 3
#define SB_G2XX_FE_PP_RULE_PAUSE_CAM2_ENTRY 4
#define SB_G2XX_FE_PP_RULE_MAX_CAM2 5

/* CAM3 */
#define SB_G2XX_FE_PP_RULE_S6_ETYPE3_ENTRY 0
#define SB_G2XX_FE_PP_RULE_S6_VLAN2_UNKNOWN_ENTRY 1
#define SB_G2XX_FE_PP_RULE_S6_IPV4_TCP_ENTRY 2
#define SB_G2XX_FE_PP_RULE_S6_IPV4_UDP_ENTRY 3
#define SB_G2XX_FE_PP_RULE_S6_IPV4_PIM_ENTRY 4
#define SB_G2XX_FE_PP_RULE_S6_IPV4_IGMP_ENTRY 5
#define SB_G2XX_FE_PP_RULE_S6_IPV4_UNKNOWN_ENTRY 6
#define SB_G2XX_FE_PP_RULE_S6_EGR_IPV4_ENTRY 7
#define SB_G2XX_FE_PP_RULE_S7_L4_HASH_ROUTE_ENTRY 8
#define SB_G2XX_FE_PP_RULE_S7_L4_HASH_ENTRY 9
#define SB_G2XX_FE_PP_RULE_S7_L4_NO_HASH_ROUTE_ENTRY 10
#define SB_G2XX_FE_PP_RULE_S7_L4_NO_HASH_ENTRY 11
#define SB_G2XX_FE_PP_RULE_S7_EGR_L4_ENTRY 12
#define SB_G2XX_FE_PP_RULE_PAUSE_CAM3_ENTRY 13
#define SB_G2XX_FE_PP_RULE_MAX_CAM3 14


/* CAM0 */
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_00_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_01_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_02_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_03_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_04_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_05_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_06_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_07_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_08_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_09_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_10_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_11_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_12_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_13_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_14_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_15_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_16_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_17_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_18_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_19_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_20_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_21_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_22_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_23_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_24_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_25_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_26_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_27_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_28_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_29_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_30_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_31_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_32_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_33_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_34_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_35_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_36_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_37_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_38_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_39_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_40_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_41_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_42_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_43_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_44_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_45_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_46_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_47_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_48_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_49_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_50_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_51_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_52_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_53_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_54_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_55_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_56_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_57_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_58_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_59_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_60_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_61_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_62_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_LSM_63_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_IPMULTICAST_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_BROADCAST_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_MULTICAST_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_ETH_COMMON_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S0_EGR_ERH_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_VLAN_TPID0_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_VLAN_TPID1_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_VLAN_TPID2_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_TPID0_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_TPID1_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_TPID2_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_VLAN_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_IPV4_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_ETYPE1_UNKNOWN_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_EGR_ETYPE1_VLAN_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_EGR_ETYPE1_IPV4_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_S1_EGR_ETYPE1_UNKNOWN_CAM_ID 0
#define SB_G2XX_FE_PP_RULE_PAUSE_CAM0_CAM_ID 0

/* CAM1 */
#define SB_G2XX_FE_PP_RULE_S2_VLAN_IPV4_CAM_ID 1
#define SB_G2XX_FE_PP_RULE_S2_VLAN_UNKNOWN_CAM_ID 1
#define SB_G2XX_FE_PP_RULE_S2_EGR_VLAN_IPV4_CAM_ID 1
#define SB_G2XX_FE_PP_RULE_S2_EGR_VLAN_UNKNOWN_CAM_ID 1
#define SB_G2XX_FE_PP_RULE_PAUSE_CAM1_CAM_ID 1

/* CAM2 */
#define SB_G2XX_FE_PP_RULE_S4_ETYPE2_IPV4_CAM_ID 2
#define SB_G2XX_FE_PP_RULE_S4_ETYPE2_UNKNOWN_CAM_ID 2
#define SB_G2XX_FE_PP_RULE_S4_EGR_ETYPE2_IPV4_CAM_ID 2
#define SB_G2XX_FE_PP_RULE_S4_EGR_ETYPE2_UNKNOWN_CAM_ID 2
#define SB_G2XX_FE_PP_RULE_PAUSE_CAM2_CAM_ID 2

/* CAM3 */
#define SB_G2XX_FE_PP_RULE_S6_ETYPE3_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S6_VLAN2_UNKNOWN_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S6_IPV4_TCP_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S6_IPV4_UDP_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S6_IPV4_PIM_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S6_IPV4_IGMP_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S6_IPV4_UNKNOWN_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S6_EGR_IPV4_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S7_L4_HASH_ROUTE_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S7_L4_HASH_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S7_L4_NO_HASH_ROUTE_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S7_L4_NO_HASH_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_S7_EGR_L4_CAM_ID 3
#define SB_G2XX_FE_PP_RULE_PAUSE_CAM3_CAM_ID 3


/*
 * Parsing State
 */
#define SB_G2XX_FE_PP_PARSE_ENTER        (0x00)
#define SB_G2XX_FE_PP_PARSE_EGR_ENTER    (0x80)
#define SB_G2XX_FE_PP_PARSE_ETH 1
#define SB_G2XX_FE_PP_PARSE_EGR_ETH 2
#define SB_G2XX_FE_PP_PARSE_VLAN 3
#define SB_G2XX_FE_PP_PARSE_EGR_VLAN 4
#define SB_G2XX_FE_PP_PARSE_ETYPE2_SNAP 5
#define SB_G2XX_FE_PP_PARSE_EGR_ETYPE2 6
#define SB_G2XX_FE_PP_PARSE_ETYPE3 7
#define SB_G2XX_FE_PP_PARSE_VLAN2 8
#define SB_G2XX_FE_PP_PARSE_IPV4 9
#define SB_G2XX_FE_PP_PARSE_EGR_IPV4 10
#define SB_G2XX_FE_PP_PARSE_L4_HASH 11
#define SB_G2XX_FE_PP_PARSE_L4 12
#define SB_G2XX_FE_PP_PARSE_EGR_L4 13
#define SB_G2XX_FE_PP_PARSE_DONT_CARE    (0xFE)
#define SB_G2XX_FE_PP_PARSE_EGR_STOP     (0xFF)
#define SB_G2XX_FE_PP_PARSE_STOP         (0xFF)


/*
 * TPID re-config
 */

sbStatus_t
soc_sbx_g2xx_pp_tpid_config(int unit, uint8_t bTpidSelect, uint32_t uTpid);

/*
 * HASH re-config
 */

sbStatus_t
soc_sbx_g2xx_pp_psc_config(int unit, uint32_t fieldMask);

sbStatus_t
soc_sbx_g2xx_pp_rule_encode(int unit);


#endif /* _SB_G2XX_FE_PP_RULE_ENCODE_H_ */
