/*
 * Normally, this file is autogenerated, but for SBX we are doing it by hand
 *
 * $Id: allenum.h 1.10 Broadcom SDK $
 * $Copyright: Copyright 2011 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 */

#ifndef _SOC_SBX_ALLENUM_H
#define _SOC_SBX_ALLENUM_H


#ifndef EXTERN
# ifdef __cplusplus
#  define EXTERN extern "C"
# else
#  define EXTERN extern
# endif
#endif

/****************************************************************
 *
 * BCM Chip Support options.
 *
 * If NO_BCM_<chip> is defined, do not define BCM_<chip>.  This
 * avoids adding support for the chip.  NO_BCM_<chip> can be added
 * to Make.local.
 ****************************************************************/

#ifdef BCM_SBX_SUPPORT
#if !defined(NO_BCM_QE2000_A0)
#if !defined(NO_BCM_QE2000_A1)
#define BCM_QE2000_A1
#endif
#if !defined(NO_BCM_QE2000_A2)
#define BCM_QE2000_A2
#endif
#if !defined(NO_BCM_QE2000_A3)
#define BCM_QE2000_A3
#endif
#endif
#if !defined(NO_BCM_BME3200_A0)
#define BCM_BME3200_A0
#endif
#if !defined(NO_BCM_BME3200_B0)
#define BCM_BME3200_B0
#endif
#if !defined(NO_BCM_BM9600_A0)
#define BCM_BM9600_A0
#if !defined(NO_BCM_BM9600_A1)
#define BCM_BM9600_A1
#endif
#if !defined(NO_BCM_BM9600_B0)
#define BCM_BM9600_B0
#endif
#endif
#if !defined(NO_BCM_FE2000_A0)
#define BCM_FE2000_A0
#endif
#endif

#if defined(BCM_QE2000_A1) || defined(BCM_QE2000_A2) || defined(BCM_QE2000_A3)
#if   96 > SOC_MAX_NUM_PORTS
#undef  SOC_MAX_NUM_PORTS
#define SOC_MAX_NUM_PORTS       96
#endif
#endif /* BCM_QE2000_A1 || BCM_QE2000_A2 || BCM_QE2000_A3 */

#if defined(BCM_BME3200_A0) || defined(BCM_BME3200_B0)
#if   40 > SOC_MAX_NUM_PORTS
#undef  SOC_MAX_NUM_PORTS
#define SOC_MAX_NUM_PORTS       40
#endif
#endif /* BCM_BME3200_A0 || BCM_BME3200_B0 */

#if defined(BCM_BM9600_A0) || defined(BCM_BM9600_A1) || defined(BCM_BM9600_B0)
#if   96 > SOC_MAX_NUM_PORTS
#undef  SOC_MAX_NUM_PORTS
#define SOC_MAX_NUM_PORTS       96
#endif
#endif /* BCM_BM9600_A0 */

#if defined(BCM_FE2000_A0) || defined(BCM_FE2000_A1)
#if   64 > SOC_MAX_NUM_PORTS
#undef  SOC_MAX_NUM_PORTS
#define SOC_MAX_NUM_PORTS       64
#endif
#endif /* BCM_FE2000_A0 || BCM_FE2000_A1 */

#endif	/* !_SOC_SBX_ALLENUM_H */
