
/*
 *$Id: hal_ma_auto_ex.h 1.2 Broadcom SDK $
 * $Copyright: Copyright 2011 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 */

/*
  #defines work with HAL _IDX routines, providing indexed access to register sets.
 */
#ifndef HAL_MA_AUTO_EX_H 
#define HAL_MA_AUTO_EX_H 



#ifndef SAND_HAL_REG_OFFSET_IDX
#define SAND_HAL_REG_OFFSET_IDX(device,reg,idx) \
	(SAND_HAL_##device##_##reg##_OFFSET + \
	SAND_HAL_##device##_##reg##_STRIDE*(idx))

#define SAND_HAL_READ_IDX(addr,device,reg,idx) SAND_HAL_READ_OFFS((addr), \
	SAND_HAL_REG_OFFSET_IDX(device,reg,(idx)))

#define SAND_HAL_WRITE_IDX(addr,device,reg,idx,value) SAND_HAL_WRITE_OFFS((addr), \
	SAND_HAL_REG_OFFSET_IDX(device,reg,(idx)),(value))

#define SAND_HAL_RMW_FIELD_IDX(addr,device,reg,idx,field,fieldValue) \
	do { \
	UINT nRegValue; \
	nRegValue=SAND_HAL_READ_IDX(addr,device,reg,idx); \
	nRegValue=SAND_HAL_MOD_FIELD(device,reg,field,nRegValue,(fieldValue)); \
	SAND_HAL_WRITE_IDX(addr,device,reg,idx,nRegValue); \
	}while(0)
#endif

/* Registers */

#define SAND_HAL_MA_QI_DEBUG_MUX_OFFSET SAND_HAL_MA_QI0_DEBUG_MUX_OFFSET
#define SAND_HAL_MA_QI_DEBUG_MUX_MASK SAND_HAL_MA_QI0_DEBUG_MUX_MASK
#define SAND_HAL_MA_QI_DEBUG_MUX_MSB SAND_HAL_MA_QI0_DEBUG_MUX_MSB
#define SAND_HAL_MA_QI_DEBUG_MUX_LSB SAND_HAL_MA_QI0_DEBUG_MUX_LSB

#define SAND_HAL_MA_QI_STATUS_OFFSET SAND_HAL_MA_QI0_STATUS_OFFSET
#define SAND_HAL_MA_QI_STATUS_MASK SAND_HAL_MA_QI0_STATUS_MASK
#define SAND_HAL_MA_QI_STATUS_MSB SAND_HAL_MA_QI0_STATUS_MSB
#define SAND_HAL_MA_QI_STATUS_LSB SAND_HAL_MA_QI0_STATUS_LSB

#define SAND_HAL_MA_SI_STICKY_STATE_STATUS_OFFSET SAND_HAL_MA_SI0_STICKY_STATE_STATUS_OFFSET
#define SAND_HAL_MA_SI_STICKY_STATE_STATUS_MASK SAND_HAL_MA_SI0_STICKY_STATE_STATUS_MASK
#define SAND_HAL_MA_SI_STICKY_STATE_STATUS_MSB SAND_HAL_MA_SI0_STICKY_STATE_STATUS_MSB
#define SAND_HAL_MA_SI_STICKY_STATE_STATUS_LSB SAND_HAL_MA_SI0_STICKY_STATE_STATUS_LSB

#define SAND_HAL_MA_SI_STATE_STATUS_OFFSET SAND_HAL_MA_SI0_STATE_STATUS_OFFSET
#define SAND_HAL_MA_SI_STATE_STATUS_MASK SAND_HAL_MA_SI0_STATE_STATUS_MASK
#define SAND_HAL_MA_SI_STATE_STATUS_MSB SAND_HAL_MA_SI0_STATE_STATUS_MSB
#define SAND_HAL_MA_SI_STATE_STATUS_LSB SAND_HAL_MA_SI0_STATE_STATUS_LSB

#define SAND_HAL_MA_SI_CONFIG1_OFFSET SAND_HAL_MA_SI0_CONFIG1_OFFSET
#define SAND_HAL_MA_SI_CONFIG1_MASK SAND_HAL_MA_SI0_CONFIG1_MASK
#define SAND_HAL_MA_SI_CONFIG1_MSB SAND_HAL_MA_SI0_CONFIG1_MSB
#define SAND_HAL_MA_SI_CONFIG1_LSB SAND_HAL_MA_SI0_CONFIG1_LSB

#define SAND_HAL_MA_SI_ERROR_OFFSET SAND_HAL_MA_SI0_ERROR_OFFSET
#define SAND_HAL_MA_SI_ERROR_MASK SAND_HAL_MA_SI0_ERROR_MASK
#define SAND_HAL_MA_SI_ERROR_MSB SAND_HAL_MA_SI0_ERROR_MSB
#define SAND_HAL_MA_SI_ERROR_LSB SAND_HAL_MA_SI0_ERROR_LSB

#define SAND_HAL_MA_QI_CONTROL_OFFSET SAND_HAL_MA_QI0_CONTROL_OFFSET
#define SAND_HAL_MA_QI_CONTROL_MASK SAND_HAL_MA_QI0_CONTROL_MASK
#define SAND_HAL_MA_QI_CONTROL_MSB SAND_HAL_MA_QI0_CONTROL_MSB
#define SAND_HAL_MA_QI_CONTROL_LSB SAND_HAL_MA_QI0_CONTROL_LSB

#define SAND_HAL_MA_SI_ERROR_MASK_OFFSET SAND_HAL_MA_SI0_ERROR_MASK_OFFSET
#define SAND_HAL_MA_SI_ERROR_MASK_MASK SAND_HAL_MA_SI0_ERROR_MASK_MASK
#define SAND_HAL_MA_SI_ERROR_MASK_MSB SAND_HAL_MA_SI0_ERROR_MASK_MSB
#define SAND_HAL_MA_SI_ERROR_MASK_LSB SAND_HAL_MA_SI0_ERROR_MASK_LSB

#define SAND_HAL_MA_SI_STATUS_OFFSET SAND_HAL_MA_SI0_STATUS_OFFSET
#define SAND_HAL_MA_SI_STATUS_MASK SAND_HAL_MA_SI0_STATUS_MASK
#define SAND_HAL_MA_SI_STATUS_MSB SAND_HAL_MA_SI0_STATUS_MSB
#define SAND_HAL_MA_SI_STATUS_LSB SAND_HAL_MA_SI0_STATUS_LSB

#define SAND_HAL_MA_QI_PACK_CNT0_OFFSET SAND_HAL_MA_QI0_PACK_CNT0_OFFSET
#define SAND_HAL_MA_QI_PACK_CNT0_MASK SAND_HAL_MA_QI0_PACK_CNT0_MASK
#define SAND_HAL_MA_QI_PACK_CNT0_MSB SAND_HAL_MA_QI0_PACK_CNT0_MSB
#define SAND_HAL_MA_QI_PACK_CNT0_LSB SAND_HAL_MA_QI0_PACK_CNT0_LSB

#define SAND_HAL_MA_SI_DEBUG_MUX_OFFSET SAND_HAL_MA_SI0_DEBUG_MUX_OFFSET
#define SAND_HAL_MA_SI_DEBUG_MUX_MASK SAND_HAL_MA_SI0_DEBUG_MUX_MASK
#define SAND_HAL_MA_SI_DEBUG_MUX_MSB SAND_HAL_MA_SI0_DEBUG_MUX_MSB
#define SAND_HAL_MA_SI_DEBUG_MUX_LSB SAND_HAL_MA_SI0_DEBUG_MUX_LSB

#define SAND_HAL_MA_QI_ERROR_MASK_OFFSET SAND_HAL_MA_QI0_ERROR_MASK_OFFSET
#define SAND_HAL_MA_QI_ERROR_MASK_MASK SAND_HAL_MA_QI0_ERROR_MASK_MASK
#define SAND_HAL_MA_QI_ERROR_MASK_MSB SAND_HAL_MA_QI0_ERROR_MASK_MSB
#define SAND_HAL_MA_QI_ERROR_MASK_LSB SAND_HAL_MA_QI0_ERROR_MASK_LSB

#define SAND_HAL_MA_QI_PACK_CNT1_OFFSET SAND_HAL_MA_QI0_PACK_CNT1_OFFSET
#define SAND_HAL_MA_QI_PACK_CNT1_MASK SAND_HAL_MA_QI0_PACK_CNT1_MASK
#define SAND_HAL_MA_QI_PACK_CNT1_MSB SAND_HAL_MA_QI0_PACK_CNT1_MSB
#define SAND_HAL_MA_QI_PACK_CNT1_LSB SAND_HAL_MA_QI0_PACK_CNT1_LSB

#define SAND_HAL_MA_QI_PACK_CNT2_OFFSET SAND_HAL_MA_QI0_PACK_CNT2_OFFSET
#define SAND_HAL_MA_QI_PACK_CNT2_MASK SAND_HAL_MA_QI0_PACK_CNT2_MASK
#define SAND_HAL_MA_QI_PACK_CNT2_MSB SAND_HAL_MA_QI0_PACK_CNT2_MSB
#define SAND_HAL_MA_QI_PACK_CNT2_LSB SAND_HAL_MA_QI0_PACK_CNT2_LSB

#define SAND_HAL_MA_QI_ERROR_OFFSET SAND_HAL_MA_QI0_ERROR_OFFSET
#define SAND_HAL_MA_QI_ERROR_MASK SAND_HAL_MA_QI0_ERROR_MASK
#define SAND_HAL_MA_QI_ERROR_MSB SAND_HAL_MA_QI0_ERROR_MSB
#define SAND_HAL_MA_QI_ERROR_LSB SAND_HAL_MA_QI0_ERROR_LSB

#define SAND_HAL_MA_SI_DEBUG_01_OFFSET SAND_HAL_MA_SI0_DEBUG_01_OFFSET
#define SAND_HAL_MA_SI_DEBUG_01_MASK SAND_HAL_MA_SI0_DEBUG_01_MASK
#define SAND_HAL_MA_SI_DEBUG_01_MSB SAND_HAL_MA_SI0_DEBUG_01_MSB
#define SAND_HAL_MA_SI_DEBUG_01_LSB SAND_HAL_MA_SI0_DEBUG_01_LSB

#define SAND_HAL_MA_SI_DEBUG_02_OFFSET SAND_HAL_MA_SI0_DEBUG_02_OFFSET
#define SAND_HAL_MA_SI_DEBUG_02_MASK SAND_HAL_MA_SI0_DEBUG_02_MASK
#define SAND_HAL_MA_SI_DEBUG_02_MSB SAND_HAL_MA_SI0_DEBUG_02_MSB
#define SAND_HAL_MA_SI_DEBUG_02_LSB SAND_HAL_MA_SI0_DEBUG_02_LSB

#define SAND_HAL_MA_SI_DEBUG_03_OFFSET SAND_HAL_MA_SI0_DEBUG_03_OFFSET
#define SAND_HAL_MA_SI_DEBUG_03_MASK SAND_HAL_MA_SI0_DEBUG_03_MASK
#define SAND_HAL_MA_SI_DEBUG_03_MSB SAND_HAL_MA_SI0_DEBUG_03_MSB
#define SAND_HAL_MA_SI_DEBUG_03_LSB SAND_HAL_MA_SI0_DEBUG_03_LSB


/* Register Strides */

#define SAND_HAL_MA_QI_DEBUG_MUX_STRIDE 4
#define SAND_HAL_MA_QI_STATUS_STRIDE 4
#define SAND_HAL_MA_SI_STICKY_STATE_STATUS_STRIDE 4
#define SAND_HAL_MA_SI_STATE_STATUS_STRIDE 4
#define SAND_HAL_MA_SI_CONFIG1_STRIDE 4
#define SAND_HAL_MA_SI_ERROR_STRIDE 4
#define SAND_HAL_MA_QI_CONTROL_STRIDE 4
#define SAND_HAL_MA_SI_ERROR_MASK_STRIDE 4
#define SAND_HAL_MA_SI_STATUS_STRIDE 4
#define SAND_HAL_MA_QI_PACK_CNT0_STRIDE 4
#define SAND_HAL_MA_SI_DEBUG_MUX_STRIDE 4
#define SAND_HAL_MA_QI_ERROR_MASK_STRIDE 4
#define SAND_HAL_MA_QI_PACK_CNT1_STRIDE 4
#define SAND_HAL_MA_QI_PACK_CNT2_STRIDE 4
#define SAND_HAL_MA_QI_ERROR_STRIDE 4
#define SAND_HAL_MA_SI_DEBUG_01_STRIDE 4
#define SAND_HAL_MA_SI_DEBUG_02_STRIDE 4
#define SAND_HAL_MA_SI_DEBUG_03_STRIDE 4

/* Register Fields */



#endif
