#
#   $Id: Makefile 1.3 Broadcom SDK $
# 
# 
# $Copyright: (c) 2010 Broadcom Corp.
# All Rights Reserved.$
#
# Makefile for ces/nemo_driver subdirectory
#
LOCALDIR = src/soc/ces/nemo_driver
CFLAGS = 
include ${SDK}/make/Make.config


lib = libsoc_nemo
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
